from app.schema import expected_schema_revision, schema_is_current


def test_expected_schema_revision_is_current_head() -> None:
    assert expected_schema_revision() == "0043_trip_expenses"
    assert len(expected_schema_revision()) <= 32
    assert schema_is_current("0042_trip_notes") is False
    assert schema_is_current("0041_ai_itinerary_refine") is False
    assert schema_is_current("0040_localized_names") is False
    assert schema_is_current("0040_localized_names") is False
    assert schema_is_current("0039_repair_dead_food_sources") is False
    assert schema_is_current("0038_trip_metadata") is False
    assert schema_is_current("0037_user_preferred_currency") is False
    assert schema_is_current("0036_food_taxonomy") is False
    assert schema_is_current("0035_hotspot_area_code") is False
    assert schema_is_current("0034_route_alternatives") is False
    assert schema_is_current("0032_remove_plus_codes") is False
    assert schema_is_current("0031_trip_item_coordinates") is False
    assert schema_is_current("0030_analytics_events") is False
    assert schema_is_current("0029_ui_saved_items") is False
    assert schema_is_current("0028_restaurant_sources") is False
    assert schema_is_current("0027_hotspot_restaurants") is False
    assert schema_is_current("0026_food_merchants_map_refs") is False
    assert schema_is_current("0025_hotspot_place_enrichment") is False
    assert schema_is_current("0024_deployment_center") is False
    assert schema_is_current("0023_flight_anchors") is False
    assert schema_is_current("0022_food_catalog") is False
    assert schema_is_current("0021_hotspot_guide_ai_search") is False
    assert schema_is_current("0020_itinerary_system_slots") is False
    assert schema_is_current("0019_hotspot_destination_id") is False
    assert schema_is_current("0018_hotspot_multilingual_guides") is False
    assert schema_is_current("0017_usage_settings") is False
    assert schema_is_current("0016_trip_route_segments") is False
    assert schema_is_current("0015_hotspot_depth_travel") is False
    assert schema_is_current("0014_user_preferred_locale") is False
    assert schema_is_current("0013_hotspot_discovery") is False
    assert schema_is_current("0012_line_price_alerts") is False
    assert schema_is_current("0011_auth_session_version") is False
    assert schema_is_current("0010_hotspot_intelligence") is False
    assert schema_is_current("0009_usage_account_status") is False
    assert schema_is_current("0008_flight_status_lookups") is False
    assert schema_is_current("0007_alert_integrity") is False
    assert schema_is_current("0002_itinerary_sharing") is False
    assert schema_is_current(None) is False
