type DatabaseCopy = Record<string, string>;
const zhTW: DatabaseCopy = {
  loading: "正在讀取資料庫狀態…", loadError: "無法讀取資料庫狀態", retry: "重新整理", status: "PostgreSQL 狀態", size: "資料庫容量", connections: "連線", active: "使用中", idle: "閒置", waiting: "等待中", max: "上限", cacheHit: "快取命中率", longTransactions: "長交易", lockWaits: "鎖等待", revision: "Schema 版本", current: "目前", expected: "預期", currentRevision: "版本一致", staleRevision: "需要升級", tables: "資料表容量", table: "資料表", rows: "估算筆數", data: "資料", indexes: "索引", total: "總容量", deadRows: "Dead rows", analyzed: "最近 Analyze", backups: "最近備份", backupNow: "建立備份", analyze: "執行 ANALYZE", maintenanceOff: "資料庫維護目前停用", operatorRequired: "需要 database_operator 角色與主機 allowlist", noBackups: "尚無備份紀錄", verified: "已驗證", failed: "失敗", operationRunning: "維護工作執行中", requestedBy: "提出者", createdAt: "建立時間", checksum: "Checksum", safeNote: "這裡只提供固定健康查詢、pg_dump 備份與 ANALYZE；不提供任意 SQL、資料列、下載、刪除或線上還原。", backupTitle: "確認建立資料庫備份", backupDescription: "主機代理會建立 PostgreSQL custom-format 備份、執行 pg_restore --list 驗證並套用保留規則。", analyzeTitle: "確認執行 ANALYZE", analyzeDescription: "主機代理只會執行受控 ANALYZE，不執行 VACUUM FULL、REINDEX 或 migration。", password: "目前密碼", typeConfirmation: "輸入確認文字", cancel: "取消", confirm: "確認執行", successQueued: "工作已排入佇列，狀態會自動更新。", agentUnavailable: "主機維護代理目前無法使用", backupsRetained: "保留最近 {count} 份", unavailable: "不可用", operation: "工作", statusLabel: "狀態",
};
const en: DatabaseCopy = {
  loading: "Loading database status…", loadError: "Database status could not be loaded", retry: "Refresh", status: "PostgreSQL status", size: "Database size", connections: "Connections", active: "Active", idle: "Idle", waiting: "Waiting", max: "Maximum", cacheHit: "Cache hit ratio", longTransactions: "Long transactions", lockWaits: "Lock waits", revision: "Schema revision", current: "Current", expected: "Expected", currentRevision: "Revision is current", staleRevision: "Upgrade required", tables: "Table capacity", table: "Table", rows: "Estimated rows", data: "Data", indexes: "Indexes", total: "Total size", deadRows: "Dead rows", analyzed: "Last analyzed", backups: "Recent backups", backupNow: "Create backup", analyze: "Run ANALYZE", maintenanceOff: "Database maintenance is disabled", operatorRequired: "Requires database_operator and the host allowlist", noBackups: "No backup record yet", verified: "Verified", failed: "Failed", operationRunning: "Maintenance operation in progress", requestedBy: "Requested by", createdAt: "Created", checksum: "Checksum", safeNote: "This center offers fixed health queries, pg_dump backup, and ANALYZE only. It has no arbitrary SQL, row browser, download, deletion, or online restore.", backupTitle: "Confirm database backup", backupDescription: "The host agent creates a PostgreSQL custom-format backup, verifies it with pg_restore --list, and applies retention.", analyzeTitle: "Confirm ANALYZE", analyzeDescription: "The host agent runs controlled ANALYZE only—never VACUUM FULL, REINDEX, or migrations.", password: "Current password", typeConfirmation: "Type confirmation", cancel: "Cancel", confirm: "Confirm", successQueued: "The operation is queued. Its status will update automatically.", agentUnavailable: "The host maintenance agent is unavailable", backupsRetained: "Keeping the latest {count} backups", unavailable: "Unavailable", operation: "Operation", statusLabel: "Status",
};
const zhCN = { ...zhTW, loading: "正在读取数据库状态…", loadError: "无法读取数据库状态", retry: "刷新", size: "数据库容量", connections: "连接", active: "使用中", idle: "空闲", waiting: "等待中", max: "上限", revision: "Schema 版本", currentRevision: "版本一致", staleRevision: "需要升级", tables: "数据表容量", table: "数据表", rows: "估算行数", data: "数据", indexes: "索引", total: "总容量", backups: "最近备份", backupNow: "创建备份", analyze: "执行 ANALYZE", maintenanceOff: "数据库维护目前停用", noBackups: "暂无备份记录", createdAt: "创建时间", safeNote: "这里只提供固定健康查询、pg_dump 备份与 ANALYZE；不提供任意 SQL、数据行、下载、删除或在线还原。", password: "当前密码", typeConfirmation: "输入确认文字", cancel: "取消", confirm: "确认执行", successQueued: "任务已进入队列，状态会自动更新。", unavailable: "不可用" };
const ja = { ...en, loading: "データベースの状態を読み込み中…", loadError: "データベースの状態を取得できません", retry: "再読み込み", status: "PostgreSQL の状態", size: "データベース容量", connections: "接続", active: "使用中", idle: "アイドル", waiting: "待機中", revision: "スキーマ版", currentRevision: "最新版です", staleRevision: "更新が必要", tables: "テーブル容量", table: "テーブル", rows: "推定行数", backups: "最近のバックアップ", backupNow: "バックアップ作成", analyze: "ANALYZE 実行", maintenanceOff: "データベース保守は無効です", noBackups: "バックアップ履歴はありません", safeNote: "固定ヘルス照会、pg_dump バックアップ、ANALYZE のみを提供します。任意 SQL、行閲覧、ダウンロード、削除、オンライン復元はありません。", password: "現在のパスワード", typeConfirmation: "確認文字を入力", cancel: "キャンセル", confirm: "実行", successQueued: "ジョブをキューに追加しました。状態は自動更新されます。", unavailable: "利用不可" };
const ko = { ...en, loading: "데이터베이스 상태 불러오는 중…", loadError: "데이터베이스 상태를 불러올 수 없습니다", retry: "새로고침", status: "PostgreSQL 상태", size: "데이터베이스 용량", connections: "연결", active: "사용 중", idle: "유휴", waiting: "대기", revision: "스키마 버전", currentRevision: "최신 버전", staleRevision: "업그레이드 필요", tables: "테이블 용량", table: "테이블", rows: "예상 행 수", backups: "최근 백업", backupNow: "백업 만들기", analyze: "ANALYZE 실행", maintenanceOff: "데이터베이스 유지 관리가 비활성화됨", noBackups: "백업 기록이 없습니다", safeNote: "고정 상태 조회, pg_dump 백업, ANALYZE만 제공합니다. 임의 SQL, 행 조회, 다운로드, 삭제, 온라인 복원은 제공하지 않습니다.", password: "현재 비밀번호", typeConfirmation: "확인 문구 입력", cancel: "취소", confirm: "실행", successQueued: "작업이 대기열에 추가되었습니다. 상태는 자동으로 갱신됩니다.", unavailable: "사용 불가" };
const copies: Record<string, DatabaseCopy> = { en, ja, ko, "zh-TW": zhTW, "zh-CN": zhCN };
const localizedOperations: Record<string, DatabaseCopy> = {
  "zh-CN": { operationRunning: "维护任务执行中", agentUnavailable: "主机维护代理目前不可用", operatorRequired: "需要 database_operator 角色与主机 allowlist", backupTitle: "确认创建数据库备份", backupDescription: "主机代理将创建 PostgreSQL custom-format 备份、执行 pg_restore --list 验证并应用保留规则。", analyzeTitle: "确认执行 ANALYZE", analyzeDescription: "主机代理只会执行受控 ANALYZE，不执行 VACUUM FULL、REINDEX 或 migration。" },
  ja: { operationRunning: "保守ジョブを実行中", agentUnavailable: "ホスト保守エージェントを利用できません", operatorRequired: "database_operator ロールとホスト allowlist が必要です", backupTitle: "データベースバックアップの作成を確認", backupDescription: "ホストエージェントが PostgreSQL custom-format バックアップを作成し、pg_restore --list で検証して保持ルールを適用します。", analyzeTitle: "ANALYZE の実行を確認", analyzeDescription: "ホストエージェントは管理された ANALYZE のみを実行し、VACUUM FULL、REINDEX、migration は実行しません。" },
  ko: { operationRunning: "유지 관리 작업 실행 중", agentUnavailable: "호스트 유지 관리 에이전트를 사용할 수 없습니다", operatorRequired: "database_operator 역할과 호스트 allowlist가 필요합니다", backupTitle: "데이터베이스 백업 생성 확인", backupDescription: "호스트 에이전트가 PostgreSQL custom-format 백업을 만들고 pg_restore --list로 검증한 뒤 보존 규칙을 적용합니다.", analyzeTitle: "ANALYZE 실행 확인", analyzeDescription: "호스트 에이전트는 통제된 ANALYZE만 실행하며 VACUUM FULL, REINDEX 또는 migration은 실행하지 않습니다." },
};
const localizedTableOperations: Record<string, DatabaseCopy> = {
  "zh-TW": { tablesCount: "public schema 共 {count} 個資料表", vacuumed: "最近 Vacuum", operationBackup: "資料庫備份", operationAnalyze: "資料表 Analyze", statusQueued: "等待中", statusRunning: "執行中", statusSucceeded: "完成", statusFailed: "失敗", setLocalPassword: "還沒有本機密碼？先設定安全密碼" },
  "zh-CN": { tablesCount: "public schema 共 {count} 个数据表", vacuumed: "最近 Vacuum", operationBackup: "数据库备份", operationAnalyze: "数据表 Analyze", statusQueued: "等待中", statusRunning: "执行中", statusSucceeded: "完成", statusFailed: "失败", setLocalPassword: "还没有本机密码？请先设置安全密码" },
  en: { tablesCount: "{count} tables in the public schema", vacuumed: "Last vacuum", operationBackup: "Database backup", operationAnalyze: "Table analyze", statusQueued: "Queued", statusRunning: "Running", statusSucceeded: "Succeeded", statusFailed: "Failed", setLocalPassword: "No local password yet? Set a secure password first" },
  ja: { tablesCount: "public スキーマに {count} テーブル", vacuumed: "最終 Vacuum", operationBackup: "データベースバックアップ", operationAnalyze: "テーブル Analyze", statusQueued: "待機中", statusRunning: "実行中", statusSucceeded: "完了", statusFailed: "失敗", setLocalPassword: "ローカルパスワードがない場合は、先に安全なパスワードを設定してください" },
  ko: { tablesCount: "public 스키마 테이블 {count}개", vacuumed: "최근 Vacuum", operationBackup: "데이터베이스 백업", operationAnalyze: "테이블 Analyze", statusQueued: "대기 중", statusRunning: "실행 중", statusSucceeded: "완료", statusFailed: "실패", setLocalPassword: "로컬 비밀번호가 없다면 먼저 안전한 비밀번호를 설정하세요" },
};
export function adminDatabaseCopy(locale: string): DatabaseCopy { return { ...(copies[locale] ?? en), ...(localizedOperations[locale] ?? {}), ...(localizedTableOperations[locale] ?? localizedTableOperations.en) }; }
export function copyValue(value: string, variables: Record<string, string | number>) { return Object.entries(variables).reduce((text, [key, replacement]) => text.replaceAll(`{${key}}`, String(replacement)), value); }
