type Copy = {
  console: string; groups: Record<string, string>; nav: Record<string, string>;
  openMenu: string; closeMenu: string; collapse: string; expand: string; command: string;
  commandHint: string; noCommand: string; recent: string; environment: string; healthy: string;
  degraded: string; unavailable: string; signOut: string; account: string; forbiddenTitle: string;
  forbiddenBody: string; serviceTitle: string; serviceBody: string; retry: string;
  databaseTitle: string; databaseDescription: string; auditTitle: string; auditDescription: string;
  dashboardLoadError: string; dashboardUsers: string; dashboardPending: string; dashboardJobs: string;
  dashboardIncidents: string; dashboardSummary: string; dashboardHealth: string;
  dashboardHealthDetail: string; dashboardCatalogs: string;
  services: Record<string, string>; serviceStatuses: Record<string, string>;
};

const zhTW: Copy = {
  console: "營運控制台", groups: { overview: "總覽", content: "內容", community: "社群", operations: "營運", system: "系統" },
  nav: { dashboard: "營運總覽", hotspots: "景點", foods: "美食", hotels: "飯店", catalogReview: "內容審核", travelServices: "旅遊服務", community: "社群管理", pets: "寵物友善", partners: "合作夥伴", analytics: "分析", users: "使用者", usage: "方案與次數", audit: "稽核紀錄", layout: "版面管理", uiText: "前台文案", system: "系統設定", providers: "Provider 與金鑰", database: "資料庫", deployments: "部署中心" },
  openMenu: "開啟營運選單", closeMenu: "關閉營運選單", collapse: "收合側欄", expand: "展開側欄", command: "搜尋頁面與操作", commandHint: "輸入頁面、分頁或操作名稱…", noCommand: "沒有符合的後台功能", recent: "最近開啟", environment: "環境", healthy: "服務正常", degraded: "部分服務異常", unavailable: "服務無法使用", signOut: "登出", account: "帳號設定", forbiddenTitle: "你沒有這個後台的權限", forbiddenBody: "目前帳號已登入，但未被授予營運控制台能力。請聯絡 owner 調整角色。", serviceTitle: "營運控制台暫時無法連線", serviceBody: "權限與系統狀態無法安全確認，因此沒有顯示管理內容。請稍後重試。", retry: "重新載入", databaseTitle: "資料庫維運", databaseDescription: "查看 PostgreSQL 健康度、容量與備份狀態，並執行受控維護。", auditTitle: "稽核紀錄", auditDescription: "追蹤管理操作的操作者、目標、時間與結果，不顯示敏感資料。", dashboardLoadError: "無法載入營運總覽", dashboardUsers: "使用者", dashboardPending: "待處理", dashboardJobs: "背景工作", dashboardIncidents: "異常", dashboardSummary: "營運摘要", dashboardHealth: "系統狀態", dashboardHealthDetail: "API、資料庫、Redis、Worker、備份與部署代理", dashboardCatalogs: "內容目錄", services: { database: "資料庫", redis: "Redis", providers: "Provider", background_jobs: "背景工作", backup: "備份", deployment: "部署代理", api: "API", web: "Web" }, serviceStatuses: { healthy: "正常", degraded: "部分異常", unavailable: "無法使用", disabled: "未啟用", unknown: "未知" },
};
const zhCN: Copy = { ...zhTW, console: "运营控制台", groups: { overview: "总览", content: "内容", community: "社区", operations: "运营", system: "系统" }, openMenu: "打开运营菜单", closeMenu: "关闭运营菜单", collapse: "收起侧栏", expand: "展开侧栏", command: "搜索页面与操作", commandHint: "输入页面、分页或操作名称…", noCommand: "没有匹配的后台功能", recent: "最近打开", healthy: "服务正常", degraded: "部分服务异常", unavailable: "服务不可用", signOut: "退出登录", account: "账号设置", forbiddenTitle: "你没有这个后台的权限", forbiddenBody: "当前账号已登录，但未获授运营控制台权限。请联系 owner 调整角色。", serviceTitle: "运营控制台暂时无法连接", serviceBody: "无法安全确认权限与系统状态，因此未显示管理内容。请稍后重试。", retry: "重新加载", databaseTitle: "数据库运维", databaseDescription: "查看 PostgreSQL 健康度、容量与备份状态，并执行受控维护。", auditTitle: "审计记录", auditDescription: "追踪管理操作的操作者、目标、时间与结果，不显示敏感数据。" };
const en: Copy = { ...zhTW, console: "Operations console", groups: { overview: "Overview", content: "Content", community: "Community", operations: "Operations", system: "System" }, nav: { dashboard: "Operations overview", hotspots: "Hotspots", foods: "Food", hotels: "Hotels", catalogReview: "Content review", travelServices: "Travel services", community: "Community", pets: "Pet-friendly", partners: "Partners", analytics: "Analytics", users: "Users", usage: "Plans & usage", audit: "Audit log", layout: "Layout", uiText: "Site copy", system: "System settings", providers: "Providers & keys", database: "Database", deployments: "Deployments" }, openMenu: "Open operations menu", closeMenu: "Close operations menu", collapse: "Collapse sidebar", expand: "Expand sidebar", command: "Search pages and actions", commandHint: "Type a page, section, or action…", noCommand: "No admin destination matches", recent: "Recently opened", environment: "Environment", healthy: "Services healthy", degraded: "Some services degraded", unavailable: "Service unavailable", signOut: "Sign out", account: "Account settings", forbiddenTitle: "You don’t have access to this console", forbiddenBody: "This account is signed in but has no operations-console capability. Ask an owner to update your roles.", serviceTitle: "The operations console is unavailable", serviceBody: "Permissions and system status could not be verified safely, so no admin content is shown. Try again shortly.", retry: "Reload", databaseTitle: "Database operations", databaseDescription: "Review PostgreSQL health, capacity, and backups, and run controlled maintenance.", auditTitle: "Audit log", auditDescription: "Trace administrator actions, targets, times, and outcomes without exposing sensitive data." };
const ja: Copy = { ...en, console: "運用コンソール", groups: { overview: "概要", content: "コンテンツ", community: "コミュニティ", operations: "運用", system: "システム" }, openMenu: "運用メニューを開く", closeMenu: "運用メニューを閉じる", collapse: "サイドバーを閉じる", expand: "サイドバーを開く", command: "ページと操作を検索", commandHint: "ページ、タブ、操作を入力…", noCommand: "一致する管理機能がありません", recent: "最近開いたページ", environment: "環境", healthy: "サービス正常", degraded: "一部サービスに問題", unavailable: "サービス利用不可", signOut: "ログアウト", account: "アカウント設定", forbiddenTitle: "この管理画面への権限がありません", forbiddenBody: "ログイン中ですが、運用コンソールの権限が付与されていません。owner にロール変更を依頼してください。", serviceTitle: "運用コンソールに接続できません", serviceBody: "権限とシステム状態を安全に確認できないため、管理内容は表示していません。しばらくしてから再試行してください。", retry: "再読み込み", databaseTitle: "データベース運用", databaseDescription: "PostgreSQL の状態、容量、バックアップを確認し、安全な保守を実行します。", auditTitle: "監査ログ", auditDescription: "機密情報を表示せず、管理操作の実行者、対象、時刻、結果を確認します。" };
const ko: Copy = { ...en, console: "운영 콘솔", groups: { overview: "개요", content: "콘텐츠", community: "커뮤니티", operations: "운영", system: "시스템" }, openMenu: "운영 메뉴 열기", closeMenu: "운영 메뉴 닫기", collapse: "사이드바 접기", expand: "사이드바 펼치기", command: "페이지 및 작업 검색", commandHint: "페이지, 탭 또는 작업 입력…", noCommand: "일치하는 관리자 기능이 없습니다", recent: "최근에 연 페이지", environment: "환경", healthy: "서비스 정상", degraded: "일부 서비스 저하", unavailable: "서비스 사용 불가", signOut: "로그아웃", account: "계정 설정", forbiddenTitle: "이 콘솔에 접근할 권한이 없습니다", forbiddenBody: "로그인되어 있지만 운영 콘솔 권한이 없습니다. owner에게 역할 변경을 요청하세요.", serviceTitle: "운영 콘솔에 연결할 수 없습니다", serviceBody: "권한과 시스템 상태를 안전하게 확인할 수 없어 관리자 내용을 표시하지 않습니다. 잠시 후 다시 시도하세요.", retry: "새로고침", databaseTitle: "데이터베이스 운영", databaseDescription: "PostgreSQL 상태, 용량, 백업을 확인하고 통제된 유지 관리를 실행합니다.", auditTitle: "감사 로그", auditDescription: "민감한 정보를 노출하지 않고 관리자 작업, 대상, 시간 및 결과을 확인합니다." };

const copies: Record<string, Copy> = { en, ja, ko, "zh-TW": zhTW, "zh-CN": zhCN };
const localizedNavigation: Record<string, Record<string, string>> = {
  en: en.nav,
  "zh-TW": zhTW.nav,
  "zh-CN": { dashboard: "运营总览", hotspots: "景点", foods: "美食", hotels: "酒店", catalogReview: "内容审核", travelServices: "旅行服务", community: "社区管理", pets: "宠物友好", partners: "合作伙伴", analytics: "分析", users: "用户", usage: "方案与次数", audit: "审计记录", layout: "版面管理", uiText: "前台文案", system: "系统设置", providers: "Provider 与密钥", database: "数据库", deployments: "部署中心" },
  ja: { dashboard: "運用概要", hotspots: "スポット", foods: "グルメ", hotels: "ホテル", catalogReview: "コンテンツ審査", travelServices: "旅行サービス", community: "コミュニティ管理", pets: "ペット対応", partners: "パートナー", analytics: "分析", users: "ユーザー", usage: "プランと利用回数", audit: "監査ログ", layout: "レイアウト", uiText: "サイト文言", system: "システム設定", providers: "プロバイダーとキー", database: "データベース", deployments: "デプロイ" },
  ko: { dashboard: "운영 개요", hotspots: "명소", foods: "음식", hotels: "호텔", catalogReview: "콘텐츠 검토", travelServices: "여행 서비스", community: "커뮤니티 관리", pets: "반려동물", partners: "파트너", analytics: "분석", users: "사용자", usage: "요금제 및 사용량", audit: "감사 로그", layout: "레이아웃", uiText: "사이트 문구", system: "시스템 설정", providers: "공급자 및 키", database: "데이터베이스", deployments: "배포" },
};
const localizedDashboard: Record<string, Partial<Copy>> = {
  en: { dashboardLoadError: "The operations overview could not be loaded", dashboardUsers: "Users", dashboardPending: "Pending", dashboardJobs: "Background jobs", dashboardIncidents: "Incidents", dashboardSummary: "Operations summary", dashboardHealth: "System status", dashboardHealthDetail: "API, database, Redis, workers, backups, and deployment agent", dashboardCatalogs: "Content catalogs" },
  "zh-TW": { dashboardLoadError: "無法載入營運總覽", dashboardUsers: "使用者", dashboardPending: "待處理", dashboardJobs: "背景工作", dashboardIncidents: "異常", dashboardSummary: "營運摘要", dashboardHealth: "系統狀態", dashboardHealthDetail: "API、資料庫、Redis、Worker、備份與部署代理", dashboardCatalogs: "內容目錄" },
  "zh-CN": { dashboardLoadError: "无法加载运营总览", dashboardUsers: "用户", dashboardPending: "待处理", dashboardJobs: "后台任务", dashboardIncidents: "异常", dashboardSummary: "运营摘要", dashboardHealth: "系统状态", dashboardHealthDetail: "API、数据库、Redis、Worker、备份与部署代理", dashboardCatalogs: "内容目录" },
  ja: { dashboardLoadError: "運用概要を読み込めません", dashboardUsers: "ユーザー", dashboardPending: "未処理", dashboardJobs: "バックグラウンドジョブ", dashboardIncidents: "異常", dashboardSummary: "運用サマリー", dashboardHealth: "システム状態", dashboardHealthDetail: "API、データベース、Redis、ワーカー、バックアップ、デプロイエージェント", dashboardCatalogs: "コンテンツ一覧" },
  ko: { dashboardLoadError: "운영 개요를 불러올 수 없습니다", dashboardUsers: "사용자", dashboardPending: "처리 대기", dashboardJobs: "백그라운드 작업", dashboardIncidents: "이상", dashboardSummary: "운영 요약", dashboardHealth: "시스템 상태", dashboardHealthDetail: "API, 데이터베이스, Redis, 워커, 백업 및 배포 에이전트", dashboardCatalogs: "콘텐츠 카탈로그" },
};
const localizedServices: Record<string, Pick<Copy, "services" | "serviceStatuses">> = {
  "zh-TW": { services: zhTW.services, serviceStatuses: zhTW.serviceStatuses },
  "zh-CN": { services: { database: "数据库", redis: "Redis", providers: "Provider", background_jobs: "后台任务", backup: "备份", deployment: "部署代理", api: "API", web: "Web" }, serviceStatuses: { healthy: "正常", degraded: "部分异常", unavailable: "不可用", disabled: "未启用", unknown: "未知" } },
  en: { services: { database: "Database", redis: "Redis", providers: "Providers", background_jobs: "Background jobs", backup: "Backups", deployment: "Deployment agent", api: "API", web: "Web" }, serviceStatuses: { healthy: "Healthy", degraded: "Degraded", unavailable: "Unavailable", disabled: "Disabled", unknown: "Unknown" } },
  ja: { services: { database: "データベース", redis: "Redis", providers: "プロバイダー", background_jobs: "バックグラウンドジョブ", backup: "バックアップ", deployment: "デプロイエージェント", api: "API", web: "Web" }, serviceStatuses: { healthy: "正常", degraded: "一部異常", unavailable: "利用不可", disabled: "未設定", unknown: "不明" } },
  ko: { services: { database: "데이터베이스", redis: "Redis", providers: "공급자", background_jobs: "백그라운드 작업", backup: "백업", deployment: "배포 에이전트", api: "API", web: "Web" }, serviceStatuses: { healthy: "정상", degraded: "일부 저하", unavailable: "사용 불가", disabled: "비활성", unknown: "알 수 없음" } },
};
export function adminOperationsCopy(locale: string): Copy {
  const selected = copies[locale] ?? en;
  return { ...selected, ...(localizedDashboard[locale] ?? localizedDashboard.en), ...(localizedServices[locale] ?? localizedServices.en), nav: localizedNavigation[locale] ?? en.nav };
}
