type AuditCopy = Record<string, string>;
const zhTW: AuditCopy = { loading: "正在讀取稽核紀錄…", error: "無法讀取稽核紀錄", retry: "重新讀取", actor: "操作者", actorPlaceholder: "Email 或 ID", action: "動作", actionPlaceholder: "例如 user.suspended", target: "目標", targetPlaceholder: "類型或 ID", result: "結果", allResults: "全部結果", success: "成功", failure: "失敗", from: "開始日期", to: "結束日期", search: "套用篩選", clear: "清除", time: "時間", details: "詳情", noRecords: "沒有符合條件的稽核紀錄", page: "第 {page} / {pages} 頁，共 {total} 筆", previous: "上一頁", next: "下一頁", open: "查看詳情", close: "關閉", eventDetail: "稽核事件", metadata: "安全摘要", deletedAccount: "已刪除帳號", requestId: "請求識別碼", noMetadata: "沒有額外摘要。" };
const en: AuditCopy = { loading: "Loading audit events…", error: "Audit events could not be loaded", retry: "Retry", actor: "Actor", actorPlaceholder: "Email or ID", action: "Action", actionPlaceholder: "e.g. user.suspended", target: "Target", targetPlaceholder: "Type or ID", result: "Result", allResults: "All outcomes", success: "Success", failure: "Failure", from: "From", to: "To", search: "Apply filters", clear: "Clear", time: "Time", details: "Details", noRecords: "No audit event matches these filters", page: "Page {page} of {pages}, {total} events", previous: "Previous", next: "Next", open: "View details", close: "Close", eventDetail: "Audit event", metadata: "Safe summary", deletedAccount: "Deleted account", requestId: "Request ID", noMetadata: "No additional summary." };
const zhCN = { ...zhTW, loading: "正在读取审计记录…", error: "无法读取审计记录", actor: "操作人", action: "操作", target: "目标", result: "结果", allResults: "全部结果", success: "成功", failure: "失败", from: "开始日期", to: "结束日期", search: "应用筛选", clear: "清除", time: "时间", details: "详情", noRecords: "没有符合条件的审计记录", previous: "上一页", next: "下一页", open: "查看详情", close: "关闭", eventDetail: "审计事件", metadata: "安全摘要" };
const ja = { ...en, loading: "監査ログを読み込み中…", error: "監査ログを取得できません", actor: "実行者", action: "操作", target: "対象", result: "結果", allResults: "すべて", success: "成功", failure: "失敗", from: "開始日", to: "終了日", search: "絞り込む", clear: "クリア", time: "時刻", details: "詳細", noRecords: "条件に一致する監査ログはありません", previous: "前へ", next: "次へ", open: "詳細を見る", close: "閉じる", eventDetail: "監査イベント", metadata: "安全な概要" };
const ko = { ...en, loading: "감사 로그 불러오는 중…", error: "감사 로그를 불러올 수 없습니다", actor: "작업자", action: "작업", target: "대상", result: "결과", allResults: "모든 결과", success: "성공", failure: "실패", from: "시작일", to: "종료일", search: "필터 적용", clear: "초기화", time: "시간", details: "상세", noRecords: "조건에 맞는 감사 로그가 없습니다", previous: "이전", next: "다음", open: "상세 보기", close: "닫기", eventDetail: "감사 이벤트", metadata: "안전 요약" };
const copies: Record<string, AuditCopy> = { en, ja, ko, "zh-TW": zhTW, "zh-CN": zhCN };
const localizedRetry: Record<string, string> = { "zh-TW": "重新讀取", "zh-CN": "重新读取", ja: "再読み込み", ko: "다시 시도", en: "Retry" };
export function adminAuditCopy(locale: string): AuditCopy { return { ...(copies[locale] ?? en), retry: localizedRetry[locale] ?? localizedRetry.en }; }
export function auditFormat(value: string, variables: Record<string, string | number>) { return Object.entries(variables).reduce((text, [key, replacement]) => text.replaceAll(`{${key}}`, String(replacement)), value); }
