type UsersCopy = Record<string, string>;
const zhTW: UsersCopy = {
  filters: "進階篩選",
  status: "帳號狀態",
  all: "全部",
  active: "啟用",
  inactive: "停用",
  suspended: "停權",
  erasurePending: "等待清除",
  role: "管理角色",
  verification: "Email 驗證",
  verified: "已驗證",
  unverified: "未驗證",
  loginMethod: "登入方式",
  registeredFrom: "註冊起日",
  registeredTo: "註冊迄日",
  sort: "排序",
  createdAt: "註冊時間",
  lastLogin: "最後登入",
  email: "Email",
  updatedAt: "更新時間",
  remainingUses: "剩餘次數",
  descending: "新到舊",
  ascending: "舊到新",
  apply: "套用",
  reset: "清除",
  never: "從未登入",
  authMethods: "登入方式",
  activity: "活動摘要",
  activityFilter: "產品活動",
  hasActivity: "有活動",
  noActivity: "尚無活動",
  lastActivity: "最後活動",
  activityCount: "活動總量",
  trips: "旅程",
  searches: "搜尋",
  alerts: "通知",
  posts: "貼文",
  comments: "留言",
  roles: "管理角色",
  rolesHint: "一位管理員可有多個角色；環境 owner 無法從畫面移除。",
  roleReason: "角色變更原因",
  rolesExpireAt: "角色到期時間（選填）",
  ownerNoExpiry: "Owner 是永久復原角色，不可設定到期時間。",
  saveRoles: "更新角色",
  suspension: "停權管理",
  suspensionReason: "停權／解除原因",
  suspensionUntil: "停權至（留空為永久）",
  timedSuspensionLimit:
    "限時停權最多 90 天；更長期間請使用需密碼確認的永久停權。",
  suspend: "套用停權",
  unsuspend: "解除停權",
  sessions: "登入工作階段",
  revokeSessions: "強制全部裝置登出",
  verificationTitle: "Email 驗證",
  resendVerification: "重送驗證信",
  erasure: "個資清除",
  erasureHint:
    "安排後有 24 小時寬限期；不可清除自己、環境管理員或最後一位 owner。",
  scheduleErasure: "安排個資清除",
  cancelErasure: "取消個資清除",
  scheduledFor: "預計清除時間",
  operationReason: "操作原因",
  stepupPassword: "目前密碼",
  typeConfirmation: "輸入確認文字",
  rolesConfirmation: "確認角色變更",
  suspendConfirmation: "確認永久停權",
  eraseConfirmation: "確認個資清除",
  confirmPermanentSuspension: "套用永久停權",
  confirmErasure: "安排清除",
  sensitiveDescription: "這是敏感管理操作。請重新驗證目前密碼並輸入指定文字。",
  setLocalPassword: "還沒有本機密碼？先設定安全密碼",
  saved: "變更已儲存。",
  revoked: "所有既有工作階段已撤銷。",
  verificationSent: "驗證信已重新排送。",
  rolesViewer: "唯讀",
  rolesSupport: "客服",
  rolesContent: "內容",
  rolesOperations: "營運",
  rolesDatabase: "資料庫維運",
  rolesDeployer: "部署",
  rolesOwner: "Owner",
  permanent: "永久",
  environmentOwner: "環境 owner",
  erasureStatus: "清除狀態",
  providerEmail: "供應商 Email",
  linkedAt: "連結時間",
  loadingDetail: "正在讀取使用者詳情…",
  operationFailed: "操作未完成",
};
const en: UsersCopy = {
  filters: "Advanced filters",
  status: "Account status",
  all: "All",
  active: "Active",
  inactive: "Inactive",
  suspended: "Suspended",
  erasurePending: "Erasure pending",
  role: "Admin role",
  verification: "Email verification",
  verified: "Verified",
  unverified: "Unverified",
  loginMethod: "Sign-in method",
  registeredFrom: "Registered from",
  registeredTo: "Registered to",
  sort: "Sort",
  createdAt: "Registered",
  lastLogin: "Last sign-in",
  email: "Email",
  updatedAt: "Updated",
  remainingUses: "Remaining usage",
  descending: "Newest first",
  ascending: "Oldest first",
  apply: "Apply",
  reset: "Clear",
  never: "Never signed in",
  authMethods: "Sign-in methods",
  activity: "Activity summary",
  activityFilter: "Product activity",
  hasActivity: "Has activity",
  noActivity: "No activity yet",
  lastActivity: "Last activity",
  activityCount: "Activity volume",
  trips: "Trips",
  searches: "Searches",
  alerts: "Alerts",
  posts: "Posts",
  comments: "Comments",
  roles: "Admin roles",
  rolesHint:
    "An administrator can hold multiple roles. Environment owners cannot be removed here.",
  roleReason: "Reason for role change",
  rolesExpireAt: "Role expiry (optional)",
  ownerNoExpiry: "Owner is a permanent recovery role and cannot expire.",
  saveRoles: "Update roles",
  suspension: "Suspension",
  suspensionReason: "Suspension / release reason",
  suspensionUntil: "Suspended until (empty means permanent)",
  timedSuspensionLimit:
    "Timed suspension is limited to 90 days. Use password-confirmed permanent suspension for longer periods.",
  suspend: "Apply suspension",
  unsuspend: "Lift suspension",
  sessions: "Sign-in sessions",
  revokeSessions: "Force sign out on every device",
  verificationTitle: "Email verification",
  resendVerification: "Resend verification email",
  erasure: "Personal-data erasure",
  erasureHint:
    "There is a 24-hour grace period. You cannot erase yourself, an environment owner, or the last owner.",
  scheduleErasure: "Schedule erasure",
  cancelErasure: "Cancel erasure",
  scheduledFor: "Scheduled for",
  operationReason: "Operation reason",
  stepupPassword: "Current password",
  typeConfirmation: "Type confirmation",
  rolesConfirmation: "Confirm role change",
  suspendConfirmation: "Confirm permanent suspension",
  eraseConfirmation: "Confirm personal-data erasure",
  confirmPermanentSuspension: "Apply permanent suspension",
  confirmErasure: "Schedule erasure",
  sensitiveDescription:
    "This is a sensitive admin operation. Re-enter your current password and type the requested phrase.",
  setLocalPassword: "No local password yet? Set a secure password first",
  saved: "Changes saved.",
  revoked: "Every existing session was revoked.",
  verificationSent: "The verification message was queued again.",
  rolesViewer: "Viewer",
  rolesSupport: "Support",
  rolesContent: "Content",
  rolesOperations: "Operations",
  rolesDatabase: "Database operator",
  rolesDeployer: "Deployer",
  rolesOwner: "Owner",
  permanent: "Permanent",
  environmentOwner: "Environment owner",
  erasureStatus: "Erasure status",
  providerEmail: "Provider email",
  linkedAt: "Linked",
  loadingDetail: "Loading user details…",
  operationFailed: "Operation failed",
};
const zhCN = {
  ...zhTW,
  filters: "高级筛选",
  status: "账号状态",
  all: "全部",
  active: "启用",
  inactive: "停用",
  suspended: "停权",
  erasurePending: "等待清除",
  role: "管理角色",
  verification: "Email 验证",
  verified: "已验证",
  unverified: "未验证",
  loginMethod: "登录方式",
  registeredFrom: "注册起日",
  registeredTo: "注册止日",
  sort: "排序",
  createdAt: "注册时间",
  lastLogin: "最后登录",
  apply: "应用",
  reset: "清除",
  never: "从未登录",
  authMethods: "登录方式",
  activity: "活动摘要",
  activityFilter: "产品活动",
  hasActivity: "有活动",
  noActivity: "暂无活动",
  lastActivity: "最后活动",
  activityCount: "活动总量",
  roles: "管理角色",
  suspension: "停权管理",
  suspend: "应用停权",
  unsuspend: "解除停权",
  sessions: "登录会话",
  revokeSessions: "强制所有设备退出",
  verificationTitle: "Email 验证",
  resendVerification: "重发验证邮件",
  erasure: "个人信息清除",
  scheduleErasure: "安排个人信息清除",
  cancelErasure: "取消个人信息清除",
  operationReason: "操作原因",
  stepupPassword: "当前密码",
  typeConfirmation: "输入确认文字",
  saved: "更改已保存。",
};
const ja = {
  ...en,
  filters: "詳細フィルター",
  status: "アカウント状態",
  all: "すべて",
  active: "有効",
  inactive: "無効",
  suspended: "停止中",
  erasurePending: "削除待ち",
  role: "管理ロール",
  verification: "メール確認",
  verified: "確認済み",
  unverified: "未確認",
  loginMethod: "ログイン方法",
  registeredFrom: "登録開始日",
  registeredTo: "登録終了日",
  sort: "並び順",
  createdAt: "登録日時",
  lastLogin: "最終ログイン",
  apply: "適用",
  reset: "クリア",
  never: "ログインなし",
  authMethods: "ログイン方法",
  activity: "利用状況",
  activityFilter: "プロダクト利用",
  hasActivity: "利用あり",
  noActivity: "まだ利用なし",
  lastActivity: "最終利用",
  activityCount: "利用件数",
  roles: "管理ロール",
  suspension: "利用停止",
  suspend: "停止する",
  unsuspend: "停止解除",
  sessions: "ログインセッション",
  revokeSessions: "全端末をログアウト",
  verificationTitle: "メール確認",
  resendVerification: "確認メールを再送",
  erasure: "個人情報削除",
  scheduleErasure: "削除を予約",
  cancelErasure: "削除予約を取消",
  operationReason: "操作理由",
  stepupPassword: "現在のパスワード",
  typeConfirmation: "確認文字を入力",
  saved: "変更を保存しました。",
};
const ko = {
  ...en,
  filters: "고급 필터",
  status: "계정 상태",
  all: "전체",
  active: "활성",
  inactive: "비활성",
  suspended: "정지",
  erasurePending: "삭제 대기",
  role: "관리자 역할",
  verification: "이메일 인증",
  verified: "인증됨",
  unverified: "미인증",
  loginMethod: "로그인 방식",
  registeredFrom: "가입 시작일",
  registeredTo: "가입 종료일",
  sort: "정렬",
  createdAt: "가입 시간",
  lastLogin: "마지막 로그인",
  apply: "적용",
  reset: "초기화",
  never: "로그인 기록 없음",
  authMethods: "로그인 방식",
  activity: "활동 요약",
  activityFilter: "제품 활동",
  hasActivity: "활동 있음",
  noActivity: "아직 활동 없음",
  lastActivity: "마지막 활동",
  activityCount: "활동 건수",
  roles: "관리자 역할",
  suspension: "계정 정지",
  suspend: "정지 적용",
  unsuspend: "정지 해제",
  sessions: "로그인 세션",
  revokeSessions: "모든 기기에서 강제 로그아웃",
  verificationTitle: "이메일 인증",
  resendVerification: "인증 메일 재전송",
  erasure: "개인정보 삭제",
  scheduleErasure: "삭제 예약",
  cancelErasure: "삭제 예약 취소",
  operationReason: "작업 사유",
  stepupPassword: "현재 비밀번호",
  typeConfirmation: "확인 문구 입력",
  saved: "변경 사항을 저장했습니다.",
};
const copies: Record<string, UsersCopy> = {
  en,
  ja,
  ko,
  "zh-TW": zhTW,
  "zh-CN": zhCN,
};
const localizedSensitiveActions: Record<string, UsersCopy> = {
  "zh-CN": {
    rolesExpireAt: "角色到期时间（可选）",
    ownerNoExpiry: "Owner 是永久恢复角色，不能设置到期时间。",
    timedSuspensionLimit:
      "限时停权最多 90 天；更长期间请使用需要密码确认的永久停权。",
    rolesConfirmation: "确认角色变更",
    suspendConfirmation: "确认永久停权",
    eraseConfirmation: "确认清除个人信息",
    confirmPermanentSuspension: "应用永久停权",
    confirmErasure: "安排清除",
    setLocalPassword: "还没有本机密码？请先设置安全密码",
    loadingDetail: "正在读取用户详情…",
    operationFailed: "操作未完成",
  },
  ja: {
    rolesExpireAt: "ロール有効期限（任意）",
    ownerNoExpiry:
      "Owner は永続的な復旧ロールのため、有効期限を設定できません。",
    timedSuspensionLimit:
      "期限付き停止は最大 90 日です。それ以上はパスワード確認付きの無期限停止を使用してください。",
    rolesConfirmation: "ロール変更を確認",
    suspendConfirmation: "無期限の利用停止を確認",
    eraseConfirmation: "個人情報削除を確認",
    confirmPermanentSuspension: "無期限で停止",
    confirmErasure: "削除を予約",
    setLocalPassword:
      "ローカルパスワードがない場合は、先に安全なパスワードを設定してください",
    loadingDetail: "ユーザー詳細を読み込み中…",
    operationFailed: "操作を完了できません",
  },
  ko: {
    rolesExpireAt: "역할 만료 시간 (선택)",
    ownerNoExpiry:
      "Owner는 영구 복구 역할이므로 만료 시간을 설정할 수 없습니다.",
    timedSuspensionLimit:
      "기간 정지는 최대 90일입니다. 그보다 길면 비밀번호 확인이 필요한 영구 정지를 사용하세요.",
    rolesConfirmation: "역할 변경 확인",
    suspendConfirmation: "영구 정지 확인",
    eraseConfirmation: "개인정보 삭제 확인",
    confirmPermanentSuspension: "영구 정지 적용",
    confirmErasure: "삭제 예약",
    setLocalPassword:
      "로컬 비밀번호가 없다면 먼저 안전한 비밀번호를 설정하세요",
    loadingDetail: "사용자 상세 불러오는 중…",
    operationFailed: "작업을 완료하지 못했습니다",
  },
};
export function adminUsersCopy(locale: string): UsersCopy {
  return {
    ...(copies[locale] ?? en),
    ...(localizedSensitiveActions[locale] ?? {}),
  };
}
