const en = {
  explore: "Explore", collections: "Collections", trips: "My trips", my: "Account", publish: "Share a story", notifications: "Notifications",
  eyebrow: "A little curiosity. Your next journey.", title: "Find somewhere worth going.", subtitle: "Places, food and stories from real sources — ready to become your next trip.",
  search: "Search", placeholder: "A city, a place, or something you love", searchLabel: "Search travel ideas", suggestions: "Keyword suggestions", matched: "Results for", all: "All", destination: "Destination", topic: "Topic", language: "Content language", any: "Any", clear: "Clear filters",
  recommended: "For you", latest: "Latest", following: "Following", feed: "Discover your next stop", filters: "Refine your discovery", preferences: "Your interests", preferenceHelp: "Only interests you choose, saved items and followed creators inform these recommendations. Your browsing history is not used.",
  savedSignal: "Use my saved items", followingSignal: "Use creators I follow", save: "Save interests", reset: "Reset interests and hidden items", cancel: "Cancel", dismiss: "Not interested", dismissed: "Hidden from your recommendations", undo: "Undo", reason: "Why this appears", defaultReason: "From the available published collection", login: "Sign in to continue", loginFollowing: "Sign in to see creators you follow", unavailable: "Discovery is not available right now.", empty: "No matches yet. Try a different place or fewer filters.", loading: "Finding travel ideas…", more: "Show more", retry: "Try again", details: "Read more", source: "Original source", originalLanguage: "Original language", undated: "Publication date not provided", planning: "Ready to plan?", planningHelp: "Build a trip with the places you have discovered.", plan: "Plan my trip",
  sourceKinds: { editorial: "Editorial", official: "Official source", community: "Community" },
  kinds: { hotspot: "Places", food: "Food", merchant: "Local spots", hotel: "Hotels", article: "Guides", video: "Videos", post: "Stories", itinerary: "Itineraries" },
  video: "YouTube video", loadVideo: "Load video", videoPrivacy: "YouTube connects only when you choose to load the player. It will not autoplay.", videoFallback: "This video is available on the original source.", videoUrl: "YouTube links (one per line, up to 5)", videoHelp: "Paste a YouTube watch, Shorts or youtu.be URL. We keep the video reference, not the video file.", invalidVideo: "Please enter up to 5 valid, unique YouTube links.",
  invitations: "Creator invitations", userId: "User ID", lookup: "Look up", invited: "Invited creator", inviteHelp: "An invitation grants publishing eligibility, not admin access or automatic approval.", inviteOnly: "Publishing currently requires a creator invitation. You can still save your draft.", reasonLabel: "Reason", update: "Update invitation", saved: "Saved", private: "Only you can see this collection", collectionGuide: "Open guide", collectionHotel: "Open hotel",
};
export type DiscoveryCopy = typeof en;
const zhTW: DiscoveryCopy = {
  explore:"探索",collections:"收藏",trips:"我的旅行",my:"我的",publish:"分享旅程",notifications:"通知",
  eyebrow:"從一點好奇，開始下一趟旅行。",title:"找到值得出發的地方。",subtitle:"有來源的景點、美食與旅人故事，讓靈感慢慢變成你的行程。",search:"搜尋",placeholder:"城市、景點，或你喜歡的旅行方式",searchLabel:"搜尋旅行靈感",suggestions:"關鍵字建議",matched:"搜尋結果",all:"全部",destination:"目的地",topic:"主題",language:"內容語言",any:"不限",clear:"清除篩選",
  recommended:"為你推薦",latest:"最新",following:"追蹤中",feed:"下一站，從這裡發現",filters:"縮小探索範圍",preferences:"我的興趣",preferenceHelp:"推薦只使用你明確選擇的興趣、收藏與追蹤作者，不使用瀏覽紀錄。",savedSignal:"參考我的收藏",followingSignal:"參考追蹤的作者",save:"儲存興趣",reset:"重設興趣與隱藏內容",cancel:"取消",dismiss:"不感興趣",dismissed:"已從你的推薦隱藏",undo:"復原",reason:"推薦原因",defaultReason:"來自目前可閱讀的公開內容",login:"登入後繼續",loginFollowing:"登入以閱讀追蹤作者的內容",unavailable:"探索目前暫時無法使用。",empty:"還沒有符合的內容，試試其他地方或減少篩選條件。",loading:"正在尋找旅行靈感…",more:"載入更多",retry:"重試",details:"閱讀詳情",source:"查看原始來源",originalLanguage:"原文語言",undated:"來源未提供發布日期",planning:"準備把靈感變成旅行？",planningHelp:"帶著剛發現的地方，開始安排自己的行程。",plan:"開始規劃",
  sourceKinds:{editorial:"編輯內容",official:"官方來源",community:"旅人分享"},kinds:{hotspot:"景點",food:"美食",merchant:"特色店家",hotel:"飯店",article:"攻略",video:"影片",post:"旅人故事",itinerary:"公開行程"},video:"YouTube 影片",loadVideo:"載入影片",videoPrivacy:"按下後才會連線至 YouTube，不會自動播放。",videoFallback:"這部影片可前往原始來源觀看。",videoUrl:"YouTube 連結（每行一個，最多 5 個）",videoHelp:"貼上 YouTube、Shorts 或 youtu.be 連結；只保存影片參照，不下載影片。",invalidVideo:"請輸入最多 5 個有效且不重複的 YouTube 連結。",invitations:"創作者邀請",userId:"使用者 ID",lookup:"查詢",invited:"已邀請的創作者",inviteHelp:"邀請只授予發文資格，不會取得管理權限或跳過內容審核。",inviteOnly:"目前發文需要創作者邀請；你仍可保存草稿。",reasonLabel:"原因",update:"更新邀請",saved:"已儲存",private:"只有你能看見這份收藏",collectionGuide:"閱讀攻略",collectionHotel:"查看飯店",
};
const zhCN: DiscoveryCopy = { ...zhTW, explore:"探索",collections:"收藏",trips:"我的旅行",my:"我的",publish:"分享旅程",notifications:"通知",eyebrow:"从一点好奇，开始下一趟旅行。",title:"找到值得出发的地方。",subtitle:"有来源的景点、美食与旅行故事，让灵感慢慢变成你的行程。",search:"搜索",placeholder:"城市、景点，或你喜欢的旅行方式",searchLabel:"搜索旅行灵感",suggestions:"关键词建议",matched:"搜索结果",all:"全部",destination:"目的地",topic:"主题",language:"内容语言",any:"不限",clear:"清除筛选",recommended:"为你推荐",latest:"最新",following:"关注中",feed:"下一站，从这里发现",filters:"缩小探索范围",preferences:"我的兴趣",preferenceHelp:"推荐仅使用你明确选择的兴趣、收藏与关注作者，不使用浏览记录。",savedSignal:"参考我的收藏",followingSignal:"参考关注的作者",save:"保存兴趣",reset:"重置兴趣与隐藏内容",cancel:"取消",dismiss:"不感兴趣",dismissed:"已从你的推荐隐藏",undo:"撤销",reason:"推荐原因",defaultReason:"来自当前可阅读的公开内容",login:"登录后继续",loginFollowing:"登录以阅读关注作者的内容",unavailable:"探索目前暂时无法使用。",empty:"还没有符合的内容，试试其他地方或减少筛选条件。",loading:"正在寻找旅行灵感…",more:"加载更多",retry:"重试",details:"阅读详情",source:"查看原始来源",originalLanguage:"原文语言",undated:"来源未提供发布日期",planning:"准备把灵感变成旅行？",planningHelp:"带着刚发现的地方，开始安排自己的行程。",plan:"开始规划",sourceKinds:{editorial:"编辑内容",official:"官方来源",community:"旅行分享"},kinds:{hotspot:"景点",food:"美食",merchant:"特色店铺",hotel:"酒店",article:"攻略",video:"视频",post:"旅行故事",itinerary:"公开行程"},video:"YouTube 视频",loadVideo:"加载视频",videoPrivacy:"点击后才会连接 YouTube，不会自动播放。",videoFallback:"此视频可前往原始来源观看。",videoUrl:"YouTube 链接（每行一个，最多 5 个）",videoHelp:"粘贴 YouTube、Shorts 或 youtu.be 链接；只保存引用，不下载视频。",invalidVideo:"请输入最多 5 个有效且不重复的 YouTube 链接。",invitations:"创作者邀请",userId:"用户 ID",lookup:"查询",invited:"已邀请的创作者",inviteHelp:"邀请仅授予发文资格，不会取得管理权限或跳过内容审核。",inviteOnly:"目前发文需要创作者邀请；仍可保存草稿。",reasonLabel:"原因",update:"更新邀请",saved:"已保存",private:"只有你能看见这份收藏",collectionGuide:"阅读攻略",collectionHotel:"查看酒店" };
const ja: DiscoveryCopy = { explore:"見つける",collections:"コレクション",trips:"マイトリップ",my:"アカウント",publish:"旅を投稿",notifications:"通知",eyebrow:"小さな好奇心から、次の旅へ。",title:"出かけたくなる場所を見つけよう。",subtitle:"出典のあるスポット、グルメ、旅の物語を、あなたの旅程に。",search:"検索",placeholder:"都市、スポット、好きな旅のスタイル",searchLabel:"旅のアイデアを検索",suggestions:"キーワード候補",matched:"検索結果",all:"すべて",destination:"目的地",topic:"テーマ",language:"コンテンツの言語",any:"指定なし",clear:"絞り込みを解除",recommended:"おすすめ",latest:"新着",following:"フォロー中",feed:"次の行き先を見つける",filters:"条件で絞り込む",preferences:"興味・関心",preferenceHelp:"自分で選んだ興味、保存した項目、フォロー中の投稿者のみを参考にします。閲覧履歴は使いません。",savedSignal:"保存した項目を参考にする",followingSignal:"フォロー中の投稿者を参考にする",save:"興味を保存",reset:"興味と非表示項目をリセット",cancel:"キャンセル",dismiss:"興味がない",dismissed:"おすすめから非表示にしました",undo:"元に戻す",reason:"おすすめの理由",defaultReason:"現在公開されているコンテンツから",login:"ログインして続ける",loginFollowing:"フォロー中の投稿を見るにはログイン",unavailable:"現在、探索を利用できません。",empty:"一致する内容がありません。目的地や条件を変えてみてください。",loading:"旅のアイデアを探しています…",more:"もっと見る",retry:"再試行",details:"詳しく読む",source:"元の情報を見る",originalLanguage:"原文の言語",undated:"公開日の情報なし",planning:"アイデアを旅にしませんか？",planningHelp:"見つけた場所をもとに、自分だけの旅程を。",plan:"旅を計画",sourceKinds:{editorial:"編集記事",official:"公式情報",community:"旅行者の投稿"},kinds:{hotspot:"スポット",food:"グルメ",merchant:"お店",hotel:"ホテル",article:"ガイド",video:"動画",post:"旅の物語",itinerary:"公開旅程"},video:"YouTube 動画",loadVideo:"動画を読み込む",videoPrivacy:"選択した時だけ YouTube に接続します。自動再生はしません。",videoFallback:"元のサイトで動画をご覧いただけます。",videoUrl:"YouTube リンク（1 行 1 件、最大 5 件）",videoHelp:"YouTube、Shorts、youtu.be の URL に対応。動画はダウンロードせず参照だけ保存します。",invalidVideo:"有効で重複しない YouTube リンクを 5 件以内で入力してください。",invitations:"投稿者の招待",userId:"ユーザー ID",lookup:"検索",invited:"招待済みの投稿者",inviteHelp:"招待は投稿資格のみを付与します。管理権限や審査免除ではありません。",inviteOnly:"公開には投稿者の招待が必要です。下書きは保存できます。",reasonLabel:"理由",update:"招待を更新",saved:"保存しました",private:"このコレクションは自分だけに表示されます",collectionGuide:"ガイドを読む",collectionHotel:"ホテルを見る" };
const ko: DiscoveryCopy = { explore:"둘러보기",collections:"컬렉션",trips:"내 여행",my:"내 계정",publish:"여행 공유",notifications:"알림",eyebrow:"작은 호기심에서 다음 여행으로.",title:"떠나고 싶은 곳을 찾아보세요.",subtitle:"출처가 있는 명소, 음식, 여행 이야기를 나만의 일정으로 이어보세요.",search:"검색",placeholder:"도시, 장소 또는 좋아하는 여행 방식",searchLabel:"여행 아이디어 검색",suggestions:"추천 검색어",matched:"검색 결과",all:"전체",destination:"여행지",topic:"주제",language:"콘텐츠 언어",any:"전체",clear:"필터 초기화",recommended:"추천",latest:"최신",following:"팔로잉",feed:"다음 여행지를 발견하세요",filters:"검색 범위 좁히기",preferences:"내 관심사",preferenceHelp:"직접 선택한 관심사, 저장 항목, 팔로우한 작성자만 참고합니다. 방문 기록은 사용하지 않습니다.",savedSignal:"저장 항목 참고",followingSignal:"팔로우한 작성자 참고",save:"관심사 저장",reset:"관심사 및 숨긴 항목 초기화",cancel:"취소",dismiss:"관심 없음",dismissed:"추천에서 숨겼습니다",undo:"실행 취소",reason:"추천 이유",defaultReason:"현재 공개된 콘텐츠에서 선정",login:"로그인하고 계속",loginFollowing:"팔로우한 작성자의 글을 보려면 로그인하세요",unavailable:"지금은 둘러보기를 이용할 수 없습니다.",empty:"일치하는 콘텐츠가 없습니다. 여행지나 필터를 바꿔보세요.",loading:"여행 아이디어를 찾는 중…",more:"더 보기",retry:"다시 시도",details:"자세히 보기",source:"원본 출처 보기",originalLanguage:"원문 언어",undated:"게시일 정보 없음",planning:"아이디어를 여행으로 바꿔볼까요?",planningHelp:"발견한 장소로 나만의 일정을 시작하세요.",plan:"여행 계획",sourceKinds:{editorial:"편집 콘텐츠",official:"공식 출처",community:"여행자 이야기"},kinds:{hotspot:"명소",food:"음식",merchant:"가게",hotel:"호텔",article:"가이드",video:"동영상",post:"여행 이야기",itinerary:"공개 일정"},video:"YouTube 동영상",loadVideo:"동영상 불러오기",videoPrivacy:"선택해야 YouTube에 연결됩니다. 자동 재생하지 않습니다.",videoFallback:"원본 사이트에서 동영상을 볼 수 있습니다.",videoUrl:"YouTube 링크 (한 줄에 하나, 최대 5개)",videoHelp:"YouTube, Shorts, youtu.be URL을 붙여넣으세요. 동영상은 다운로드하지 않고 참조만 저장합니다.",invalidVideo:"중복되지 않는 유효한 YouTube 링크를 최대 5개 입력하세요.",invitations:"작성자 초대",userId:"사용자 ID",lookup:"조회",invited:"초대된 작성자",inviteHelp:"초대는 게시 자격만 부여합니다. 관리자 권한이나 검토 면제가 아닙니다.",inviteOnly:"현재 게시하려면 작성자 초대가 필요합니다. 초안은 저장할 수 있습니다.",reasonLabel:"사유",update:"초대 업데이트",saved:"저장됨",private:"나만 볼 수 있는 컬렉션입니다",collectionGuide:"가이드 읽기",collectionHotel:"호텔 보기" };
export function getDiscoveryCopy(locale: string): DiscoveryCopy { return ({ "zh-TW": zhTW, "zh-CN": zhCN, en, ja, ko } as Record<string, DiscoveryCopy>)[locale] || en; }
export function getRecommendationReason(locale: string, reason: string) {
  const values: Record<string, string[]> = {
    en: ["Matches a destination you chose", "Matches a topic you chose", "Related to your saved items", "From a creator you follow", "Recently published"],
    "zh-TW": ["符合你選擇的目的地", "符合你選擇的主題", "與你的收藏相關", "來自你追蹤的作者", "最近發布的內容"],
    "zh-CN": ["符合你选择的目的地", "符合你选择的主题", "与你的收藏相关", "来自你关注的作者", "最近发布的内容"],
    ja: ["選んだ目的地と一致", "選んだテーマと一致", "保存した項目に関連", "フォロー中の投稿者から", "最近公開された内容"],
    ko: ["선택한 여행지와 일치", "선택한 주제와 일치", "저장한 항목과 관련", "팔로우한 작성자의 콘텐츠", "최근 게시된 콘텐츠"],
  };
  const index = ["destination_interest", "topic_interest", "saved_interest", "following", "latest"].indexOf(reason);
  return index < 0 ? getDiscoveryCopy(locale).defaultReason : (values[locale] || values.en)[index];
}
export function getDiscoveryFeedback(locale: string) {
  const values: Record<string, { updated: string; type: string; conflict: string; reload: string; discard: string }> = {
    en: { updated: "Source updated", type: "Content type", conflict: "Your interests changed in another session. Reload the latest version before saving.", reload: "Reload latest version", discard: "Discard these unsaved changes and reload your interests?" },
    "zh-TW": { updated: "來源更新時間", type: "內容類型", conflict: "興趣已在其他工作階段更新，請重新載入最新版本後再儲存。", reload: "載入最新版本", discard: "放棄這些未儲存修改，重新載入你的興趣？" },
    "zh-CN": { updated: "来源更新时间", type: "内容类型", conflict: "兴趣已在其他会话中更新，请重新加载最新版本后保存。", reload: "加载最新版本", discard: "放弃这些未保存的修改，重新加载兴趣？" },
    ja: { updated: "情報の更新日時", type: "コンテンツの種類", conflict: "別のセッションで興味が更新されました。最新版を読み込んでから保存してください。", reload: "最新版を読み込む", discard: "未保存の変更を破棄して興味を読み込み直しますか？" },
    ko: { updated: "출처 업데이트", type: "콘텐츠 유형", conflict: "다른 세션에서 관심사가 변경되었습니다. 최신 버전을 불러온 후 저장하세요.", reload: "최신 버전 불러오기", discard: "저장하지 않은 변경을 버리고 관심사를 다시 불러올까요?" },
  };
  return values[locale] || values.en;
}
