// Feature-local copy keeps this editor work independent of the catalogue team's
// active translation batch. Every key is required in all five supported locales.
const en = {
  addHere: "Add a stop here", addTitle: "Where would you like to go?",
  discover: "Discover", favorites: "Saved", nearby: "Nearby",
  search: "Search places", manual: "Add a custom stop",
  searchHint: "Search by place, neighborhood or restaurant",
  context: "Day {day} · {before} → {after}", start: "Start of day", end: "End of day",
  selected: "Added", add: "Add", close: "Done", undo: "Undo",
  savedSection: "Your saved places", nearbySection: "Around this stop", citySection: "In your destination",
  nearbyHint: "Based on straight-line distance. Travel times update when you check routes.",
  cityHint: "Choose a hotel or place to see recommendations nearby.",
  emptySaved: "No saved places with verified locations match here. Try nearby recommendations or search.",
  emptyNearby: "No matching places in this area.", emptySearch: "No matching places.",
  expand: "Expand to 10 km", allCities: "Include saved places in other cities",
  loading: "Finding places…", retry: "Try again", unavailable: "Places could not be loaded.",
  offline: "You're offline. You can still add a custom stop and save it as a draft.",
  all: "All", attractions: "Sights", food: "Food & cafés",
  distance: "{distance} km away", duration: "{minutes} min", saved: "Saved",
  move: "Move", moveTitle: "Move this stop", moveDay: "Day", movePosition: "Position",
  moveHere: "Move here", moved: "Stop moved", moveHint: "Drag the handle, or choose Move to pick a day and position.",
  moveHandle: "Move {title}", moving: "Moving {title}. Release at the highlighted gap.",
  fixedHint: "Fixed time stays the same. Arrival conflicts will be shown.",
  addedNotice: "{title} added", already: "Already planned", editDetails: "Edit details",
  chooseLocation: "Choose a precise location", restaurant: "Saved restaurant",
  showIssues: "View planning notes", browseMeals: "Choose from saved or nearby restaurants",
  replacement: "Choose restaurant", replaced: "Restaurant updated",
  previous: "Previous page", next: "Next page",
} as const;
export type ItineraryCopy = Record<keyof typeof en, string>;
const zhTW: ItineraryCopy = {
  addHere: "在這裡新增行程", addTitle: "下一站想去哪裡？",
  discover: "為你挑選", favorites: "我的收藏", nearby: "附近推薦",
  search: "搜尋地點", manual: "自行填寫行程",
  searchHint: "搜尋景點、商圈或餐廳",
  context: "第 {day} 天 · {before} → {after}", start: "當天開始", end: "當天結束",
  selected: "已加入", add: "加入", close: "完成", undo: "復原",
  savedSection: "你收藏的地點", nearbySection: "這一站附近", citySection: "目的地推薦",
  nearbyHint: "距離為直線估算，實際交通時間會在查路後更新。",
  cityHint: "設定飯店或景點後，就能依位置推薦附近地點。",
  emptySaved: "目前沒有符合條件且地點已確認的收藏。可以看看附近推薦，或直接搜尋地點。",
  emptyNearby: "附近暫時沒有符合的地點。", emptySearch: "沒有符合的地點。",
  expand: "擴大到 10 公里", allCities: "也顯示其他城市的收藏",
  loading: "正在找適合的地點…", retry: "重試", unavailable: "暫時無法載入地點。",
  offline: "目前離線，仍可自行填寫行程並保留草稿。",
  all: "全部", attractions: "景點", food: "美食與咖啡",
  distance: "距離約 {distance} 公里", duration: "停留 {minutes} 分鐘", saved: "已收藏",
  move: "移動", moveTitle: "移動這個行程", moveDay: "日期", movePosition: "插入位置",
  moveHere: "移到這裡", moved: "已移動行程", moveHint: "拖曳把手可調整順序，也可按「移動」選擇日期與位置。",
  moveHandle: "移動 {title}", moving: "正在移動 {title}，放開即可放到標示的位置。",
  fixedHint: "固定時間保持不變，無法準時抵達時會顯示提醒。",
  addedNotice: "已加入 {title}", already: "已在行程中", editDetails: "編輯詳情",
  chooseLocation: "先確認精準地點", restaurant: "已收藏餐廳",
  showIssues: "查看安排提醒", browseMeals: "從收藏或附近餐廳挑選",
  replacement: "選擇這家餐廳", replaced: "已更換餐廳",
  previous: "上一頁", next: "下一頁",
};
const zhCN: ItineraryCopy = {
  addHere: "在这里新增行程", addTitle: "下一站想去哪里？",
  discover: "为你挑选", favorites: "我的收藏", nearby: "附近推荐", search: "搜索地点", manual: "自行填写行程",
  searchHint: "搜索景点、商圈或餐厅", context: "第 {day} 天 · {before} → {after}", start: "当天开始", end: "当天结束",
  selected: "已加入", add: "加入", close: "完成", undo: "撤销", savedSection: "你收藏的地点", nearbySection: "这一站附近", citySection: "目的地推荐",
  nearbyHint: "距离为直线估算，实际交通时间会在查路后更新。", cityHint: "设置酒店或景点后，就能按位置推荐附近地点。",
  emptySaved: "目前没有符合条件且地点已确认的收藏。可以看看附近推荐，或直接搜索地点。", emptyNearby: "附近暂时没有符合的地点。", emptySearch: "没有符合的地点。",
  expand: "扩大到 10 公里", allCities: "也显示其他城市的收藏", loading: "正在寻找适合的地点…", retry: "重试", unavailable: "暂时无法加载地点。",
  offline: "目前离线，仍可自行填写行程并保留草稿。", all: "全部", attractions: "景点", food: "美食与咖啡",
  distance: "距离约 {distance} 公里", duration: "停留 {minutes} 分钟", saved: "已收藏", move: "移动", moveTitle: "移动这个行程",
  moveDay: "日期", movePosition: "插入位置", moveHere: "移到这里", moved: "已移动行程",
  moveHint: "拖动把手可调整顺序，也可按“移动”选择日期与位置。", moveHandle: "移动 {title}", moving: "正在移动 {title}，松开即可放到标示的位置。",
  fixedHint: "固定时间保持不变，无法准时抵达时会显示提醒。", addedNotice: "已加入 {title}", already: "已在行程中", editDetails: "编辑详情",
  chooseLocation: "先确认精准地点", restaurant: "已收藏餐厅", showIssues: "查看安排提醒", browseMeals: "从收藏或附近餐厅挑选",
  replacement: "选择这家餐厅", replaced: "已更换餐厅",
  previous: "上一页", next: "下一页",
};
const ja: ItineraryCopy = {
  addHere: "ここに予定を追加", addTitle: "次はどこに行きますか？",
  discover: "おすすめ", favorites: "お気に入り", nearby: "周辺", search: "場所を検索", manual: "予定を手入力",
  searchHint: "観光地・エリア・レストランを検索", context: "{day}日目 · {before} → {after}", start: "一日の始まり", end: "一日の終わり",
  selected: "追加済み", add: "追加", close: "完了", undo: "元に戻す", savedSection: "保存した場所", nearbySection: "この場所の周辺", citySection: "目的地のおすすめ",
  nearbyHint: "直線距離の目安です。移動時間はルート検索後に更新されます。", cityHint: "ホテルや訪問先を設定すると周辺のおすすめが表示されます。",
  emptySaved: "位置確認済みのお気に入りが条件に一致しません。周辺のおすすめや検索をお試しください。", emptyNearby: "周辺に該当する場所がありません。", emptySearch: "該当する場所がありません。",
  expand: "10 kmまで広げる", allCities: "他の都市のお気に入りも表示", loading: "場所を探しています…", retry: "再試行", unavailable: "場所を読み込めませんでした。",
  offline: "オフラインです。予定を手入力して下書きに保存できます。", all: "すべて", attractions: "観光", food: "グルメ・カフェ",
  distance: "約{distance} km", duration: "滞在{minutes}分", saved: "保存済み", move: "移動", moveTitle: "この予定を移動",
  moveDay: "日付", movePosition: "追加する位置", moveHere: "ここへ移動", moved: "予定を移動しました",
  moveHint: "ハンドルをドラッグするか、「移動」で日付と位置を選べます。", moveHandle: "{title}を移動", moving: "{title}を移動中。表示された位置で放してください。",
  fixedHint: "固定時刻は変わりません。間に合わない場合は通知されます。", addedNotice: "{title}を追加しました", already: "予定に追加済み", editDetails: "詳細を編集",
  chooseLocation: "正確な場所を確認", restaurant: "保存したレストラン", showIssues: "プランの注意事項", browseMeals: "お気に入り・周辺のお店から選ぶ",
  replacement: "このお店を選択", replaced: "レストランを更新しました",
  previous: "前のページ", next: "次のページ",
};
const ko: ItineraryCopy = {
  addHere: "여기에 일정 추가", addTitle: "다음은 어디로 갈까요?",
  discover: "추천", favorites: "저장 장소", nearby: "주변 추천", search: "장소 검색", manual: "일정 직접 입력",
  searchHint: "명소, 지역, 식당 검색", context: "{day}일차 · {before} → {after}", start: "하루 시작", end: "하루 마무리",
  selected: "추가됨", add: "추가", close: "완료", undo: "되돌리기", savedSection: "저장한 장소", nearbySection: "이 장소 주변", citySection: "여행지 추천",
  nearbyHint: "직선거리 기준입니다. 실제 이동 시간은 경로 검색 후 갱신됩니다.", cityHint: "호텔이나 방문 장소를 설정하면 주변 장소를 추천합니다.",
  emptySaved: "위치가 확인된 저장 장소 중 조건에 맞는 장소가 없습니다. 주변 추천이나 검색을 이용하세요.", emptyNearby: "주변에 조건에 맞는 장소가 없습니다.", emptySearch: "일치하는 장소가 없습니다.",
  expand: "10 km까지 확대", allCities: "다른 도시의 저장 장소도 표시", loading: "장소를 찾는 중…", retry: "다시 시도", unavailable: "장소를 불러올 수 없습니다.",
  offline: "오프라인입니다. 일정을 직접 입력하고 임시 저장할 수 있습니다.", all: "전체", attractions: "명소", food: "맛집·카페",
  distance: "약 {distance} km", duration: "{minutes}분 체류", saved: "저장됨", move: "이동", moveTitle: "이 일정 이동",
  moveDay: "날짜", movePosition: "삽입 위치", moveHere: "여기로 이동", moved: "일정이 이동되었습니다",
  moveHint: "핸들을 드래그하거나 '이동'에서 날짜와 위치를 선택하세요.", moveHandle: "{title} 이동", moving: "{title} 이동 중. 표시된 위치에서 놓으세요.",
  fixedHint: "고정 시간은 유지됩니다. 제시간에 도착하지 못하면 알림이 표시됩니다.", addedNotice: "{title} 추가됨", already: "일정에 있음", editDetails: "상세 편집",
  chooseLocation: "정확한 위치 확인", restaurant: "저장한 식당", showIssues: "일정 알림 보기", browseMeals: "저장한 식당이나 주변 식당에서 선택",
  replacement: "이 식당 선택", replaced: "식당이 변경되었습니다",
  previous: "이전 페이지", next: "다음 페이지",
};
export function itineraryCopy(locale: string): ItineraryCopy {
  return ({ en, ja, ko, "zh-TW": zhTW, "zh-CN": zhCN } as Record<string, ItineraryCopy>)[locale] || en;
}
export function itineraryText(text: string, values: Record<string, string | number>) {
  return text.replace(/\{(\w+)\}/g, (match, key: string) => String(values[key] ?? match));
}
