const en = {
  title: "Korea · dual map identities",
  hint: "Find Google candidates without publishing places or changing NAVER approval, names, coordinates or trip times. Every branch requires a separate human review.",
  independent:
    "NAVER and Google are reviewed independently. A saved ID is not a confirmed match.",
  kind: "Place type",
  hotspot: "Attraction",
  merchant: "Restaurant",
  hotel: "Hotel",
  city: "City ID",
  allCities: "All Korean cities",
  missing: "Google review status",
  all: "All",
  missingId: "No Google review",
  pending: "Needs review",
  confirmed: "Confirmed",
  filter: "Find places",
  select: "Select",
  selectAll: "Select this page",
  clear: "Clear selection",
  selected: "selected (maximum 50)",
  batch: "Find Google candidates",
  progress: "Candidate search",
  refresh: "Refresh",
  previous: "Previous",
  next: "Next",
  empty: "No matching Korean places.",
  review: "Review candidates",
  reviewing: "Loading current Google information…",
  canonical: "Canonical place (unchanged)",
  candidates: "Google candidates · temporary comparison only",
  none: "No candidates. Keep this place unconfirmed.",
  compare:
    "Compare the Korean name, exact branch and complete address. Distance alone does not confirm a match.",
  checked:
    "I checked the Korean name, branch and complete address against the canonical place.",
  note: "Review evidence and reason",
  confirm: "Confirm only this Google identity",
  reject: "Reject this candidate",
  success: "Review saved. Canonical location and publication are unchanged.",
  close: "Close review",
  unverified: "Unverified",
  notFound: "Not found",
  failed: "Failed",
  queued: "Queued",
  running: "Searching",
  completed: "Completed",
  partial: "Partially completed",
  rejected: "Rejected",
  unknown: "Not reviewed",
  unavailable: "Unavailable",
  error: "Unable to load map identities. Please retry.",
  position: "Position reference",
  expired: "Candidate information expired. Reload before reviewing.",
};
type Copy = typeof en;
const copies: Record<string, Copy> = {
  en,
  "zh-TW": {
    title: "韓國・雙地圖身分核對",
    hint: "尋找 Google 候選不會發布地點，也不會改動 NAVER 核准、名稱、座標或行程時間。每個分館仍需人工獨立核對。",
    independent: "NAVER 與 Google 分別核對；已填入 ID 不代表已確認為同一地點。",
    kind: "地點類型",
    hotspot: "景點",
    merchant: "餐廳",
    hotel: "飯店",
    city: "城市代碼",
    allCities: "所有韓國城市",
    missing: "Google 核對狀態",
    all: "全部",
    missingId: "尚無 Google 核對",
    pending: "待核對",
    confirmed: "已確認",
    filter: "尋找地點",
    select: "選取",
    selectAll: "選取本頁",
    clear: "清除選取",
    selected: "筆已選取（最多 50 筆）",
    batch: "尋找 Google 候選",
    progress: "候選搜尋進度",
    refresh: "重新整理",
    previous: "上一頁",
    next: "下一頁",
    empty: "沒有符合條件的韓國地點。",
    review: "核對候選",
    reviewing: "正在取得最新 Google 資訊…",
    canonical: "主地點資料（不變更）",
    candidates: "Google 候選・僅供暫時比對",
    none: "沒有候選，保持尚未核對。",
    compare:
      "請比對韓文名稱、確切分館與完整地址；距離相近不能單獨作為同店依據。",
    checked: "我已比對主資料的韓文名稱、分館與完整地址，確認為同一地點。",
    note: "核對依據與原因",
    confirm: "僅確認此 Google 身分",
    reject: "拒絕此候選",
    success: "已保存核對結果，主地點及發布狀態沒有變更。",
    close: "關閉核對",
    unverified: "尚未核對",
    notFound: "找不到",
    failed: "失敗",
    queued: "排隊中",
    running: "搜尋中",
    completed: "搜尋完成",
    partial: "部分完成",
    rejected: "已拒絕",
    unknown: "尚未核對",
    unavailable: "目前無法使用",
    error: "無法載入地圖身分，請重試。",
    position: "位置參考",
    expired: "候選資訊已過期，請重新載入後核對。",
  },
  "zh-CN": {
    title: "韩国・双地图身份核对",
    hint: "查找 Google 候选不会发布地点，也不会改动 NAVER 审核、名称、坐标或行程时间。每个分店仍需人工独立核对。",
    independent: "NAVER 与 Google 分别核对；已填写 ID 不代表已确认为同一地点。",
    kind: "地点类型",
    hotspot: "景点",
    merchant: "餐厅",
    hotel: "酒店",
    city: "城市代码",
    allCities: "所有韩国城市",
    missing: "Google 核对状态",
    all: "全部",
    missingId: "尚无 Google 核对",
    pending: "待核对",
    confirmed: "已确认",
    filter: "查找地点",
    select: "选择",
    selectAll: "选择本页",
    clear: "清除选择",
    selected: "项已选择（最多 50 项）",
    batch: "查找 Google 候选",
    progress: "候选搜索进度",
    refresh: "刷新",
    previous: "上一页",
    next: "下一页",
    empty: "没有符合条件的韩国地点。",
    review: "核对候选",
    reviewing: "正在获取最新 Google 信息…",
    canonical: "主地点资料（不变更）",
    candidates: "Google 候选・仅供临时比对",
    none: "没有候选，保持尚未核对。",
    compare:
      "请比对韩文名称、具体分店与完整地址；距离相近不能单独作为同店依据。",
    checked: "我已比对主资料的韩文名称、分店与完整地址，确认为同一地点。",
    note: "核对依据与原因",
    confirm: "仅确认此 Google 身份",
    reject: "拒绝此候选",
    success: "已保存核对结果，主地点及发布状态没有变更。",
    close: "关闭核对",
    unverified: "尚未核对",
    notFound: "找不到",
    failed: "失败",
    queued: "排队中",
    running: "搜索中",
    completed: "搜索完成",
    partial: "部分完成",
    rejected: "已拒绝",
    unknown: "尚未核对",
    unavailable: "目前无法使用",
    error: "无法加载地图身份，请重试。",
    position: "位置参考",
    expired: "候选信息已过期，请重新加载后核对。",
  },
  ja: {
    title: "韓国・2つの地図の場所確認",
    hint: "Google 候補の検索では公開状態、NAVER の承認、名称、座標、旅程時刻を変更しません。支店ごとに人による確認が必要です。",
    independent:
      "NAVER と Google は個別に確認します。ID の保存だけでは同一店舗と認められません。",
    kind: "場所の種類",
    hotspot: "観光地",
    merchant: "飲食店",
    hotel: "ホテル",
    city: "都市コード",
    allCities: "韓国の全都市",
    missing: "Google 確認状況",
    all: "すべて",
    missingId: "Google 確認なし",
    pending: "要確認",
    confirmed: "確認済み",
    filter: "場所を検索",
    select: "選択",
    selectAll: "このページを選択",
    clear: "選択解除",
    selected: "件選択（最大 50 件）",
    batch: "Google 候補を検索",
    progress: "候補検索の進捗",
    refresh: "再読み込み",
    previous: "前へ",
    next: "次へ",
    empty: "条件に合う韓国の場所はありません。",
    review: "候補を確認",
    reviewing: "最新の Google 情報を取得中…",
    canonical: "元の場所情報（変更なし）",
    candidates: "Google 候補・一時的な比較用",
    none: "候補なし。未確認のまま保持します。",
    compare:
      "韓国語名、支店、住所全体を照合してください。距離だけでは同じ店舗と判断できません。",
    checked:
      "元データの韓国語名、支店、住所全体を照合し、同じ場所であることを確認しました。",
    note: "確認の根拠と理由",
    confirm: "この Google ID のみ確認",
    reject: "この候補を却下",
    success: "確認結果を保存しました。元の場所と公開状態は変更していません。",
    close: "確認を閉じる",
    unverified: "未確認",
    notFound: "見つかりません",
    failed: "失敗",
    queued: "待機中",
    running: "検索中",
    completed: "完了",
    partial: "一部完了",
    rejected: "却下済み",
    unknown: "未確認",
    unavailable: "利用できません",
    error: "地図情報を読み込めません。再試行してください。",
    position: "位置の参考",
    expired: "候補の有効期限が切れました。再読み込みしてください。",
  },
  ko: {
    title: "한국 · 두 지도 장소 확인",
    hint: "Google 후보 검색은 게시 상태, NAVER 승인, 이름, 좌표 또는 일정 시간을 변경하지 않습니다. 각 지점은 별도로 직접 확인해야 합니다.",
    independent:
      "NAVER와 Google은 각각 확인합니다. ID 저장만으로 동일 장소가 확인되지는 않습니다.",
    kind: "장소 유형",
    hotspot: "관광지",
    merchant: "음식점",
    hotel: "호텔",
    city: "도시 코드",
    allCities: "모든 한국 도시",
    missing: "Google 확인 상태",
    all: "전체",
    missingId: "Google 확인 없음",
    pending: "확인 필요",
    confirmed: "확인됨",
    filter: "장소 찾기",
    select: "선택",
    selectAll: "현재 페이지 선택",
    clear: "선택 해제",
    selected: "개 선택 (최대 50개)",
    batch: "Google 후보 찾기",
    progress: "후보 검색 진행",
    refresh: "새로고침",
    previous: "이전",
    next: "다음",
    empty: "조건에 맞는 한국 장소가 없습니다.",
    review: "후보 확인",
    reviewing: "최신 Google 정보를 가져오는 중…",
    canonical: "기준 장소 정보 (변경 없음)",
    candidates: "Google 후보 · 임시 비교 전용",
    none: "후보가 없습니다. 미확인 상태를 유지합니다.",
    compare:
      "한국어 이름, 정확한 지점, 전체 주소를 비교하세요. 가까운 거리만으로 같은 업체로 판단하지 마세요.",
    checked:
      "기준 정보의 한국어 이름, 지점, 전체 주소를 비교하여 동일한 장소임을 확인했습니다.",
    note: "확인 근거와 이유",
    confirm: "이 Google 식별 정보만 확인",
    reject: "이 후보 거부",
    success:
      "확인 결과를 저장했습니다. 기준 장소와 게시 상태는 변경하지 않았습니다.",
    close: "확인 닫기",
    unverified: "미확인",
    notFound: "찾을 수 없음",
    failed: "실패",
    queued: "대기 중",
    running: "검색 중",
    completed: "완료",
    partial: "일부 완료",
    rejected: "거부됨",
    unknown: "미확인",
    unavailable: "사용할 수 없음",
    error: "지도 정보를 불러올 수 없습니다. 다시 시도하세요.",
    position: "위치 참고",
    expired: "후보 정보가 만료되었습니다. 다시 불러온 후 확인하세요.",
  },
};
export function mapIdentityCopy(locale: string): Copy {
  return copies[locale] ?? en;
}
export function mapIdentityStatus(
  status: string | undefined,
  copy: Copy,
): string {
  const keys: Record<string, keyof Copy> = {
    confirmed: "confirmed",
    approved: "confirmed",
    verified: "confirmed",
    pending: "pending",
    unverified: "unverified",
    candidate: "pending",
    rejected: "rejected",
    not_found: "notFound",
    unmatched: "notFound",
    failed: "failed",
    queued: "queued",
    running: "running",
    started: "running",
    completed: "completed",
    complete: "completed",
    partial: "partial",
    unavailable: "unavailable",
  };
  return copy[keys[status ?? ""] ?? "unknown"];
}
