const en = {
  assistant: "AI assistant", arrange: "Plan places", adjust: "Adjust my itinerary", optimize: "Improve the route",
  assistantHint: "Explore an idea first. Your itinerary changes only when you apply it.",
  preparation: "Travel essentials", preparationHint: "Stays, flights, weather and useful extras",
  settings: "Trip settings", settingsHint: "Travelers, preferences and daily rhythm",
  sharing: "Share & export", sharingHint: "A read-only link, calendar or printable itinerary",
  overview: "Your trip, your pace", more: "More options", back: "Back", weather: "Weather",
  preferences: "Travelers & preferences", preferencesHint: "These settings guide future searches and AI previews. They do not rearrange your trip.",
  savePreferences: "Save preferences", preferencesSaved: "Preferences saved. Your itinerary is unchanged.",
  invalidPreferences: "Check the traveler counts and preferences before saving.",
  emptyTitle: "A little space for adventure", emptyHint: "Add a place you love, or let AI suggest a first draft.",
  issues: "Planning notes", start: "Add your first place", add: "Add a place", dayOptions: "Day settings",
  itemOptions: "Options for {title}", statusHint: "Applied itinerary status", previewHint: "Preview only · nothing changed yet",
  optionalStop: "Not arranged yet", free: "Free", charge: "Applied plan: {charge}", pending: "Review location",
};
type Copy = typeof en;
const translations: Record<string, Copy> = {
  en,
  "zh-TW": {
    assistant: "AI 助手", arrange: "安排景點", adjust: "調整現有行程", optimize: "順一下動線",
    assistantHint: "先看看建議，按下套用才會修改你的行程。",
    preparation: "旅行準備", preparationHint: "住宿、航班、天氣與實用服務",
    settings: "旅程設定", settingsHint: "旅伴、旅行偏好與每天的節奏",
    sharing: "分享與匯出", sharingHint: "唯讀連結、行事曆與列印行程",
    overview: "你的旅行，照你的步調", more: "更多操作", back: "返回", weather: "天氣",
    preferences: "旅伴與旅行偏好", preferencesHint: "設定用於之後的搜尋與 AI 預覽，不會直接重排現有行程。",
    savePreferences: "儲存偏好", preferencesSaved: "偏好已儲存，原有行程保持不變。",
    invalidPreferences: "請確認旅伴人數與偏好欄位。",
    emptyTitle: "為這一天留一點期待", emptyHint: "加入想去的地方，或讓 AI 提供第一版建議。",
    issues: "安排提醒", start: "加入第一個地點", add: "新增安排", dayOptions: "當日設定",
    itemOptions: "{title} 的更多操作", statusHint: "已套用的行程狀態", previewHint: "預覽中・尚未修改行程",
    optionalStop: "尚未安排", free: "免費", charge: "套用行程：{charge}", pending: "確認地點",
  },
  "zh-CN": {
    assistant: "AI 助手", arrange: "安排景点", adjust: "调整现有行程", optimize: "优化路线",
    assistantHint: "先查看建议，点击应用才会修改你的行程。",
    preparation: "旅行准备", preparationHint: "住宿、航班、天气与实用服务",
    settings: "行程设置", settingsHint: "旅伴、旅行偏好与每天的节奏",
    sharing: "分享与导出", sharingHint: "只读链接、日历与打印行程",
    overview: "你的旅行，按你的节奏", more: "更多操作", back: "返回", weather: "天气",
    preferences: "旅伴与旅行偏好", preferencesHint: "设置用于之后的搜索与 AI 预览，不会直接重排现有行程。",
    savePreferences: "保存偏好", preferencesSaved: "偏好已保存，原有行程保持不变。",
    invalidPreferences: "请确认旅伴人数与偏好字段。",
    emptyTitle: "为这一天留一点期待", emptyHint: "加入想去的地方，或让 AI 提供第一版建议。",
    issues: "安排提醒", start: "加入第一个地点", add: "新增安排", dayOptions: "当日设置",
    itemOptions: "{title} 的更多操作", statusHint: "已应用的行程状态", previewHint: "预览中・尚未修改行程",
    optionalStop: "尚未安排", free: "免费", charge: "应用行程：{charge}", pending: "确认地点",
  },
  ja: {
    assistant: "AIアシスタント", arrange: "訪問先を提案", adjust: "現在の旅程を調整", optimize: "移動を最適化",
    assistantHint: "まず提案を確認。適用するまで旅程は変わりません。",
    preparation: "旅の準備", preparationHint: "宿泊・航空便・天気・便利なサービス",
    settings: "旅行の設定", settingsHint: "同行者・好み・一日のペース",
    sharing: "共有・書き出し", sharingHint: "閲覧専用リンク・カレンダー・印刷",
    overview: "あなたの旅を、あなたのペースで", more: "その他の操作", back: "戻る", weather: "天気",
    preferences: "同行者と旅行の好み", preferencesHint: "今後の検索とAIの提案に使用します。現在の旅程は並べ替えません。",
    savePreferences: "設定を保存", preferencesSaved: "設定を保存しました。旅程は変更していません。",
    invalidPreferences: "人数と設定内容を確認してください。",
    emptyTitle: "この日に、楽しみをひとつ", emptyHint: "行きたい場所を追加するか、AIに最初の提案を頼みましょう。",
    issues: "確認事項", start: "最初の場所を追加", add: "予定を追加", dayOptions: "この日の設定",
    itemOptions: "{title} の操作", statusHint: "適用済み旅程の保存状態", previewHint: "プレビュー中・旅程は未変更",
    optionalStop: "未設定", free: "無料", charge: "旅程の適用：{charge}", pending: "場所を確認",
  },
  ko: {
    assistant: "AI 도우미", arrange: "방문 장소 추천", adjust: "기존 일정 조정", optimize: "동선 다듬기",
    assistantHint: "먼저 제안을 확인하세요. 적용해야 일정이 변경됩니다.",
    preparation: "여행 준비", preparationHint: "숙소, 항공편, 날씨와 유용한 서비스",
    settings: "여행 설정", settingsHint: "여행자, 취향과 하루의 속도",
    sharing: "공유 및 내보내기", sharingHint: "읽기 전용 링크, 캘린더, 일정 인쇄",
    overview: "나만의 여행, 나만의 속도", more: "더 보기", back: "뒤로", weather: "날씨",
    preferences: "여행자 및 여행 취향", preferencesHint: "이후 검색과 AI 미리보기에 사용됩니다. 기존 일정을 자동으로 바꾸지 않습니다.",
    savePreferences: "설정 저장", preferencesSaved: "설정을 저장했습니다. 기존 일정은 그대로입니다.",
    invalidPreferences: "여행자 수와 설정을 확인해 주세요.",
    emptyTitle: "이 하루에 설렘을 더해요", emptyHint: "가고 싶은 장소를 추가하거나 AI에게 첫 일정을 부탁하세요.",
    issues: "확인할 사항", start: "첫 장소 추가", add: "일정 추가", dayOptions: "하루 설정",
    itemOptions: "{title} 옵션", statusHint: "적용된 일정의 저장 상태", previewHint: "미리보기 · 아직 변경되지 않음",
    optionalStop: "아직 미정", free: "무료", charge: "일정 적용: {charge}", pending: "장소 확인",
  },
};
export function plannerCopy(locale: string): Copy { return translations[locale] || en; }
export const plannerLocales = Object.keys(translations);
