"""Sub-city areas (商圈) used to browse the merchant directory.

Every ``DestinationProfile.areas`` string has exactly one seed here; the validator
keeps the two lists in lock-step so a renamed profile area fails at import time
instead of silently orphaning merchants. Areas created later from the admin
panel live only in the database and are not covered by this catalog.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass

from app.destinations.catalog import DESTINATIONS, destination_for_id
from app.foods.category_catalog import SLUG_PATTERN, validate_names


@dataclass(frozen=True)
class AreaSeed:
    destination_id: str
    key: str
    names: Mapping[str, str]
    match_terms: tuple[str, ...] = ()
    center: tuple[float, float] | None = None
    display_order: int = 100

    @property
    def slug(self) -> str:
        return f"{self.destination_id}-{self.key}"

    @property
    def source_name(self) -> str:
        return self.names["zh-TW"]


def _a(
    destination_id: str,
    key: str,
    zh_tw: str,
    en: str,
    ja: str,
    ko: str,
    zh_cn: str | None = None,
    *,
    order: int,
    terms: tuple[str, ...] = (),
    center: tuple[float, float] | None = None,
) -> AreaSeed:
    return AreaSeed(
        destination_id=destination_id,
        key=key,
        names={"zh-TW": zh_tw, "zh-CN": zh_cn or zh_tw, "en": en, "ja": ja, "ko": ko},
        match_terms=terms,
        center=center,
        display_order=order,
    )


AREA_SEEDS: tuple[AreaSeed, ...] = (
    # Japan.
    _a(
        "tokyo",
        "shinjuku",
        "新宿",
        "Shinjuku",
        "新宿",
        "신주쿠",
        order=1,
        terms=("新宿", "Shinjuku"),
    ),
    _a(
        "tokyo",
        "ueno-asakusa",
        "上野／淺草",
        "Ueno / Asakusa",
        "上野・浅草",
        "우에노·아사쿠사",
        "上野／浅草",
        order=2,
        terms=("上野", "浅草", "Ueno", "Asakusa"),
    ),
    _a(
        "tokyo",
        "tokyo-station-ginza",
        "東京站／銀座",
        "Tokyo Station / Ginza",
        "東京駅・銀座",
        "도쿄역·긴자",
        "东京站／银座",
        order=3,
        terms=("東京駅", "銀座", "Ginza", "Marunouchi"),
    ),
    _a(
        "tokyo",
        "shibuya",
        "澀谷",
        "Shibuya",
        "渋谷",
        "시부야",
        "涩谷",
        order=4,
        terms=("渋谷", "Shibuya"),
    ),
    _a(
        "osaka-kyoto",
        "namba-shinsaibashi",
        "難波／心齋橋",
        "Namba / Shinsaibashi",
        "難波・心斎橋",
        "난바·신사이바시",
        "难波／心斋桥",
        order=1,
        terms=("難波", "ナンバ", "心斎橋", "道頓堀", "Namba", "Dotonbori"),
    ),
    _a("osaka-kyoto", "umeda", "梅田", "Umeda", "梅田", "우메다", order=2, terms=("梅田", "Umeda")),
    _a(
        "osaka-kyoto",
        "kyoto-station",
        "京都站",
        "Kyoto Station",
        "京都駅",
        "교토역",
        "京都站",
        order=3,
        terms=("京都駅", "Kyoto Station"),
    ),
    _a(
        "osaka-kyoto",
        "shijo-kawaramachi",
        "四條河原町",
        "Shijo Kawaramachi",
        "四条河原町",
        "시조 가와라마치",
        "四条河原町",
        order=4,
        terms=("河原町", "寺町", "祇園", "Kawaramachi", "Gion"),
    ),
    _a(
        "fukuoka",
        "hakata-station",
        "博多站",
        "Hakata Station",
        "博多駅",
        "하카타역",
        "博多站",
        order=1,
        terms=("博多", "Hakata"),
    ),
    _a("fukuoka", "tenjin", "天神", "Tenjin", "天神", "텐진", order=2, terms=("天神", "Tenjin")),
    _a("fukuoka", "nakasu", "中洲", "Nakasu", "中洲", "나카스", order=3, terms=("中洲", "Nakasu")),
    _a(
        "fukuoka",
        "ohori-park",
        "大濠公園",
        "Ohori Park",
        "大濠公園",
        "오호리 공원",
        "大濠公园",
        order=4,
        terms=("大濠", "Ohori"),
    ),
    _a(
        "sapporo",
        "sapporo-station",
        "札幌站",
        "Sapporo Station",
        "札幌駅",
        "삿포로역",
        "札幌站",
        order=1,
        terms=("札幌駅", "ステラプレイス", "Sapporo Station"),
    ),
    _a("sapporo", "odori", "大通", "Odori", "大通", "오도리", order=2, terms=("大通", "Odori")),
    _a(
        "sapporo",
        "susukino",
        "薄野",
        "Susukino",
        "すすきの",
        "스스키노",
        order=3,
        terms=("すすきの", "Susukino"),
    ),
    _a(
        "sapporo",
        "nakajima-park",
        "中島公園",
        "Nakajima Park",
        "中島公園",
        "나카지마 공원",
        "中岛公园",
        order=4,
        terms=("中島公園", "Nakajima"),
    ),
    _a(
        "okinawa",
        "kokusai-dori",
        "國際通",
        "Kokusai Dori",
        "国際通り",
        "고쿠사이도리",
        "国际通",
        order=1,
        terms=("国際通り", "Kokusai"),
    ),
    _a(
        "okinawa",
        "naha-shintoshin",
        "那霸新都心",
        "Naha Shintoshin",
        "那覇新都心",
        "나하 신도심",
        "那霸新都心",
        order=2,
        terms=("新都心", "おもろまち", "Omoromachi"),
    ),
    _a("okinawa", "chatan", "北谷", "Chatan", "北谷", "차탄", order=3, terms=("北谷", "Chatan")),
    _a("okinawa", "onna", "恩納", "Onna", "恩納", "온나", "恩纳", order=4, terms=("恩納", "Onna")),
    _a(
        "nagoya",
        "nagoya-station",
        "名古屋站",
        "Nagoya Station",
        "名古屋駅",
        "나고야역",
        "名古屋站",
        order=1,
        terms=("名古屋駅", "名駅", "Nagoya Station"),
    ),
    _a(
        "nagoya",
        "sakae",
        "榮",
        "Sakae",
        "栄",
        "사카에",
        "荣",
        order=2,
        terms=("栄", "矢場町", "Sakae"),
    ),
    _a(
        "nagoya",
        "fushimi",
        "伏見",
        "Fushimi",
        "伏見",
        "후시미",
        "伏见",
        order=3,
        terms=("伏見", "Fushimi"),
    ),
    _a(
        "nagoya",
        "kanayama",
        "金山",
        "Kanayama",
        "金山",
        "가나야마",
        order=4,
        terms=("金山", "Kanayama"),
    ),
    _a(
        "sendai",
        "sendai-station",
        "仙台站",
        "Sendai Station",
        "仙台駅",
        "센다이역",
        "仙台站",
        order=1,
        terms=("仙台駅", "Sendai Station"),
    ),
    _a(
        "sendai",
        "ichibancho",
        "一番町",
        "Ichibancho",
        "一番町",
        "이치반초",
        order=2,
        terms=("一番町",),
    ),
    _a(
        "sendai",
        "kokubuncho",
        "國分町",
        "Kokubuncho",
        "国分町",
        "고쿠분초",
        "国分町",
        order=3,
        terms=("国分町",),
    ),
    _a(
        "sendai",
        "aoba-dori",
        "青葉通",
        "Aoba-dori",
        "青葉通り",
        "아오바도리",
        "青叶通",
        order=4,
        terms=("青葉通",),
    ),
    _a(
        "kanazawa",
        "kanazawa-station",
        "金澤站",
        "Kanazawa Station",
        "金沢駅",
        "가나자와역",
        "金泽站",
        order=1,
        terms=("金沢駅", "Kanazawa Station"),
    ),
    _a(
        "kanazawa",
        "omicho",
        "近江町",
        "Omicho Market",
        "近江町",
        "오미초",
        order=2,
        terms=("近江町", "Omicho"),
    ),
    _a(
        "kanazawa",
        "korinbo",
        "香林坊",
        "Korinbo",
        "香林坊",
        "고린보",
        order=3,
        terms=("香林坊", "Korinbo"),
    ),
    _a(
        "kanazawa",
        "higashi-chaya",
        "東茶屋街",
        "Higashi Chaya",
        "ひがし茶屋街",
        "히가시차야가이",
        "东茶屋街",
        order=4,
        terms=("茶屋街", "Higashi Chaya"),
    ),
    _a(
        "hiroshima",
        "kamiyacho",
        "紙屋町",
        "Kamiyacho",
        "紙屋町",
        "가미야초",
        "纸屋町",
        order=1,
        terms=("紙屋町",),
    ),
    _a(
        "hiroshima",
        "hatchobori",
        "八丁堀",
        "Hatchobori",
        "八丁堀",
        "핫초보리",
        order=2,
        terms=("八丁堀",),
    ),
    _a(
        "hiroshima",
        "hiroshima-station",
        "廣島站",
        "Hiroshima Station",
        "広島駅",
        "히로시마역",
        "广岛站",
        order=3,
        terms=("広島駅", "Hiroshima Station"),
    ),
    _a(
        "hiroshima",
        "peace-park",
        "和平公園",
        "Peace Memorial Park",
        "平和記念公園",
        "평화기념공원",
        "和平公园",
        order=4,
        terms=("平和記念公園", "Peace Park"),
    ),
    _a(
        "yokohama",
        "minato-mirai",
        "港未來",
        "Minato Mirai",
        "みなとみらい",
        "미나토미라이",
        "港未来",
        order=1,
        terms=("みなとみらい", "Minato Mirai"),
    ),
    _a(
        "yokohama",
        "kannai-bashamichi",
        "關內／馬車道",
        "Kannai / Bashamichi",
        "関内・馬車道",
        "간나이·바샤미치",
        "关内／马车道",
        order=2,
        terms=("関内", "馬車道", "Kannai", "Bashamichi"),
    ),
    _a(
        "yokohama",
        "chinatown-motomachi",
        "中華街／元町",
        "Chinatown / Motomachi",
        "中華街・元町",
        "차이나타운·모토마치",
        "中华街／元町",
        order=3,
        terms=("中華街", "元町", "Chinatown", "Motomachi"),
    ),
    _a(
        "yokohama",
        "yokohama-station",
        "橫濱站",
        "Yokohama Station",
        "横浜駅",
        "요코하마역",
        "横滨站",
        order=4,
        terms=("横浜駅", "Yokohama Station"),
    ),
    _a(
        "kamakura",
        "kamakura-station-komachi",
        "鎌倉站／小町通",
        "Kamakura Station / Komachi-dori",
        "鎌倉駅・小町通り",
        "가마쿠라역·고마치도리",
        "镰仓站／小町通",
        order=1,
        terms=("鎌倉駅", "小町通り", "Kamakura Station", "Komachi"),
    ),
    _a(
        "kamakura",
        "hase",
        "長谷",
        "Hase",
        "長谷",
        "하세",
        "长谷",
        order=2,
        terms=("長谷", "Hase"),
    ),
    _a(
        "kamakura",
        "kita-kamakura",
        "北鎌倉",
        "Kita-Kamakura",
        "北鎌倉",
        "기타카마쿠라",
        "北镰仓",
        order=3,
        terms=("北鎌倉", "Kita-Kamakura"),
    ),
    _a(
        "kamakura",
        "yuigahama",
        "由比濱",
        "Yuigahama",
        "由比ヶ浜",
        "유이가하마",
        "由比滨",
        order=4,
        terms=("由比ヶ浜", "Yuigahama"),
    ),
    # South Korea.
    _a(
        "seoul",
        "myeongdong",
        "明洞",
        "Myeongdong",
        "明洞",
        "명동",
        order=1,
        terms=("명동", "남대문", "Myeongdong"),
    ),
    _a("seoul", "hongdae", "弘大", "Hongdae", "弘大", "홍대", order=2, terms=("홍대", "Hongdae")),
    _a(
        "seoul",
        "dongdaemun",
        "東大門",
        "Dongdaemun",
        "東大門",
        "동대문",
        "东大门",
        order=3,
        terms=("동대문",),
    ),
    _a(
        "seoul",
        "gangnam",
        "江南",
        "Gangnam",
        "江南",
        "강남",
        order=4,
        terms=("강남", "압구정", "Gangnam"),
    ),
    _a(
        "busan", "seomyeon", "西面", "Seomyeon", "西面", "서면", order=1, terms=("서면", "Seomyeon")
    ),
    _a(
        "busan",
        "nampo-dong",
        "南浦洞",
        "Nampo-dong",
        "南浦洞",
        "남포동",
        order=2,
        terms=("남포동", "BIFF", "국제시장", "Nampo"),
    ),
    _a(
        "busan",
        "haeundae",
        "海雲台",
        "Haeundae",
        "海雲台",
        "해운대",
        "海云台",
        order=3,
        terms=("해운대",),
    ),
    _a(
        "busan",
        "gwangalli",
        "廣安里",
        "Gwangalli",
        "広安里",
        "광안리",
        "广安里",
        order=4,
        terms=("광안리",),
    ),
    _a(
        "jeju",
        "jeju-city",
        "濟州市",
        "Jeju City",
        "済州市",
        "제주시",
        "济州市",
        order=1,
        terms=("제주시",),
    ),
    _a("jeju", "aewol", "涯月", "Aewol", "涯月", "애월", order=2, terms=("애월", "Aewol")),
    _a(
        "jeju",
        "jungmun",
        "中文觀光區",
        "Jungmun Resort",
        "中文観光団地",
        "중문관광단지",
        "中文观光区",
        order=3,
        terms=("중문", "Jungmun"),
    ),
    _a(
        "jeju",
        "seogwipo",
        "西歸浦",
        "Seogwipo",
        "西帰浦",
        "서귀포",
        "西归浦",
        order=4,
        terms=("서귀포",),
    ),
    _a(
        "daegu",
        "dongseongno",
        "東城路",
        "Dongseongno",
        "東城路",
        "동성로",
        "东城路",
        order=1,
        terms=("동성로",),
    ),
    _a(
        "daegu",
        "banwoldang",
        "半月堂",
        "Banwoldang",
        "半月堂",
        "반월당",
        order=2,
        terms=("반월당", "약전골목"),
    ),
    _a(
        "daegu",
        "suseong-lake",
        "壽城池",
        "Suseong Lake",
        "寿城池",
        "수성못",
        "寿城池",
        order=3,
        terms=("수성못",),
    ),
    _a(
        "daegu",
        "daegu-station",
        "大邱站",
        "Daegu Station",
        "大邱駅",
        "대구역",
        "大邱站",
        order=4,
        terms=("대구역",),
    ),
    _a(
        "gyeongju",
        "hwangnidan-gil",
        "皇理團路",
        "Hwangnidan-gil",
        "皇理団길",
        "황리단길",
        "皇理团路",
        order=1,
        terms=("황리단길", "교동"),
    ),
    _a(
        "gyeongju",
        "daereungwon",
        "大陵苑",
        "Daereungwon",
        "大陵苑",
        "대릉원",
        order=2,
        terms=("대릉원",),
    ),
    _a(
        "gyeongju",
        "bomun-lake",
        "普門湖",
        "Bomun Lake",
        "普門湖",
        "보문호",
        "普门湖",
        order=3,
        terms=("보문",),
    ),
    _a(
        "gyeongju",
        "bulguksa",
        "佛國寺",
        "Bulguksa",
        "仏国寺",
        "불국사",
        "佛国寺",
        order=4,
        terms=("불국사",),
    ),
    _a(
        "jeonju",
        "hanok-village",
        "韓屋村",
        "Hanok Village",
        "韓屋村",
        "한옥마을",
        "韩屋村",
        order=1,
        terms=("한옥마을", "교동", "전동"),
    ),
    _a(
        "jeonju",
        "nambu-market",
        "南部市場",
        "Nambu Market",
        "南部市場",
        "남부시장",
        "南部市场",
        order=2,
        terms=("남부시장",),
    ),
    _a(
        "jeonju",
        "gaekridan-gil",
        "客理團路",
        "Gaekridan-gil",
        "客理団길",
        "객리단길",
        "客理团路",
        order=3,
        terms=("객리단길",),
    ),
    _a(
        "jeonju",
        "wansan-park",
        "完山公園",
        "Wansan Park",
        "完山公園",
        "완산공원",
        "完山公园",
        order=4,
        terms=("완산",),
    ),
    # Thailand.
    _a(
        "bangkok",
        "siam",
        "暹羅",
        "Siam",
        "サイアム",
        "시암",
        "暹罗",
        order=1,
        terms=("Siam", "สยาม"),
    ),
    _a(
        "bangkok",
        "asok-sukhumvit",
        "Asok／素坤逸",
        "Asok / Sukhumvit",
        "アソーク・スクンビット",
        "아속·수쿰빗",
        order=2,
        terms=("Asok", "Sukhumvit", "สุขุมวิท"),
    ),
    _a("bangkok", "silom", "Silom", "Silom", "シーロム", "실롬", order=3, terms=("Silom", "สีลม")),
    _a(
        "bangkok",
        "riverside",
        "河濱",
        "Riverside",
        "リバーサイド",
        "리버사이드",
        "河滨",
        order=4,
        terms=("Riverside", "Charoen Krung"),
    ),
    _a(
        "chiang-mai",
        "old-city",
        "古城",
        "Old City",
        "旧市街",
        "올드시티",
        order=1,
        terms=("Old City", "เมืองเก่า"),
    ),
    _a(
        "chiang-mai",
        "nimman",
        "尼曼區",
        "Nimman",
        "ニマンヘミン",
        "님만해민",
        "尼曼区",
        order=2,
        terms=("Nimman", "นิมมาน"),
    ),
    _a(
        "chiang-mai",
        "ping-riverside",
        "湄平河畔",
        "Ping Riverside",
        "ピン川沿い",
        "핑강변",
        order=3,
        terms=("Ping River", "แม่น้ำปิง"),
    ),
    _a(
        "chiang-mai",
        "night-bazaar",
        "夜市周邊",
        "Night Bazaar",
        "ナイトバザール周辺",
        "나이트 바자 주변",
        "夜市周边",
        order=4,
        terms=("Night Bazaar", "ไนท์บาซาร์"),
    ),
    _a(
        "phuket",
        "old-town",
        "普吉老城",
        "Phuket Old Town",
        "プーケット旧市街",
        "푸켓 올드타운",
        order=1,
        terms=("Old Town", "เมืองเก่า"),
    ),
    _a(
        "phuket",
        "patong",
        "芭東",
        "Patong",
        "パトン",
        "빠통",
        "芭东",
        order=2,
        terms=("Patong", "ป่าตอง"),
    ),
    _a("phuket", "kata", "卡塔", "Kata", "カタ", "까따", order=3, terms=("Kata", "กะตะ")),
    _a("phuket", "karon", "卡隆", "Karon", "カロン", "까론", order=4, terms=("Karon", "กะรน")),
    _a(
        "krabi",
        "ao-nang",
        "奧南",
        "Ao Nang",
        "アオナン",
        "아오낭",
        "奥南",
        order=1,
        terms=("Ao Nang", "อ่าวนาง"),
    ),
    _a(
        "krabi",
        "krabi-town",
        "喀比鎮",
        "Krabi Town",
        "クラビタウン",
        "끄라비 타운",
        "喀比镇",
        order=2,
        terms=("Krabi Town",),
    ),
    _a(
        "krabi",
        "railay",
        "萊雷",
        "Railay",
        "ライレイ",
        "라일레이",
        "莱雷",
        order=3,
        terms=("Railay", "ไร่เลย์"),
    ),
    _a(
        "krabi",
        "klong-muang",
        "克隆芒",
        "Klong Muang",
        "クロンムアン",
        "끌롱무앙",
        order=4,
        terms=("Klong Muang",),
    ),
    _a(
        "chiang-rai",
        "clock-tower",
        "鐘樓",
        "Clock Tower",
        "時計塔",
        "시계탑",
        "钟楼",
        order=1,
        terms=("Clock Tower", "หอนาฬิกา"),
    ),
    _a(
        "chiang-rai",
        "night-bazaar",
        "夜市",
        "Night Bazaar",
        "ナイトバザール",
        "나이트 바자",
        order=2,
        terms=("Night Bazaar", "Jetyod"),
    ),
    _a(
        "chiang-rai",
        "riverside",
        "河畔",
        "Riverside",
        "川沿い",
        "강변",
        order=3,
        terms=("Riverside", "แม่น้ำกก"),
    ),
    _a(
        "chiang-rai",
        "old-town",
        "舊城",
        "Old Town",
        "旧市街",
        "구시가지",
        "旧城",
        order=4,
        terms=("Old Town",),
    ),
    # Taiwan.
    _a(
        "taipei",
        "taipei-main-station",
        "台北車站",
        "Taipei Main Station",
        "台北駅",
        "타이베이역",
        "台北车站",
        order=1,
        terms=("台北車站", "北車"),
    ),
    _a(
        "taipei",
        "ximending",
        "西門町",
        "Ximending",
        "西門町",
        "시먼딩",
        "西门町",
        order=2,
        terms=("西門",),
    ),
    _a(
        "taipei", "xinyi", "信義區", "Xinyi", "信義区", "신이구", "信义区", order=3, terms=("信義",)
    ),
    _a("taipei", "zhongshan", "中山", "Zhongshan", "中山", "중산", order=4, terms=("中山",)),
    _a(
        "taichung",
        "central-district",
        "中區",
        "Central District",
        "中区",
        "중구",
        "中区",
        order=1,
        terms=("中區",),
    ),
    _a(
        "taichung",
        "west-district",
        "西區",
        "West District",
        "西区",
        "서구",
        "西区",
        order=2,
        terms=("西區", "四維"),
    ),
    _a(
        "taichung",
        "calligraphy-greenway",
        "草悟道",
        "Calligraphy Greenway",
        "草悟道",
        "차오우다오",
        order=3,
        terms=("草悟道",),
    ),
    _a("taichung", "fengjia", "逢甲", "Fengjia", "逢甲", "펑자", order=4, terms=("逢甲",)),
    _a(
        "kaohsiung",
        "yancheng",
        "鹽埕",
        "Yancheng",
        "塩埕",
        "옌청",
        "盐埕",
        order=1,
        terms=("鹽埕",),
    ),
    _a("kaohsiung", "qianjin", "前金", "Qianjin", "前金", "첸진", order=2, terms=("前金",)),
    _a("kaohsiung", "zuoying", "左營", "Zuoying", "左営", "줘잉", "左营", order=3, terms=("左營",)),
    _a(
        "kaohsiung",
        "sanduo",
        "三多商圈",
        "Sanduo Shopping District",
        "三多商圏",
        "싼둬 상권",
        order=4,
        terms=("三多",),
    ),
    _a(
        "tainan",
        "west-central",
        "中西區",
        "West Central District",
        "中西区",
        "중서구",
        "中西区",
        order=1,
        terms=("中西區",),
    ),
    _a("tainan", "anping", "安平", "Anping", "安平", "안핑", order=2, terms=("安平",)),
    _a(
        "tainan",
        "confucius-temple",
        "孔廟",
        "Confucius Temple",
        "孔子廟",
        "공자묘",
        "孔庙",
        order=3,
        terms=("孔廟",),
    ),
    _a(
        "tainan",
        "haian-road",
        "海安路",
        "Haian Road",
        "海安路",
        "하이안로",
        order=4,
        terms=("海安路",),
    ),
    # Singapore and Hong Kong.
    _a(
        "singapore",
        "marina-bay",
        "濱海灣",
        "Marina Bay",
        "マリーナベイ",
        "마리나베이",
        "滨海湾",
        order=1,
        terms=("Marina Bay",),
    ),
    _a(
        "singapore",
        "orchard",
        "烏節路",
        "Orchard Road",
        "オーチャード",
        "오차드",
        "乌节路",
        order=2,
        terms=("Orchard",),
    ),
    _a(
        "singapore",
        "chinatown",
        "牛車水",
        "Chinatown",
        "チャイナタウン",
        "차이나타운",
        "牛车水",
        order=3,
        terms=("Chinatown", "Maxwell", "New Bridge", "Far East Square"),
    ),
    _a("singapore", "bugis", "武吉士", "Bugis", "ブギス", "부기스", order=4, terms=("Bugis",)),
    _a(
        "hong-kong",
        "central-sheung-wan",
        "中環／上環",
        "Central / Sheung Wan",
        "セントラル・上環",
        "센트럴·셩완",
        "中环／上环",
        order=1,
        terms=("中環", "上環", "Central", "Sheung Wan"),
    ),
    _a(
        "hong-kong",
        "tsim-sha-tsui",
        "尖沙咀",
        "Tsim Sha Tsui",
        "尖沙咀",
        "침사추이",
        order=2,
        terms=("尖沙咀",),
    ),
    _a(
        "hong-kong",
        "causeway-bay",
        "銅鑼灣",
        "Causeway Bay",
        "銅鑼湾",
        "코즈웨이베이",
        "铜锣湾",
        order=3,
        terms=("銅鑼灣",),
    ),
    _a(
        "hong-kong",
        "mong-kok",
        "旺角",
        "Mong Kok",
        "旺角",
        "몽콕",
        order=4,
        terms=("旺角", "太子", "Prince Edward"),
    ),
    # Vietnam.
    _a(
        "hanoi",
        "hoan-kiem-lake",
        "還劍湖",
        "Hoan Kiem Lake",
        "ホアンキエム湖",
        "호안끼엠 호수",
        "还剑湖",
        order=1,
        terms=("Hoàn Kiếm",),
    ),
    _a(
        "hanoi",
        "old-quarter",
        "老城區",
        "Old Quarter",
        "旧市街",
        "올드 쿼터",
        "老城区",
        order=2,
        terms=("Old Quarter", "Bát Đàn", "Hàng"),
    ),
    _a(
        "hanoi",
        "west-lake",
        "西湖",
        "West Lake",
        "西湖",
        "서호",
        order=3,
        terms=("Tây Hồ", "West Lake"),
    ),
    _a("hanoi", "ba-dinh", "巴亭", "Ba Dinh", "バーディン", "바딘", order=4, terms=("Ba Đình",)),
    _a(
        "ho-chi-minh-city",
        "district-1",
        "第一郡",
        "District 1",
        "1区",
        "1군",
        order=1,
        terms=("Quận 1", "District 1"),
    ),
    _a(
        "ho-chi-minh-city",
        "district-3",
        "第三郡",
        "District 3",
        "3区",
        "3군",
        order=2,
        terms=("Quận 3", "District 3"),
    ),
    _a(
        "ho-chi-minh-city",
        "ben-thanh",
        "濱城市場",
        "Ben Thanh Market",
        "ベンタイン市場",
        "벤탄 시장",
        "滨城市场",
        order=3,
        terms=("Bến Thành",),
    ),
    _a(
        "ho-chi-minh-city",
        "thao-dien",
        "草田",
        "Thao Dien",
        "タオディエン",
        "타오디엔",
        order=4,
        terms=("Thảo Điền",),
    ),
    _a(
        "da-nang",
        "my-khe-beach",
        "美溪海灘",
        "My Khe Beach",
        "ミーケービーチ",
        "미케 비치",
        "美溪海滩",
        order=1,
        terms=("Mỹ Khê",),
    ),
    _a(
        "da-nang",
        "han-river",
        "漢江",
        "Han River",
        "ハン川",
        "한강",
        "汉江",
        order=2,
        terms=("Sông Hàn", "Bạch Đằng"),
    ),
    _a(
        "da-nang",
        "son-tra",
        "山茶半島",
        "Son Tra Peninsula",
        "ソンチャー半島",
        "선짜 반도",
        "山茶半岛",
        order=3,
        terms=("Sơn Trà",),
    ),
    _a(
        "da-nang",
        "hoi-an-old-town",
        "會安古城",
        "Hoi An Old Town",
        "ホイアン旧市街",
        "호이안 구시가지",
        "会安古城",
        order=4,
        terms=("Hội An",),
    ),
    _a(
        "da-lat",
        "da-lat-market",
        "大叻市場",
        "Da Lat Market",
        "ダラット市場",
        "달랏 시장",
        "大叻市场",
        order=1,
        terms=("Chợ Đà Lạt",),
    ),
    _a(
        "da-lat",
        "xuan-huong-lake",
        "春香湖",
        "Xuan Huong Lake",
        "スアンフーン湖",
        "쑤언흐엉 호수",
        order=2,
        terms=("Xuân Hương",),
    ),
    _a("da-lat", "ward-3", "第三坊", "Ward 3", "3坊", "3동", order=3, terms=("Phường 3",)),
    _a(
        "da-lat",
        "french-quarter",
        "舊法國區",
        "French Quarter",
        "旧フランス人街",
        "구 프랑스 지구",
        "旧法国区",
        order=4,
    ),
    _a(
        "hue",
        "imperial-city",
        "皇城",
        "Imperial City",
        "王宮",
        "황성",
        order=1,
        terms=("Đại Nội", "Imperial City"),
    ),
    _a(
        "hue",
        "perfume-river-south",
        "香江南岸",
        "Perfume River South Bank",
        "フォーン川南岸",
        "흐엉강 남안",
        order=2,
        terms=("Hùng Vương", "Lê Lợi"),
    ),
    _a(
        "hue",
        "dong-ba-market",
        "東巴市場",
        "Dong Ba Market",
        "ドンバ市場",
        "동바 시장",
        "东巴市场",
        order=3,
        terms=("Đông Ba",),
    ),
    _a("hue", "new-town", "新城區", "New Town", "新市街", "신시가지", "新城区", order=4),
)

AREA_SEEDS_BY_SLUG: dict[str, AreaSeed] = {seed.slug: seed for seed in AREA_SEEDS}


def area_seed_for(destination_id: str, source_name: str) -> AreaSeed | None:
    for seed in AREA_SEEDS:
        if seed.destination_id == destination_id and seed.source_name == source_name:
            return seed
    return None


def validate_area_catalog() -> None:
    if len(AREA_SEEDS) != 132:
        raise RuntimeError("area catalog must contain exactly 132 areas")
    slugs = [seed.slug for seed in AREA_SEEDS]
    if len(set(slugs)) != len(slugs):
        raise RuntimeError("area slugs must be unique")
    for seed in AREA_SEEDS:
        if destination_for_id(seed.destination_id) is None:
            raise RuntimeError(f"area {seed.slug} references unknown destination")
        if not SLUG_PATTERN.match(seed.key) or not SLUG_PATTERN.match(seed.slug):
            raise RuntimeError(f"area {seed.slug} must use a lowercase kebab-case key")
        validate_names(seed.names)
        if "／" in seed.source_name and " / " not in seed.names["en"]:
            raise RuntimeError(
                f"combined area {seed.slug} must keep both parts in its English name"
            )
        if seed.center is not None:
            latitude, longitude = seed.center
            if not (-90 <= latitude <= 90 and -180 <= longitude <= 180):
                raise RuntimeError(f"area {seed.slug} has an out-of-range center")
    seeded_pairs = {(seed.destination_id, seed.source_name) for seed in AREA_SEEDS}
    profile_pairs = {
        (profile.id, area) for profile in DESTINATIONS for area in profile.areas
    }
    if seeded_pairs != profile_pairs:
        missing = sorted(profile_pairs - seeded_pairs)
        extra = sorted(seeded_pairs - profile_pairs)
        raise RuntimeError(
            f"area catalog drifted from DestinationProfile.areas: missing={missing} extra={extra}"
        )
    for profile in DESTINATIONS:
        orders = [
            seed.display_order
            for seed in AREA_SEEDS
            if seed.destination_id == profile.id
        ]
        if len(set(orders)) != len(orders):
            raise RuntimeError(
                f"area display orders must be unique within {profile.id}"
            )


validate_area_catalog()
