from __future__ import annotations

from dataclasses import dataclass
from urllib.parse import quote

from app.destinations.catalog import destination_for_id
from app.i18n import LOCALES

COUNTRY_NAMES = {
    "JP": {"zh-TW": "日本", "zh-CN": "日本", "en": "Japan", "ja": "日本", "ko": "일본"},
    "KR": {"zh-TW": "韓國", "zh-CN": "韩国", "en": "South Korea", "ja": "韓国", "ko": "대한민국"},
    "TH": {"zh-TW": "泰國", "zh-CN": "泰国", "en": "Thailand", "ja": "タイ", "ko": "태국"},
    "TW": {"zh-TW": "台灣", "zh-CN": "台湾", "en": "Taiwan", "ja": "台湾", "ko": "대만"},
    "SG": {
        "zh-TW": "新加坡",
        "zh-CN": "新加坡",
        "en": "Singapore",
        "ja": "シンガポール",
        "ko": "싱가포르",
    },
    "HK": {"zh-TW": "香港", "zh-CN": "香港", "en": "Hong Kong", "ja": "香港", "ko": "홍콩"},
    "VN": {"zh-TW": "越南", "zh-CN": "越南", "en": "Vietnam", "ja": "ベトナム", "ko": "베트남"},
}

OFFICIAL_FOOD_SOURCES = {
    "JP": "https://www.japan.travel/en/uk/inspiration/food-and-drink/",
    "KR": "https://www.korea.net/AboutKorea/Korean-Life/Food",
    "TH": "https://www.tourismthailand.org/Articles/10-thai-dishes-you-must-try",
    "TW": "https://eng.taiwan.net.tw/m1.aspx?sNo=0002091",
    "SG": "https://www.visitsingapore.com/dining-drinks-singapore/local-dishes/",
    "HK": "https://www.discoverhongkong.com/eng/explore/dining.html",
    "VN": "https://vietnam.travel/things-to-do/vietnam-food-20-must-try-dishes",
}


@dataclass(frozen=True)
class FoodSeed:
    slug: str
    country_code: str
    name: str
    simplified_name: str
    local_name: str
    romanized_name: str
    food_kind: str
    meal_types: tuple[str, ...]
    ingredient_tags: tuple[str, ...]
    dietary_notes: tuple[str, ...]
    destination_ids: tuple[str, ...]
    description: str
    wikipedia_title: str
    display_order: int

    @property
    def source_urls(self) -> tuple[str, ...]:
        return (
            OFFICIAL_FOOD_SOURCES[self.country_code],
            f"https://en.wikipedia.org/wiki/{quote(self.wikipedia_title.replace(' ', '_'))}",
        )

    @property
    def localized_names(self) -> dict[str, str]:
        return {
            "zh-TW": self.name,
            "zh-CN": self.simplified_name,
            "en": self.romanized_name,
            "ja": self.local_name if self.country_code == "JP" else self.romanized_name,
            "ko": self.local_name if self.country_code == "KR" else self.romanized_name,
        }

    @property
    def localized_summaries(self) -> dict[str, str]:
        country = COUNTRY_NAMES[self.country_code]
        return {
            "zh-TW": self.description,
            "zh-CN": (
                f"{self.simplified_name}是{country['zh-CN']}具代表性的地方美食，"
                "可在推荐城市的市场或传统街区品尝。"
            ),
            "en": (
                f"{self.romanized_name} is a representative food of {country['en']}, "
                "best explored through approved local markets and food districts."
            ),
            "ja": (
                f"{self.localized_names['ja']}は{country['ja']}を代表する料理で、"
                "現地の市場や食文化地区で楽しめます。"
            ),
            "ko": (
                f"{self.localized_names['ko']}은(는) {country['ko']}을 대표하는 음식으로, "
                "현지 시장과 음식 거리에서 경험할 수 있습니다."
            ),
        }

    @property
    def search_text(self) -> str:
        destinations = [destination_for_id(item) for item in self.destination_ids]
        return " ".join(
            [
                self.slug,
                self.country_code,
                self.local_name,
                self.romanized_name,
                *self.localized_names.values(),
                *(item.city for item in destinations if item is not None),
                *self.ingredient_tags,
            ]
        ).casefold()


def _food(
    slug: str,
    country: str,
    name: str,
    simplified: str,
    local: str,
    romanized: str,
    kind: str,
    meals: tuple[str, ...],
    ingredients: tuple[str, ...],
    destinations: tuple[str, ...],
    description: str,
    wiki: str,
    order: int,
    notes: tuple[str, ...] = (),
) -> FoodSeed:
    return FoodSeed(
        slug,
        country,
        name,
        simplified,
        local,
        romanized,
        kind,
        meals,
        ingredients,
        notes,
        destinations,
        description,
        wiki,
        order,
    )


FOOD_SEEDS: tuple[FoodSeed, ...] = (
    # Japan
    _food(
        "jp-sushi",
        "JP",
        "壽司",
        "寿司",
        "寿司",
        "Sushi",
        "main",
        ("lunch", "dinner"),
        ("米", "海鮮"),
        ("tokyo", "osaka-kyoto", "fukuoka", "sapporo", "kanazawa"),
        "以醋飯搭配海鮮或蔬菜，是日本地域與季節食材的代表吃法。",
        "Sushi",
        1,
        ("常見版本含生食海鮮",),
    ),
    _food(
        "jp-ramen",
        "JP",
        "拉麵",
        "拉面",
        "ラーメン",
        "Ramen",
        "noodle_soup",
        ("lunch", "dinner"),
        ("麵", "高湯"),
        ("tokyo", "osaka-kyoto", "fukuoka", "sapporo", "sendai"),
        "以小麥麵和地方湯頭組成，各城市發展出豚骨、味噌、醬油等風格。",
        "Ramen",
        2,
        ("湯底可能含豬肉或魚介",),
    ),
    _food(
        "jp-tempura",
        "JP",
        "天婦羅",
        "天妇罗",
        "天ぷら",
        "Tempura",
        "main",
        ("lunch", "dinner"),
        ("海鮮", "蔬菜", "麵衣"),
        ("tokyo", "osaka-kyoto", "kanazawa"),
        "將海鮮與時蔬裹上薄麵衣酥炸，重點在輕盈口感與當季食材。",
        "Tempura",
        3,
        ("含麩質，常見版本含海鮮",),
    ),
    _food(
        "jp-okonomiyaki",
        "JP",
        "御好燒",
        "御好烧",
        "お好み焼き",
        "Okonomiyaki",
        "street_food",
        ("lunch", "dinner"),
        ("高麗菜", "麵糊"),
        ("osaka-kyoto", "hiroshima"),
        "以高麗菜和麵糊為基礎，大阪與廣島各有不同堆疊與配料方式。",
        "Okonomiyaki",
        4,
        ("醬汁與麵糊通常含麩質",),
    ),
    _food(
        "jp-takoyaki",
        "JP",
        "章魚燒",
        "章鱼烧",
        "たこ焼き",
        "Takoyaki",
        "street_food",
        ("snack", "dinner"),
        ("章魚", "麵糊"),
        ("osaka-kyoto",),
        "將章魚塊包入圓形麵糊煎烤，是大阪街頭最具代表性的小吃之一。",
        "Takoyaki",
        5,
        ("含海鮮與麩質",),
    ),
    _food(
        "jp-tonkatsu",
        "JP",
        "炸豬排",
        "炸猪排",
        "豚カツ",
        "Tonkatsu",
        "main",
        ("lunch", "dinner"),
        ("豬肉", "麵包粉"),
        ("tokyo", "nagoya", "kanazawa"),
        "厚切豬排裹麵包粉炸至酥脆，常搭配高麗菜絲、白飯和味噌湯。",
        "Tonkatsu",
        6,
        ("含豬肉與麩質",),
    ),
    _food(
        "jp-udon",
        "JP",
        "烏龍麵",
        "乌冬面",
        "うどん",
        "Udon",
        "noodle_soup",
        ("breakfast", "lunch", "dinner"),
        ("小麥麵", "高湯"),
        ("osaka-kyoto", "fukuoka", "nagoya"),
        "粗厚有彈性的小麥麵，可冷食或搭配清湯，各地有不同麵體與湯頭。",
        "Udon",
        7,
        ("含麩質",),
    ),
    _food(
        "jp-soba",
        "JP",
        "蕎麥麵",
        "荞麦面",
        "そば",
        "Soba",
        "noodle_soup",
        ("lunch", "dinner"),
        ("蕎麥", "高湯"),
        ("tokyo", "sendai", "nagoya"),
        "以蕎麥粉製麵，可冷蘸或熱湯食用，適合體驗日本傳統麵食文化。",
        "Soba",
        8,
        ("可能混合小麥並含麩質",),
    ),
    _food(
        "jp-yakitori",
        "JP",
        "日式烤雞串",
        "日式烤鸡串",
        "焼き鳥",
        "Yakitori",
        "street_food",
        ("dinner",),
        ("雞肉", "醬汁"),
        ("tokyo", "fukuoka", "sendai"),
        "將雞肉不同部位串烤，以鹽或醬汁調味，是居酒屋與屋台常見料理。",
        "Yakitori",
        9,
        ("醬汁可能含大豆與麩質",),
    ),
    _food(
        "jp-wagashi",
        "JP",
        "和菓子",
        "和果子",
        "和菓子",
        "Wagashi",
        "dessert",
        ("snack", "dessert"),
        ("紅豆", "米粉"),
        ("osaka-kyoto", "kanazawa", "tokyo"),
        "以豆餡、米與季節造型呈現的傳統點心，常搭配抹茶品嘗。",
        "Wagashi",
        10,
    ),
    # South Korea
    _food(
        "kr-kimchi",
        "KR",
        "泡菜",
        "泡菜",
        "김치",
        "Kimchi",
        "main",
        ("lunch", "dinner"),
        ("蔬菜", "辣椒", "發酵"),
        ("seoul", "busan", "jeju", "daegu", "gyeongju", "jeonju"),
        "以蔬菜、辣椒和發酵工法製成，是韓國餐桌不可缺少的配菜與飲食文化象徵。",
        "Kimchi",
        11,
        ("部分版本含魚露或海鮮",),
    ),
    _food(
        "kr-bibimbap",
        "KR",
        "韓式拌飯",
        "韩式拌饭",
        "비빔밥",
        "Bibimbap",
        "main",
        ("lunch", "dinner"),
        ("米", "蔬菜", "辣醬"),
        ("seoul", "jeonju", "daegu"),
        "將米飯、時蔬、肉類與辣醬拌勻食用，全州是著名的地方代表。",
        "Bibimbap",
        12,
        ("可依需求選擇不含肉版本",),
    ),
    _food(
        "kr-bulgogi",
        "KR",
        "韓式烤肉",
        "韩式烤肉",
        "불고기",
        "Bulgogi",
        "main",
        ("lunch", "dinner"),
        ("牛肉", "醬油"),
        ("seoul", "busan", "jeonju"),
        "以甜鹹醬汁醃漬薄切肉片後燒烤或拌炒，口味溫和且適合配飯。",
        "Bulgogi",
        13,
        ("常見版本含牛肉與大豆",),
    ),
    _food(
        "kr-samgyeopsal",
        "KR",
        "韓式五花肉",
        "韩式五花肉",
        "삼겹살",
        "Samgyeopsal",
        "main",
        ("dinner",),
        ("豬肉", "生菜"),
        ("seoul", "busan", "jeju", "daegu"),
        "厚切五花肉在桌邊烤熟，再以生菜、蒜片和醬料包食。",
        "Samgyeopsal",
        14,
        ("含豬肉",),
    ),
    _food(
        "kr-tteokbokki",
        "KR",
        "辣炒年糕",
        "辣炒年糕",
        "떡볶이",
        "Tteokbokki",
        "street_food",
        ("snack", "dinner"),
        ("年糕", "辣醬"),
        ("seoul", "busan", "daegu"),
        "以Q彈年糕拌煮甜辣醬汁，是市場與街邊攤常見的國民小吃。",
        "Tteokbokki",
        15,
        ("醬料可能含魚漿與麩質",),
    ),
    _food(
        "kr-japchae",
        "KR",
        "韓式雜菜",
        "韩式杂菜",
        "잡채",
        "Japchae",
        "main",
        ("lunch", "dinner"),
        ("冬粉", "蔬菜"),
        ("seoul", "jeonju", "gyeongju"),
        "將地瓜冬粉與蔬菜、肉絲以芝麻油拌炒，常見於節慶與宴席。",
        "Japchae",
        16,
        ("醬油通常含大豆",),
    ),
    _food(
        "kr-samgyetang",
        "KR",
        "蔘雞湯",
        "参鸡汤",
        "삼계탕",
        "Samgyetang",
        "noodle_soup",
        ("lunch", "dinner"),
        ("雞肉", "人蔘", "糯米"),
        ("seoul", "daegu"),
        "整雞填入糯米、人蔘與香料燉煮，是韓國夏季補身文化的代表料理。",
        "Samgye-tang",
        17,
        ("含雞肉",),
    ),
    _food(
        "kr-naengmyeon",
        "KR",
        "韓式冷麵",
        "韩式冷面",
        "냉면",
        "Naengmyeon",
        "noodle_soup",
        ("lunch", "dinner"),
        ("蕎麥麵", "冷湯"),
        ("seoul", "busan", "daegu"),
        "細韌麵條搭配冰涼湯汁或辣醬，是炎熱季節常見的清爽麵食。",
        "Naengmyeon",
        18,
        ("部分麵條含蕎麥或小麥",),
    ),
    _food(
        "kr-hotteok",
        "KR",
        "糖餅",
        "糖饼",
        "호떡",
        "Hotteok",
        "dessert",
        ("snack", "dessert"),
        ("麵糰", "糖", "堅果"),
        ("seoul", "busan", "jeonju"),
        "煎製麵餅包入黑糖與堅果餡，冬季在市場與街頭特別常見。",
        "Hotteok",
        19,
        ("含麩質，常見版本含堅果",),
    ),
    _food(
        "kr-gimbap",
        "KR",
        "韓式紫菜飯捲",
        "韩式紫菜饭卷",
        "김밥",
        "Gimbap",
        "street_food",
        ("breakfast", "lunch", "snack"),
        ("米", "海苔", "蔬菜"),
        ("seoul", "busan", "jeju", "gyeongju"),
        "米飯與多種配料捲入海苔，方便攜帶，是市場和郊遊常見餐點。",
        "Gimbap",
        20,
    ),
    # Thailand
    _food(
        "th-pad-thai",
        "TH",
        "泰式炒河粉",
        "泰式炒河粉",
        "ผัดไทย",
        "Pad Thai",
        "main",
        ("lunch", "dinner"),
        ("河粉", "羅望子", "花生"),
        ("bangkok", "chiang-mai", "phuket", "krabi", "chiang-rai"),
        "河粉以羅望子醬拌炒，搭配豆芽、蛋與花生，呈現酸甜鹹平衡。",
        "Pad Thai",
        21,
        ("常見版本含花生、蛋與海鮮",),
    ),
    _food(
        "th-tom-yum",
        "TH",
        "冬蔭功湯",
        "冬阴功汤",
        "ต้มยำกุ้ง",
        "Tom Yum Goong",
        "noodle_soup",
        ("lunch", "dinner"),
        ("蝦", "香茅", "酸辣湯"),
        ("bangkok", "phuket", "krabi"),
        "以香茅、南薑、檸檬葉和辣椒煮成的酸辣蝦湯，香氣鮮明。",
        "Tom yum",
        22,
        ("含甲殼類海鮮",),
    ),
    _food(
        "th-green-curry",
        "TH",
        "泰式綠咖哩",
        "泰式绿咖喱",
        "แกงเขียวหวาน",
        "Green Curry",
        "main",
        ("lunch", "dinner"),
        ("椰奶", "綠咖哩", "香草"),
        ("bangkok", "chiang-mai", "phuket"),
        "綠辣椒香料與椰奶煮成濃郁咖哩，常搭配雞肉、茄子與米飯。",
        "Green curry",
        23,
        ("常見版本含魚露",),
    ),
    _food(
        "th-som-tam",
        "TH",
        "青木瓜沙拉",
        "青木瓜沙拉",
        "ส้มตำ",
        "Som Tam",
        "street_food",
        ("lunch", "snack", "dinner"),
        ("青木瓜", "辣椒", "花生"),
        ("bangkok", "chiang-mai", "chiang-rai"),
        "青木瓜絲搗拌辣椒、酸汁與花生，口感爽脆並帶酸辣甜鹹層次。",
        "Green papaya salad",
        24,
        ("常見版本含花生、魚露或蝦米",),
    ),
    _food(
        "th-khao-man-gai",
        "TH",
        "泰式海南雞飯",
        "泰式海南鸡饭",
        "ข้าวมันไก่",
        "Khao Man Gai",
        "main",
        ("breakfast", "lunch", "dinner"),
        ("雞肉", "雞油飯"),
        ("bangkok", "chiang-mai", "chiang-rai"),
        "嫩雞搭配雞湯煮飯和辛香沾醬，是早餐到晚餐都常見的平民料理。",
        "Hainanese chicken rice",
        25,
        ("含雞肉",),
    ),
    _food(
        "th-boat-noodles",
        "TH",
        "船麵",
        "船面",
        "ก๋วยเตี๋ยวเรือ",
        "Boat Noodles",
        "noodle_soup",
        ("lunch", "dinner"),
        ("米粉", "濃湯"),
        ("bangkok",),
        "小碗米粉搭配香料濃湯，源自曼谷水上市集與運河飲食文化。",
        "Boat noodles",
        26,
        ("湯底通常含肉類",),
    ),
    _food(
        "th-mango-sticky-rice",
        "TH",
        "芒果糯米飯",
        "芒果糯米饭",
        "ข้าวเหนียวมะม่วง",
        "Mango Sticky Rice",
        "dessert",
        ("snack", "dessert"),
        ("芒果", "糯米", "椰奶"),
        ("bangkok", "chiang-mai", "phuket", "krabi"),
        "熟芒果配椰奶糯米與微鹹椰醬，是泰國代表性熱帶甜點。",
        "Mango sticky rice",
        27,
    ),
    _food(
        "th-massaman-curry",
        "TH",
        "馬薩曼咖哩",
        "马萨曼咖喱",
        "แกงมัสมั่น",
        "Massaman Curry",
        "main",
        ("lunch", "dinner"),
        ("椰奶", "香料", "馬鈴薯"),
        ("bangkok", "phuket", "krabi"),
        "融合南亞香料與泰式椰奶的溫和咖哩，常與牛肉或雞肉慢燉。",
        "Massaman curry",
        28,
        ("常見版本含花生",),
    ),
    _food(
        "th-khao-soi",
        "TH",
        "泰北咖哩麵",
        "泰北咖喱面",
        "ข้าวซอย",
        "Khao Soi",
        "noodle_soup",
        ("lunch", "dinner"),
        ("蛋麵", "椰奶咖哩"),
        ("chiang-mai", "chiang-rai"),
        "椰奶咖哩湯搭配軟麵與炸麵，是清邁與清萊代表性的泰北料理。",
        "Khao soi",
        29,
        ("含麩質，常見版本含肉類",),
    ),
    _food(
        "th-moo-ping",
        "TH",
        "泰式烤豬肉串",
        "泰式烤猪肉串",
        "หมูปิ้ง",
        "Moo Ping",
        "street_food",
        ("breakfast", "snack", "dinner"),
        ("豬肉", "椰奶", "香料"),
        ("bangkok", "chiang-mai", "chiang-rai"),
        "醃漬豬肉串炭烤後搭配糯米，是市場與通勤早餐常見的小吃。",
        "Moo ping",
        30,
        ("含豬肉",),
    ),
    # Taiwan
    _food(
        "tw-beef-noodle-soup",
        "TW",
        "牛肉麵",
        "牛肉面",
        "牛肉麵",
        "Beef Noodle Soup",
        "noodle_soup",
        ("lunch", "dinner"),
        ("牛肉", "麵", "高湯"),
        ("taipei", "taichung", "kaohsiung", "tainan"),
        "紅燒或清燉牛肉湯搭配麵條，是台灣城市麵食文化的代表。",
        "Beef noodle soup",
        31,
        ("含牛肉與麩質",),
    ),
    _food(
        "tw-xiaolongbao",
        "TW",
        "小籠包",
        "小笼包",
        "小籠包",
        "Xiaolongbao",
        "main",
        ("breakfast", "lunch", "dinner"),
        ("麵皮", "豬肉", "湯汁"),
        ("taipei", "taichung"),
        "薄麵皮包入肉餡與湯汁蒸熟，食用時可搭配薑絲與醋。",
        "Xiaolongbao",
        32,
        ("常見版本含豬肉與麩質",),
    ),
    _food(
        "tw-lu-rou-fan",
        "TW",
        "滷肉飯",
        "卤肉饭",
        "滷肉飯",
        "Lu Rou Fan",
        "main",
        ("breakfast", "lunch", "dinner"),
        ("米", "豬肉", "醬油"),
        ("taipei", "taichung", "kaohsiung", "tainan"),
        "細切豬肉以醬油香料慢滷後淋在白飯上，各地肥瘦與調味不同。",
        "Braised pork rice",
        33,
        ("含豬肉與大豆",),
    ),
    _food(
        "tw-oyster-omelet",
        "TW",
        "蚵仔煎",
        "蚵仔煎",
        "蚵仔煎",
        "Oyster Omelet",
        "street_food",
        ("snack", "dinner"),
        ("牡蠣", "蛋", "地瓜粉"),
        ("taipei", "taichung", "kaohsiung", "tainan"),
        "鮮蚵、蛋與澱粉漿煎成柔韌口感，再淋上甜鹹醬汁。",
        "Oyster omelette",
        34,
        ("含牡蠣與蛋",),
    ),
    _food(
        "tw-stinky-tofu",
        "TW",
        "臭豆腐",
        "臭豆腐",
        "臭豆腐",
        "Stinky Tofu",
        "street_food",
        ("snack", "dinner"),
        ("豆腐", "發酵"),
        ("taipei", "taichung", "kaohsiung", "tainan"),
        "發酵豆腐可油炸、清蒸或麻辣燉煮，是台灣夜市辨識度極高的小吃。",
        "Stinky tofu",
        35,
        ("含大豆",),
    ),
    _food(
        "tw-bubble-tea",
        "TW",
        "珍珠奶茶",
        "珍珠奶茶",
        "珍珠奶茶",
        "Bubble Tea",
        "drink",
        ("snack", "drink"),
        ("茶", "牛奶", "粉圓"),
        ("taipei", "taichung", "kaohsiung", "tainan"),
        "茶飲加入Q彈粉圓與奶香，起源於台灣並發展出多種甜度與配料。",
        "Bubble tea",
        36,
        ("奶類可依店家更換",),
    ),
    _food(
        "tw-gua-bao",
        "TW",
        "刈包",
        "刈包",
        "刈包",
        "Gua Bao",
        "street_food",
        ("snack", "lunch"),
        ("麵皮", "豬肉", "花生粉"),
        ("taipei", "taichung", "tainan"),
        "蒸軟麵皮夾入滷五花肉、酸菜、花生粉與香菜，口感層次豐富。",
        "Gua bao",
        37,
        ("含豬肉、花生與麩質",),
    ),
    _food(
        "tw-pineapple-cake",
        "TW",
        "鳳梨酥",
        "凤梨酥",
        "鳳梨酥",
        "Pineapple Cake",
        "dessert",
        ("snack", "dessert"),
        ("鳳梨", "麵粉", "奶油"),
        ("taipei", "taichung", "kaohsiung"),
        "酥鬆外皮包裹鳳梨果餡，是常見的台灣茶點與伴手禮。",
        "Pineapple cake",
        38,
        ("常見版本含奶與麩質",),
    ),
    _food(
        "tw-danzai-noodles",
        "TW",
        "擔仔麵",
        "担仔面",
        "擔仔麵",
        "Danzai Noodles",
        "noodle_soup",
        ("lunch", "dinner"),
        ("麵", "肉燥", "蝦湯"),
        ("tainan",),
        "小碗麵搭配蝦湯、肉燥與蒜泥，是台南具代表性的傳統小吃。",
        "Danzai noodles",
        39,
        ("常見版本含豬肉與甲殼類",),
    ),
    _food(
        "tw-scallion-pancake",
        "TW",
        "蔥油餅",
        "葱油饼",
        "蔥油餅",
        "Scallion Pancake",
        "street_food",
        ("breakfast", "snack"),
        ("麵粉", "蔥"),
        ("taipei", "taichung", "kaohsiung"),
        "麵糰揉入青蔥後煎至外酥內韌，是早餐店與街頭常見點心。",
        "Scallion pancake",
        40,
        ("含麩質",),
    ),
    # Singapore
    _food(
        "sg-chicken-rice",
        "SG",
        "海南雞飯",
        "海南鸡饭",
        "海南雞飯",
        "Hainanese Chicken Rice",
        "main",
        ("breakfast", "lunch", "dinner"),
        ("雞肉", "雞油飯"),
        ("singapore",),
        "嫩雞、香米、辣椒醬與薑蓉組成，是新加坡熟食中心的代表料理。",
        "Hainanese chicken rice",
        41,
        ("含雞肉",),
    ),
    _food(
        "sg-laksa",
        "SG",
        "叻沙",
        "叻沙",
        "叻沙",
        "Laksa",
        "noodle_soup",
        ("lunch", "dinner"),
        ("米粉", "椰奶", "海鮮"),
        ("singapore",),
        "米粉浸在椰奶香料湯中，加上海鮮或魚餅，加東風格尤其知名。",
        "Laksa",
        42,
        ("常見版本含海鮮",),
    ),
    _food(
        "sg-chilli-crab",
        "SG",
        "辣椒螃蟹",
        "辣椒螃蟹",
        "辣椒螃蟹",
        "Chilli Crab",
        "main",
        ("dinner",),
        ("螃蟹", "辣椒", "番茄"),
        ("singapore",),
        "螃蟹裹上甜辣濃稠醬汁，通常搭配炸饅頭享用。",
        "Chilli crab",
        43,
        ("含甲殼類、蛋與麩質",),
    ),
    _food(
        "sg-char-kway-teow",
        "SG",
        "炒粿條",
        "炒粿条",
        "炒粿條",
        "Char Kway Teow",
        "main",
        ("lunch", "dinner"),
        ("河粉", "醬油", "豆芽"),
        ("singapore",),
        "寬河粉以大火和醬油快炒，常加入蛋、臘腸與海鮮。",
        "Char kway teow",
        44,
        ("常見版本含蛋、豬肉或海鮮",),
    ),
    _food(
        "sg-bak-kut-teh",
        "SG",
        "肉骨茶",
        "肉骨茶",
        "肉骨茶",
        "Bak Kut Teh",
        "noodle_soup",
        ("breakfast", "lunch", "dinner"),
        ("豬肋骨", "胡椒", "香料"),
        ("singapore",),
        "豬肋骨以胡椒、蒜與香料熬湯，新加坡常見風格辛香清亮。",
        "Bak kut teh",
        45,
        ("含豬肉",),
    ),
    _food(
        "sg-kaya-toast",
        "SG",
        "咖椰吐司",
        "咖椰吐司",
        "咖椰吐司",
        "Kaya Toast",
        "dessert",
        ("breakfast", "snack"),
        ("吐司", "椰子醬", "奶油"),
        ("singapore",),
        "烤吐司夾入咖椰醬與奶油，常搭配半熟蛋和南洋咖啡作早餐。",
        "Kaya toast",
        46,
        ("常見版本含蛋、奶與麩質",),
    ),
    _food(
        "sg-satay",
        "SG",
        "沙嗲",
        "沙嗲",
        "沙嗲",
        "Satay",
        "street_food",
        ("dinner", "snack"),
        ("肉串", "花生醬"),
        ("singapore",),
        "醃漬肉串炭烤後搭配花生醬、黃瓜與米糕，是夜間熟食區人氣小吃。",
        "Satay",
        47,
        ("含花生，肉類依攤位而異",),
    ),
    _food(
        "sg-rojak",
        "SG",
        "囉惹",
        "罗惹",
        "囉惹",
        "Rojak",
        "street_food",
        ("snack", "lunch"),
        ("水果", "蔬菜", "濃醬"),
        ("singapore",),
        "水果、蔬菜與油條拌入甜鹹濃醬，呈現多元飲食文化的混合風味。",
        "Rojak",
        48,
        ("常見版本含花生、蝦醬與麩質",),
    ),
    _food(
        "sg-fish-head-curry",
        "SG",
        "咖哩魚頭",
        "咖喱鱼头",
        "咖哩魚頭",
        "Fish Head Curry",
        "main",
        ("lunch", "dinner"),
        ("魚頭", "咖哩", "蔬菜"),
        ("singapore",),
        "魚頭與蔬菜浸煮在香料咖哩中，融合南印度與新加坡飲食特色。",
        "Fish head curry",
        49,
        ("含魚類",),
    ),
    _food(
        "sg-ice-kacang",
        "SG",
        "紅豆冰",
        "红豆冰",
        "紅豆冰",
        "Ice Kacang",
        "dessert",
        ("snack", "dessert"),
        ("刨冰", "紅豆", "糖漿"),
        ("singapore",),
        "刨冰淋上彩色糖漿、紅豆與多種配料，是炎熱天氣常見甜品。",
        "Ais kacang",
        50,
    ),
    # Hong Kong
    _food(
        "hk-dim-sum",
        "HK",
        "點心",
        "点心",
        "點心",
        "Dim Sum",
        "main",
        ("breakfast", "lunch"),
        ("麵皮", "肉類", "海鮮"),
        ("hong-kong",),
        "蒸籠與小碟形式的多樣茶點，搭配飲茶構成香港重要的社交飲食文化。",
        "Dim sum",
        51,
        ("過敏原依品項而異",),
    ),
    _food(
        "hk-roast-goose",
        "HK",
        "燒鵝",
        "烧鹅",
        "燒鵝",
        "Roast Goose",
        "main",
        ("lunch", "dinner"),
        ("鵝肉", "燒味醬料"),
        ("hong-kong",),
        "醃製鵝隻以高溫燒烤出脆皮與肉汁，是香港燒味代表。",
        "Roast goose",
        52,
        ("含禽肉",),
    ),
    _food(
        "hk-wonton-noodles",
        "HK",
        "雲吞麵",
        "云吞面",
        "雲吞麵",
        "Wonton Noodles",
        "noodle_soup",
        ("breakfast", "lunch", "dinner"),
        ("麵", "蝦雲吞", "高湯"),
        ("hong-kong",),
        "細彈麵條配上蝦肉雲吞與清湯，講究麵體、湯頭與上桌速度。",
        "Wonton noodles",
        53,
        ("含甲殼類、蛋與麩質",),
    ),
    _food(
        "hk-egg-tart",
        "HK",
        "港式蛋撻",
        "港式蛋挞",
        "蛋撻",
        "Hong Kong Egg Tart",
        "dessert",
        ("breakfast", "snack", "dessert"),
        ("蛋", "奶", "酥皮"),
        ("hong-kong",),
        "酥皮或牛油皮盛裝滑嫩蛋奶餡，是茶餐廳與餅店經典點心。",
        "Egg tart",
        54,
        ("含蛋、奶與麩質",),
    ),
    _food(
        "hk-pineapple-bun",
        "HK",
        "菠蘿包",
        "菠萝包",
        "菠蘿包",
        "Pineapple Bun",
        "dessert",
        ("breakfast", "snack"),
        ("麵包", "酥皮", "奶油"),
        ("hong-kong",),
        "麵包頂部覆上酥脆甜皮，外形似菠蘿，常夾厚切牛油食用。",
        "Pineapple bun",
        55,
        ("通常不含菠蘿，含奶與麩質",),
    ),
    _food(
        "hk-claypot-rice",
        "HK",
        "煲仔飯",
        "煲仔饭",
        "煲仔飯",
        "Claypot Rice",
        "main",
        ("dinner",),
        ("米", "臘味", "鍋巴"),
        ("hong-kong",),
        "米飯與臘味或排骨在砂鍋中炊煮，底部形成香脆鍋巴。",
        "Claypot rice",
        56,
        ("配料常含豬肉與大豆",),
    ),
    _food(
        "hk-milk-tea",
        "HK",
        "港式奶茶",
        "港式奶茶",
        "絲襪奶茶",
        "Hong Kong Milk Tea",
        "drink",
        ("breakfast", "snack", "drink"),
        ("紅茶", "淡奶"),
        ("hong-kong",),
        "濃紅茶經細網反覆沖泡後加入淡奶，是茶餐廳文化的重要飲品。",
        "Hong Kong-style milk tea",
        57,
        ("含奶，可詢問無糖版本",),
    ),
    _food(
        "hk-cart-noodles",
        "HK",
        "車仔麵",
        "车仔面",
        "車仔麵",
        "Cart Noodles",
        "noodle_soup",
        ("lunch", "dinner"),
        ("麵", "自選配料"),
        ("hong-kong",),
        "自由選擇麵體、湯底與多種配料，源自街頭小販的平價飲食。",
        "Cart noodle",
        58,
        ("過敏原依自選配料而異",),
    ),
    _food(
        "hk-siu-mei",
        "HK",
        "港式燒味",
        "港式烧味",
        "燒味",
        "Siu Mei",
        "main",
        ("lunch", "dinner"),
        ("燒肉", "醬汁"),
        ("hong-kong",),
        "叉燒、燒肉、燒鴨等掛爐肉食切盤配飯，是香港日常快餐主角。",
        "Siu mei",
        59,
        ("多數品項含肉類與大豆",),
    ),
    _food(
        "hk-congee",
        "HK",
        "港式粥品",
        "港式粥品",
        "粥",
        "Hong Kong Congee",
        "main",
        ("breakfast", "lunch", "dinner"),
        ("米", "高湯"),
        ("hong-kong",),
        "米粒長時間熬至綿滑，再搭配魚片、牛肉或皮蛋等配料。",
        "Congee",
        60,
        ("配料與過敏原依品項而異",),
    ),
    # Vietnam
    _food(
        "vn-pho",
        "VN",
        "越南河粉",
        "越南河粉",
        "Phở",
        "Pho",
        "noodle_soup",
        ("breakfast", "lunch", "dinner"),
        ("河粉", "香料高湯", "香草"),
        ("hanoi", "ho-chi-minh-city", "da-nang", "da-lat", "hue"),
        "米製河粉搭配香料高湯、肉片與新鮮香草，南北風格各具特色。",
        "Pho",
        61,
        ("湯底通常含牛肉或雞肉",),
    ),
    _food(
        "vn-banh-mi",
        "VN",
        "越南法國麵包",
        "越南法棍",
        "Bánh mì",
        "Banh Mi",
        "street_food",
        ("breakfast", "lunch", "snack"),
        ("法國麵包", "醃菜", "肉類"),
        ("hanoi", "ho-chi-minh-city", "da-nang", "da-lat"),
        "酥脆法國麵包夾入肉類、醃菜、香草與醬料，反映越南飲食融合。",
        "Bánh mì",
        62,
        ("含麩質，餡料依店家而異",),
    ),
    _food(
        "vn-bun-cha",
        "VN",
        "河內烤肉米線",
        "河内烤肉米线",
        "Bún chả",
        "Bun Cha",
        "main",
        ("lunch", "dinner"),
        ("米線", "烤豬肉", "香草"),
        ("hanoi",),
        "炭烤豬肉放入酸甜魚露湯汁，搭配米線、香草和生菜食用。",
        "Bún chả",
        63,
        ("含豬肉與魚露",),
    ),
    _food(
        "vn-goi-cuon",
        "VN",
        "越南生春捲",
        "越南生春卷",
        "Gỏi cuốn",
        "Vietnamese Fresh Spring Rolls",
        "street_food",
        ("lunch", "snack"),
        ("米紙", "蝦", "香草"),
        ("ho-chi-minh-city", "da-nang", "hanoi"),
        "透明米紙包入蝦、米線、香草與蔬菜，口感清爽並搭配沾醬。",
        "Gỏi cuốn",
        64,
        ("常見版本含蝦與花生醬",),
    ),
    _food(
        "vn-banh-xeo",
        "VN",
        "越南煎餅",
        "越南煎饼",
        "Bánh xèo",
        "Banh Xeo",
        "street_food",
        ("lunch", "dinner"),
        ("米漿", "薑黃", "豆芽"),
        ("ho-chi-minh-city", "da-nang", "hue"),
        "薑黃米漿煎成薄脆外皮，包入豆芽、豬肉或海鮮後以生菜包食。",
        "Bánh xèo",
        65,
        ("常見版本含豬肉、海鮮與魚露",),
    ),
    _food(
        "vn-cao-lau",
        "VN",
        "高樓麵",
        "高楼面",
        "Cao lầu",
        "Cao Lau",
        "main",
        ("lunch", "dinner"),
        ("粗麵", "豬肉", "香草"),
        ("da-nang",),
        "會安代表性的粗麵搭配叉燒豬肉、香草與脆片，湯汁份量較少。",
        "Cao lầu",
        66,
        ("含豬肉與麩質",),
    ),
    _food(
        "vn-com-tam",
        "VN",
        "越南碎米飯",
        "越南碎米饭",
        "Cơm tấm",
        "Com Tam",
        "main",
        ("breakfast", "lunch", "dinner"),
        ("碎米", "烤肉", "魚露"),
        ("ho-chi-minh-city",),
        "碎米搭配烤豬排、肉餅、蛋與魚露，是胡志明市常見日常餐點。",
        "Cơm tấm",
        67,
        ("常見版本含豬肉、蛋與魚露",),
    ),
    _food(
        "vn-bun-bo-hue",
        "VN",
        "順化牛肉米線",
        "顺化牛肉米线",
        "Bún bò Huế",
        "Bun Bo Hue",
        "noodle_soup",
        ("breakfast", "lunch", "dinner"),
        ("米線", "牛肉", "香茅"),
        ("hue", "da-nang", "ho-chi-minh-city"),
        "香茅辣湯搭配粗米線、牛肉與香草，是順化最具代表性的麵食。",
        "Bún bò Huế",
        68,
        ("常見湯底含牛肉、豬肉與魚露",),
    ),
    _food(
        "vn-egg-coffee",
        "VN",
        "雞蛋咖啡",
        "鸡蛋咖啡",
        "Cà phê trứng",
        "Vietnamese Egg Coffee",
        "drink",
        ("breakfast", "snack", "drink"),
        ("咖啡", "蛋黃", "煉乳"),
        ("hanoi",),
        "濃咖啡覆上打發蛋黃與煉乳形成綿密泡沫，是河內特色飲品。",
        "Egg coffee",
        69,
        ("含蛋與奶",),
    ),
    _food(
        "vn-che",
        "VN",
        "越南甜湯",
        "越南甜汤",
        "Chè",
        "Che",
        "dessert",
        ("snack", "dessert"),
        ("豆類", "椰奶", "水果"),
        ("hanoi", "ho-chi-minh-city", "da-nang", "hue"),
        "以豆類、果凍、水果與椰奶組合的甜品總稱，可冷食或熱食。",
        "Chè (Vietnamese dessert)",
        70,
    ),
)


def validate_catalog() -> None:
    if len(FOOD_SEEDS) != 70:
        raise RuntimeError(f"food bootstrap must contain exactly 70 rows, found {len(FOOD_SEEDS)}")
    if len({item.slug for item in FOOD_SEEDS}) != len(FOOD_SEEDS):
        raise RuntimeError("food bootstrap slugs must be unique")
    supported = set(COUNTRY_NAMES)
    counts = {code: sum(item.country_code == code for item in FOOD_SEEDS) for code in supported}
    if any(value != 10 for value in counts.values()):
        raise RuntimeError(f"food bootstrap must contain ten foods per country: {counts}")
    destination_ids = {
        item
        for food in FOOD_SEEDS
        for item in food.destination_ids
        if destination_for_id(item) is None
    }
    if destination_ids:
        raise RuntimeError(f"food bootstrap has unknown destinations: {sorted(destination_ids)}")
    if any(set(item.localized_names) != set(LOCALES) for item in FOOD_SEEDS):
        raise RuntimeError("food bootstrap must contain all public locales")
    if any(not item.source_urls or not item.destination_ids for item in FOOD_SEEDS):
        raise RuntimeError("food bootstrap sources and destinations are required")
    for code in supported:
        if len({item.food_kind for item in FOOD_SEEDS if item.country_code == code}) < 3:
            raise RuntimeError(f"{code} must cover at least three food kinds")


validate_catalog()
