export const KINDS = ["hotel", "transfer", "tour", "esim"] as const;
export const CITIES = ["tokyo", "osaka", "kyoto", "seoul", "busan", "taipei"] as const;
export const PUBLIC_DESTINATIONS = [
  "tokyo",
  "osaka-kyoto",
  "fukuoka",
  "sapporo",
  "okinawa",
  "nagoya",
  "seoul",
  "busan",
  "jeju",
  "bangkok",
  "chiang-mai",
  "phuket",
  "krabi",
  "taipei",
  "singapore",
  "hong-kong",
  "hanoi",
  "ho-chi-minh-city",
  "da-nang",
  "taichung",
  "kaohsiung",
  "sendai",
  "kanazawa",
  "hiroshima",
  "daegu",
  "chiang-rai",
  "da-lat",
  "tainan",
  "gyeongju",
  "jeonju",
  "hue",
  "yokohama",
  "kamakura",
] as const;
export type Kind = typeof KINDS[number];
