// A local, editable planning viewer: timing and shot intent, never a claim of generated art.
import { productionNarrator } from "./design.mjs";
const escape = (value) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]);
export function storyboardHtml(works, profile) {
  const data = JSON.stringify(works.map(({ slug, source, design }) => ({ slug, title: source.series.title, design: { ...design, narrator: productionNarrator(source.setting, design) } }))).replace(/</g, "\\u003c");
  return `<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>十部動畫攝製檢查</title>
<style>body{margin:0;background:#101820;color:#edf2f7;font:16px/1.7 system-ui,sans-serif}header,main{max-width:1120px;margin:auto;padding:24px}h1{font-size:28px}p{color:#c4d3df}select,input,button{font:inherit;background:#233746;color:inherit;border:1px solid #506676;border-radius:8px;padding:8px}input{width:90%;accent-color:#efb366}article{background:#182936;border:1px solid #344c5e;border-radius:12px;padding:20px;margin:18px 0}small{color:#a5bbca}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}strong{color:#ffcf8a}.tag{display:inline-block;padding:3px 9px;border-radius:6px;background:#294755;margin:3px}pre{white-space:pre-wrap;font:inherit;color:#ccd9e3}button{cursor:pointer}@media(max-width:720px){.grid{grid-template-columns:1fr}header,main{padding:16px}}</style>
<header><h1>十部動畫攝製檢查</h1><p>中文先完成；所有字幕為 CC。此頁顯示拍攝設計與規劃秒數，尚未產生角色畫面、聲音或動畫。</p><select id="work" aria-label="作品">${works.map((work, index) => `<option value="${index}">${escape(work.source.series.title)}</option>`).join("")}</select> <span class="tag">${escape(profile.video.model)}</span><span class="tag">1080p・8 秒素材</span></header>
<main><h2>開場 30 秒</h2><input id="clock" type="range" min="0" max="29.9" step="0.1" value="0" aria-label="開場時間"><span id="time"></span><article id="shot"></article><h2>角色聲線與造型</h2><div id="cast" class="grid"></div><h2>40 集攝製重點</h2><select id="episode" aria-label="集數"></select><article id="detail"></article><h2>需試作確認</h2><article id="open"></article></main>
<script>const works=${data};const get=id=>document.getElementById(id);const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const list=a=>(a??[]).map(s=>'<p>'+safe(typeof s==='string'?s:JSON.stringify(s))+'</p>').join('');function shot(){const d=works[+get('work').value].design,t=+get('clock').value,s=d.opening_30s.find(s=>s.in_s<=t&&t<s.out_s)||d.opening_30s.at(-1);get('time').textContent=t.toFixed(1)+' 秒';get('shot').innerHTML='<strong>'+safe(s.id)+'｜'+s.in_s+'–'+s.out_s+' 秒｜'+safe(s.scale)+'</strong><h3>'+safe(s.action)+'</h3><p>運鏡：'+safe(s.camera)+'</p><p>對白意圖：'+safe(s.dialogue_intent)+'</p><p>聲音：'+safe(s.sound)+'</p><small>來源：'+safe(s.source_refs.join('；'))+'</small>'}function episode(){const d=works[+get('work').value].design,e=d.episodes[+get('episode').value];get('detail').innerHTML='<strong>第 '+e.episode+' 集 '+safe(e.title)+'</strong><h3>'+safe(e.hero_shot.action)+'</h3><p>'+safe(e.hero_shot.camera)+'｜'+safe(e.hero_shot.sound)+'</p>'+list(e.risk_controls.map(c=>c.risk+' → '+c.solution))+list(e.prop_checks)+list(e.voice_notes)+list(e.cc_notes)+'<small>'+safe(e.source_refs.join('；'))+'</small>'}function render(){const d=works[+get('work').value].design;get('clock').value=0;get('cast').innerHTML=d.characters.map(c=>'<article><strong>'+safe(c.id)+'｜'+safe(c.voice_name)+'</strong><p>'+safe(c.performance)+'</p><small>聲音已選，尚未試音</small>'+list(c.look_states.map(l=>l.id+'：'+l.cue))+'</article>').join('');get('episode').innerHTML=d.episodes.map((e,i)=>'<option value="'+i+'">'+e.episode+' '+safe(e.title)+'</option>').join('');get('open').innerHTML=list(d.unresolved.map(x=>x.issue+'：'+x.why));shot();episode()}get('work').onchange=render;get('clock').oninput=shot;get('episode').onchange=episode;render();</script></html>\n`;
}
