"use client";
import { useTranslations } from "next-intl";
import { unknownPetRule, type PetRule } from "@/lib/community/types";
import { Button, fieldClass, panelClass } from "./ui";
const booleans = ["ground_allowed","leash_required","carrier_required","stroller_required","stroller_allowed","diaper_required","indoor_allowed","outdoor_allowed","reservation_required","overnight_allowed"] as const;
export function PetRulesEditor({rules,onChange}: {rules:PetRule[];onChange:(rules:PetRule[])=>void}) {
 const t=useTranslations("community");
 function edit(index:number,patch:Partial<PetRule>) {onChange(rules.map((rule,i)=> i===index ? {...rule,...patch} : rule));}
 return <div className="space-y-4">{rules.map((rule,index)=><fieldset key={index} className={`${panelClass} space-y-4`}><legend className="font-bold">{t("speciesRule",{count:index+1})}</legend><div className="grid gap-3 sm:grid-cols-2"><label className="font-semibold">{t("species")}<input required maxLength={40} className={fieldClass} value={rule.species} onChange={(e)=>edit(index,{species:e.target.value})} /><small>{t("speciesHelp")}</small></label><label className="font-semibold">{t("status")}<select className={fieldClass} value={rule.status} onChange={(e)=>edit(index,{status:e.target.value as PetRule["status"]})}>{["allowed","conditional","not_allowed","unknown"].map((key)=><option key={key} value={key}>{t(`petStatus.${key}`)}</option>)}</select></label>
 {(["weight","count"] as const).map((kind)=>{const limit=kind==="weight" ? rule.weight_limit : rule.count_limit;return <label className="font-semibold" key={kind}>{t(`petFields.${kind}_limit`)}<select className={fieldClass} value={limit} onChange={(e)=>{const v=e.target.value as PetRule["weight_limit"];edit(index,kind==="weight" ? {weight_limit:v,max_weight_kg:v==="limited" ? 5:null} : {count_limit:v,max_count:v==="limited" ? 1:null});}}>{["unknown","none","limited"].map((key)=><option key={key} value={key}>{t(`limits.${key}`)}</option>)}</select>{limit==="limited" && <input aria-label={t(`petFields.${kind}_limit`)} required type="number" min={kind==="weight" ? 0.01:1} max={kind==="weight" ? 200:100} step={kind==="weight" ? 0.01:1} className={fieldClass} value={(kind==="weight" ? rule.max_weight_kg:rule.max_count)||""} onChange={(e)=>edit(index,kind==="weight" ? {max_weight_kg:Number(e.target.value)} : {max_count:Number(e.target.value)})} />}</label>;})}
 {booleans.map((key)=><label key={key} className="font-semibold">{t(`petFields.${key}`)}<select className={fieldClass} value={rule[key]===null ? "unknown":String(rule[key])} onChange={(e)=>edit(index,{[key]:e.target.value==="unknown" ? null:e.target.value==="true"})}><option value="unknown">{t("unknown")}</option><option value="true">{t("yes")}</option><option value="false">{t("no")}</option></select></label>)}
 <label className="font-semibold">{t("petFields.fee")}<input type="number" min={0} max={1000000} step={0.01} className={fieldClass} value={rule.fee_amount ?? ""} onChange={(e)=>edit(index,{fee_amount:e.target.value==="" ? null:Number(e.target.value),fee_currency:e.target.value==="" ? null:rule.fee_currency||"TWD"})} /></label><label className="font-semibold">{t("currency")}<input required={rule.fee_amount!==null} disabled={rule.fee_amount===null} pattern="[A-Z]{3}" maxLength={3} className={fieldClass} value={rule.fee_currency||""} onChange={(e)=>edit(index,{fee_currency:e.target.value})} /></label></div>
 <label className="block font-semibold">{t("notes")}<textarea maxLength={2000} className={fieldClass} value={rule.notes} onChange={(e)=>edit(index,{notes:e.target.value})} /></label><Button secondary onClick={()=>onChange(rules.filter((_,i)=>i!==index))}>{t("remove")}</Button></fieldset>)}<Button secondary disabled={rules.length>=10} onClick={()=>onChange([...rules,{...unknownPetRule,species:rules.length===0 ? "dog":""}])}>{t("addSpeciesRule")}</Button></div>;
}
