"""Geographic areas (districts and nearby day-trip zones) inside each hotspot city.

Every hotspot is assigned to an area purely from its coordinates: an area is a
circle (center + radius) and a hotspot belongs to the circle that contains it with
the smallest ``distance / radius`` ratio, ties going to catalog order. A place that
falls outside every circle of its city keeps no area rather than being stretched into
the nearest one, so a 30 km day trip never shows up as "新宿".

Radii follow two rules of thumb: 1-3 km for urban districts, 5-20 km for reviewed
suburban or day-trip zones. Area names align with the lodging areas exposed by
``app.destinations.catalog`` where the two overlap.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from decimal import Decimal

from app.hotspots.discovery import haversine_km
from app.i18n import Locale


@dataclass(frozen=True)
class HotspotArea:
    code: str
    names: Mapping[Locale, str]
    latitude: float
    longitude: float
    radius_km: float


def _area(
    code: str,
    zh: str,
    en: str,
    latitude: float,
    longitude: float,
    radius_km: float,
    *,
    ja: str | None = None,
    ko: str | None = None,
) -> HotspotArea:
    names: dict[Locale, str] = {"zh-TW": zh, "en": en}
    if ja:
        names["ja"] = ja
    if ko:
        names["ko"] = ko
    return HotspotArea(code, names, latitude, longitude, radius_km)


HOTSPOT_AREAS: dict[str, tuple[HotspotArea, ...]] = {
    "NRT": (
        _area("shinjuku", "新宿", "Shinjuku", 35.6938, 139.7034, 2.0, ja="新宿"),
        _area(
            "shibuya", "澀谷／原宿", "Shibuya & Harajuku", 35.6680, 139.7030, 2.2, ja="渋谷・原宿"
        ),
        _area("ikebukuro", "池袋", "Ikebukuro", 35.7295, 139.7109, 2.0, ja="池袋"),
        _area(
            "akihabara",
            "秋葉原／神田",
            "Akihabara & Kanda",
            35.6984,
            139.7731,
            1.3,
            ja="秋葉原・神田",
        ),
        _area("ueno", "上野／谷中", "Ueno & Yanaka", 35.7180, 139.7740, 1.8, ja="上野・谷中"),
        _area(
            "asakusa",
            "淺草／晴空塔",
            "Asakusa & Tokyo Skytree",
            35.7125,
            139.8020,
            2.0,
            ja="浅草・スカイツリー",
        ),
        _area(
            "marunouchi",
            "東京站／銀座／築地",
            "Tokyo Station, Ginza & Tsukiji",
            35.6760,
            139.7650,
            2.0,
            ja="東京駅・銀座・築地",
        ),
        _area(
            "roppongi",
            "六本木／東京鐵塔",
            "Roppongi & Tokyo Tower",
            35.6600,
            139.7380,
            1.7,
            ja="六本木・東京タワー",
        ),
        _area(
            "kagurazaka",
            "飯田橋／神樂坂／後樂園",
            "Iidabashi, Kagurazaka & Korakuen",
            35.7020,
            139.7400,
            1.4,
            ja="飯田橋・神楽坂・後楽園",
        ),
        _area(
            "nihonbashi",
            "日本橋／人形町",
            "Nihonbashi & Ningyocho",
            35.6850,
            139.7760,
            1.0,
            ja="日本橋・人形町",
        ),
        _area(
            "jimbocho",
            "神保町／御茶之水",
            "Jimbocho & Ochanomizu",
            35.6975,
            139.7590,
            0.9,
            ja="神保町・御茶ノ水",
        ),
        _area(
            "hamamatsucho",
            "濱松町／竹芝",
            "Hamamatsucho & Takeshiba",
            35.6560,
            139.7600,
            1.0,
            ja="浜松町・竹芝",
        ),
        _area("toyosu", "豐洲", "Toyosu", 35.6470, 139.7860, 1.3, ja="豊洲"),
        _area(
            "nakameguro",
            "中目黑／代官山",
            "Nakameguro & Daikanyama",
            35.6460,
            139.7000,
            1.2,
            ja="中目黒・代官山",
        ),
        _area(
            "shirokane",
            "目黑／白金台",
            "Meguro & Shirokanedai",
            35.6350,
            139.7180,
            1.5,
            ja="目黒・白金台",
        ),
        _area("nakano", "中野", "Nakano", 35.7070, 139.6650, 1.2, ja="中野"),
        _area(
            "komagome",
            "駒込／六義園",
            "Komagome & Rikugien",
            35.7330,
            139.7460,
            1.2,
            ja="駒込・六義園",
        ),
        _area("shimokitazawa", "下北澤", "Shimokitazawa", 35.6616, 139.6670, 1.0, ja="下北沢"),
        _area(
            "jiyugaoka",
            "自由之丘／等等力",
            "Jiyugaoka & Todoroki",
            35.6050,
            139.6600,
            2.0,
            ja="自由が丘・等々力",
        ),
        _area(
            "togoshi",
            "戶越／大井町",
            "Togoshi & Oimachi",
            35.6150,
            139.7250,
            2.0,
            ja="戸越・大井町",
        ),
        _area(
            "kichijoji",
            "吉祥寺／三鷹",
            "Kichijoji & Mitaka",
            35.7000,
            139.5760,
            1.6,
            ja="吉祥寺・三鷹",
        ),
        _area(
            "kasai",
            "葛西臨海公園",
            "Kasai Rinkai Park",
            35.6420,
            139.8620,
            1.5,
            ja="葛西臨海公園",
        ),
        _area(
            "shibamata",
            "葛飾／柴又",
            "Katsushika & Shibamata",
            35.7580,
            139.8780,
            2.5,
            ja="葛飾・柴又",
        ),
        _area(
            "koganei",
            "小金井／江戶東京建築園",
            "Koganei & Edo-Tokyo Open Air Museum",
            35.7158,
            139.5126,
            2.0,
            ja="小金井・江戸東京たてもの園",
        ),
        _area(
            "tachikawa",
            "立川／昭和紀念公園",
            "Tachikawa & Showa Memorial Park",
            35.7100,
            139.4000,
            4.0,
            ja="立川・昭和記念公園",
        ),
        _area(
            "tama",
            "多摩／稻城",
            "Tama & Inagi",
            35.6250,
            139.4700,
            6.0,
            ja="多摩・稲城",
        ),
        _area(
            "kiyosumi",
            "清澄白河／兩國",
            "Kiyosumi-Shirakawa & Ryogoku",
            35.6900,
            139.7950,
            1.8,
            ja="清澄白河・両国",
        ),
        _area("odaiba", "台場", "Odaiba", 35.6290, 139.7760, 2.5, ja="お台場"),
        _area(
            "maihama",
            "舞濱／東京迪士尼",
            "Maihama & Tokyo Disney Resort",
            35.6330,
            139.8830,
            3.0,
            ja="舞浜・ディズニーリゾート",
        ),
        _area(
            "takao",
            "高尾／八王子",
            "Mt. Takao & Hachioji",
            35.6253,
            139.2436,
            12.0,
            ja="高尾・八王子",
        ),
        _area("kawagoe", "川越", "Kawagoe", 35.9175, 139.4891, 8.0, ja="川越"),
        _area("kuramae", "藏前", "Kuramae", 35.7032, 139.7909, 0.8, ja="蔵前"),
        _area("okushibu", "奧澀谷", "Oku-Shibuya", 35.667, 139.689, 0.8, ja="奥渋谷"),
        _area(
            "urahara",
            "裏原宿／貓街",
            "Ura-Harajuku & Cat Street",
            35.67,
            139.705,
            0.7,
            ja="裏原宿・キャットストリート",
        ),
        _area("koenji", "高圓寺", "Koenji", 35.7037, 139.6528, 1.0, ja="高円寺"),
    ),
    "KIX": (
        _area(
            "namba",
            "難波／心齋橋",
            "Namba & Shinsaibashi",
            34.6690,
            135.5010,
            1.6,
            ja="難波・心斎橋",
        ),
        _area("umeda", "梅田", "Umeda", 34.7025, 135.4960, 1.6, ja="梅田"),
        _area(
            "tenma",
            "天滿／天神橋筋",
            "Tenma & Tenjinbashisuji",
            34.7060,
            135.5120,
            1.4,
            ja="天満・天神橋筋",
        ),
        _area("osaka-castle", "大阪城", "Osaka Castle", 34.6873, 135.5262, 1.6, ja="大阪城"),
        _area(
            "osaka-bay",
            "天保山／環球影城",
            "Osaka Bay (Tempozan & USJ)",
            34.6560,
            135.4320,
            1.6,
            ja="天保山・ユニバーサル",
        ),
        _area("sakai", "堺", "Sakai", 34.5730, 135.4830, 4.0, ja="堺"),
        _area("kyoto-station", "京都站", "Kyoto Station", 34.9858, 135.7588, 1.2, ja="京都駅"),
        _area(
            "kawaramachi",
            "四條河原町／烏丸",
            "Shijo Kawaramachi & Karasuma",
            35.0040,
            135.7680,
            1.3,
            ja="四条河原町・烏丸",
        ),
        _area(
            "higashiyama",
            "祇園／東山",
            "Gion & Higashiyama",
            35.0000,
            135.7790,
            1.8,
            ja="祇園・東山",
        ),
        _area(
            "nijo",
            "二條城／京都御所",
            "Nijo Castle & Imperial Palace",
            35.0180,
            135.7500,
            1.6,
            ja="二条城・京都御所",
        ),
        _area(
            "kinkakuji",
            "金閣寺／北野",
            "Kinkaku-ji & Kitano",
            35.0350,
            135.7330,
            2.0,
            ja="金閣寺・北野",
        ),
        _area("arashiyama", "嵐山", "Arashiyama", 35.0150, 135.6750, 2.5, ja="嵐山"),
        _area("fushimi", "伏見", "Fushimi", 34.9650, 135.7700, 2.5, ja="伏見"),
        _area("kurama", "鞍馬／貴船", "Kurama & Kibune", 35.1181, 135.7707, 5.0, ja="鞍馬・貴船"),
        _area("uji", "宇治", "Uji", 34.8900, 135.8080, 4.0, ja="宇治"),
        _area("nara", "奈良", "Nara", 34.6850, 135.8300, 5.0, ja="奈良"),
        _area("nakazakicho", "中崎町", "Nakazakicho", 34.7069, 135.5052, 0.6, ja="中崎町"),
        _area("horie", "南堀江", "Minami-Horie", 34.6727, 135.4929, 0.8, ja="南堀江"),
        _area("nakatsu", "中津", "Nakatsu", 34.7097, 135.493, 0.6, ja="中津"),
        _area("nishijin", "西陣", "Nishijin", 35.0297, 135.7519, 1.4, ja="西陣"),
        # 五条楽園 sits between Kawaramachi-dori and the Kamo river; the subway
        # station coordinate first used here is Karasuma-Gojo, 800 m west of it.
        _area("gojo", "河原町五條", "Kawaramachi-Gojo", 34.9943, 135.7656, 0.7, ja="五条楽園"),
        _area("ichijoji", "一乘寺", "Ichijoji", 35.0443, 135.7875, 1.0, ja="一乗寺"),
    ),
    "FUK": (
        _area("hakata", "博多站", "Hakata Station", 33.5900, 130.4200, 1.2, ja="博多駅"),
        _area("nakasu", "中洲／川端", "Nakasu & Kawabata", 33.5930, 130.4080, 0.9, ja="中洲・川端"),
        _area("tenjin", "天神／薬院", "Tenjin & Yakuin", 33.5890, 130.4000, 1.3, ja="天神・薬院"),
        _area(
            "ohori",
            "大濠公園／舞鶴",
            "Ohori Park & Maizuru",
            33.5860,
            130.3780,
            1.4,
            ja="大濠公園・舞鶴",
        ),
        _area(
            "ropponmatsu",
            "六本松／城南",
            "Ropponmatsu & Jonan",
            33.5720,
            130.3800,
            1.6,
            ja="六本松・城南",
        ),
        _area(
            "momochi", "百道／西新", "Momochi & Nishijin", 33.5920, 130.3530, 1.6, ja="百道・西新"
        ),
        _area(
            "uminonakamichi",
            "海之中道／志賀島",
            "Uminonakamichi & Shikanoshima",
            33.6592,
            130.3535,
            4.0,
            ja="海の中道・志賀島",
        ),
        _area("dazaifu", "太宰府", "Dazaifu", 33.5214, 130.5350, 4.0, ja="太宰府"),
        _area("itoshima", "糸島", "Itoshima", 33.6000, 130.2000, 12.0, ja="糸島"),
        _area("yanagawa", "柳川", "Yanagawa", 33.1631, 130.4058, 8.0, ja="柳川"),
        _area("daimyo", "大名／今泉", "Daimyo & Imaizumi", 33.5875, 130.398, 0.6, ja="大名・今泉"),
        _area("shirogane", "白金／高砂", "Shirogane", 33.5788, 130.4085, 0.7, ja="白金・高砂"),
    ),
    "CTS": (
        _area(
            "odori",
            "札幌站／大通",
            "Sapporo Station & Odori",
            43.0640,
            141.3520,
            1.8,
            ja="札幌駅・大通",
        ),
        _area(
            "susukino",
            "薄野／中島公園",
            "Susukino & Nakajima Park",
            43.0510,
            141.3540,
            1.2,
            ja="すすきの・中島公園",
        ),
        _area(
            "maruyama",
            "圓山／宮之森",
            "Maruyama & Miyanomori",
            43.0530,
            141.3160,
            1.6,
            ja="円山・宮の森",
        ),
        _area(
            "moiwa",
            "藻岩山／伏見",
            "Mt. Moiwa & Fushimi",
            43.0300,
            141.3250,
            2.2,
            ja="藻岩山・伏見",
        ),
        _area(
            "miyanosawa",
            "宮之澤／白色戀人公園",
            "Miyanosawa & Shiroi Koibito Park",
            43.0886,
            141.2717,
            2.0,
            ja="宮の沢・白い恋人パーク",
        ),
        _area(
            "moerenuma",
            "莫埃來沼公園／東區",
            "Moerenuma Park & Higashi Ward",
            43.1245,
            141.4299,
            3.0,
            ja="モエレ沼公園・東区",
        ),
        _area(
            "atsubetsu",
            "厚別／開拓村",
            "Atsubetsu & Historical Village",
            43.0482,
            141.4970,
            3.0,
            ja="厚別・開拓の村",
        ),
        _area(
            "makomanai",
            "真駒內／藝術之森",
            "Makomanai & Sapporo Art Park",
            42.9339,
            141.3372,
            3.0,
            ja="真駒内・芸術の森",
        ),
        _area("jozankei", "定山溪", "Jozankei", 42.9653, 141.1625, 6.0, ja="定山渓"),
        _area("otaru", "小樽", "Otaru", 43.1950, 141.0000, 6.0, ja="小樽"),
        _area(
            "soseigawa", "創成川東", "Soseigawa East", 43.0613, 141.3605, 0.7, ja="創成川イースト"
        ),
        _area("tanukikoji", "狸小路", "Tanukikoji", 43.0583, 141.3546, 0.5, ja="狸小路"),
    ),
    "OKA": (
        _area(
            "naha",
            "那霸市區／國際通",
            "Naha & Kokusai-dori",
            26.2150,
            127.6850,
            2.2,
            ja="那覇市街・国際通り",
        ),
        _area(
            "shintoshin",
            "那霸新都心",
            "Naha Shintoshin (Omoromachi)",
            26.2270,
            127.6950,
            1.2,
            ja="那覇新都心・おもろまち",
        ),
        _area("shuri", "首里", "Shuri", 26.2175, 127.7180, 1.5, ja="首里"),
        _area(
            "itoman",
            "糸滿／豐見城",
            "Itoman & Tomigusuku",
            26.1300,
            127.6700,
            6.0,
            ja="糸満・豊見城",
        ),
        _area(
            "nanjo",
            "南城／齋場御嶽",
            "Nanjo & Sefa-utaki",
            26.1650,
            127.8100,
            6.0,
            ja="南城・斎場御嶽",
        ),
        _area(
            "chatan",
            "北谷／美國村",
            "Chatan & American Village",
            26.3160,
            127.7560,
            3.0,
            ja="北谷・アメリカンビレッジ",
        ),
        _area(
            "nakagusuku",
            "中城／宜野灣",
            "Nakagusuku & Ginowan",
            26.2839,
            127.8014,
            4.0,
            ja="中城・宜野湾",
        ),
        _area("onna", "恩納／萬座毛", "Onna & Manzamo", 26.4900, 127.8400, 10.0, ja="恩納・万座毛"),
        _area(
            "motobu",
            "本部／美麗海水族館",
            "Motobu & Churaumi Aquarium",
            26.6900,
            127.8800,
            10.0,
            ja="本部・美ら海水族館",
        ),
        _area(
            "minatogawa",
            "港川外人住宅",
            "Minatogawa Stateside Town",
            # 港川2丁目 in Urasoe; the first cut sat 4 km southeast in the Shuri hills.
            26.2627,
            127.7152,
            0.6,
            ja="港川ステイツサイドタウン",
        ),
        _area("ukishima", "浮島通", "Ukishima Street", 26.2158, 127.6854, 0.4, ja="浮島通り"),
    ),
    "NGO": (
        _area(
            "nagoya-station",
            "名古屋站／四間道",
            "Nagoya Station & Shikemichi",
            35.1720,
            136.8860,
            1.3,
            ja="名古屋駅・四間道",
        ),
        _area("sakae", "榮／伏見", "Sakae & Fushimi", 35.1690, 136.9060, 1.2, ja="栄・伏見"),
        _area("osu", "大須", "Osu", 35.1590, 136.9010, 0.9, ja="大須"),
        _area("nagoya-castle", "名古屋城", "Nagoya Castle", 35.1856, 136.8986, 1.2, ja="名古屋城"),
        _area(
            "shirakabe",
            "白壁／德川園",
            "Shirakabe & Tokugawa Garden",
            35.1820,
            136.9260,
            1.4,
            ja="白壁・徳川園",
        ),
        _area("atsuta", "熱田／金山", "Atsuta & Kanayama", 35.1350, 136.9060, 1.8, ja="熱田・金山"),
        _area(
            "nagoya-port",
            "名古屋港／金城埠頭",
            "Port of Nagoya & Kinjo Pier",
            35.0700,
            136.8650,
            3.5,
            ja="名古屋港・金城ふ頭",
        ),
        _area("tokoname", "常滑", "Tokoname", 35.0015, 137.0866, 6.0, ja="常滑"),
        _area("inuyama", "犬山", "Inuyama", 35.3879, 136.9423, 6.0, ja="犬山"),
        _area("kakuozan", "覺王山", "Kakuozan", 35.1665, 136.9531, 0.8, ja="覚王山"),
    ),
    "ICN": (
        _area(
            "jongno",
            "景福宮／北村／仁寺洞",
            "Gyeongbokgung, Bukchon & Insadong",
            37.5800,
            126.9840,
            1.4,
            ko="경복궁·북촌·인사동",
        ),
        _area(
            "myeongdong",
            "明洞／南山",
            "Myeongdong & Namsan",
            37.5600,
            126.9860,
            1.4,
            ko="명동·남산",
        ),
        _area(
            "dongdaemun",
            "東大門／廣藏市場",
            "Dongdaemun & Gwangjang Market",
            37.5690,
            127.0050,
            1.3,
            ko="동대문·광장시장",
        ),
        _area(
            "yongsan", "龍山／梨泰院", "Yongsan & Itaewon", 37.5350, 126.9900, 1.8, ko="용산·이태원"
        ),
        _area(
            "hongdae", "弘大／合井", "Hongdae & Hapjeong", 37.5530, 126.9200, 1.5, ko="홍대·합정"
        ),
        _area(
            "yeouido",
            "汝矣島／仙遊島",
            "Yeouido & Seonyudo",
            37.5350,
            126.9100,
            2.2,
            ko="여의도·선유도",
        ),
        _area("sangam", "上岩／數位媒體城", "Sangam & DMC", 37.5750, 126.8950, 2.0, ko="상암·DMC"),
        _area("gangnam", "江南／COEX", "Gangnam & COEX", 37.5100, 127.0500, 2.5, ko="강남·코엑스"),
        _area(
            "jamsil",
            "蠶室／樂天世界",
            "Jamsil & Lotte World",
            37.5130,
            127.1000,
            2.0,
            ko="잠실·롯데월드",
        ),
        _area(
            "namhansanseong", "南漢山城", "Namhansanseong", 37.4780, 127.1842, 5.0, ko="남한산성"
        ),
        _area("suwon", "水原華城", "Suwon Hwaseong", 37.2807, 127.0102, 6.0, ko="수원 화성"),
        _area("seongsu", "聖水洞", "Seongsu-dong", 37.543, 127.048, 1.3, ko="성수동"),
        _area("hannam", "漢南洞", "Hannam-dong", 37.535, 127.001, 0.8, ko="한남동"),
        _area("euljiro", "乙支路", "Euljiro", 37.5664, 126.991, 0.7, ko="을지로"),
        _area("yeonnam", "延南洞", "Yeonnam-dong", 37.5625, 126.9255, 0.6, ko="연남동"),
        _area("yongnidan", "龍理團街", "Yongnidan-gil", 37.532, 126.972, 0.6, ko="용리단길"),
        _area("sindang", "新堂洞", "Sindang-dong", 37.566, 127.02, 0.7, ko="신당동"),
    ),
    "PUS": (
        _area(
            "nampo",
            "南浦洞／札嘎其",
            "Nampo-dong & Jagalchi",
            35.0990,
            129.0300,
            1.4,
            ko="남포동·자갈치",
        ),
        _area(
            "gamcheon",
            "甘川文化村／松島",
            "Gamcheon Culture Village & Songdo",
            35.0850,
            129.0130,
            1.8,
            ko="감천문화마을·송도",
        ),
        _area(
            "yeongdo",
            "影島／太宗臺",
            "Yeongdo & Taejongdae",
            35.0700,
            129.0700,
            3.0,
            ko="영도·태종대",
        ),
        _area("seomyeon", "西面", "Seomyeon", 35.1570, 129.0590, 1.4, ko="서면"),
        _area(
            "dongnae",
            "東萊／溫泉場",
            "Dongnae & Oncheonjang",
            35.2000,
            129.0950,
            3.0,
            ko="동래·온천장",
        ),
        _area("gwangalli", "廣安里", "Gwangalli", 35.1530, 129.1180, 1.8, ko="광안리"),
        _area(
            "oryukdo",
            "五六島／二妓臺",
            "Oryukdo & Igidae",
            35.0980,
            129.1200,
            2.5,
            ko="오륙도·이기대",
        ),
        _area("haeundae", "海雲台", "Haeundae", 35.1600, 129.1620, 2.0, ko="해운대"),
        _area(
            "gijang",
            "機張／海東龍宮寺",
            "Gijang & Haedong Yonggungsa",
            35.1883,
            129.2233,
            6.0,
            ko="기장·해동용궁사",
        ),
        _area(
            "tongdosa",
            "梁山／通度寺",
            "Yangsan & Tongdosa",
            35.4881,
            129.0647,
            6.0,
            ko="양산·통도사",
        ),
        _area(
            "jeonpo", "田浦咖啡街", "Jeonpo Cafe Street", 35.155, 129.063, 0.5, ko="전포카페거리"
        ),
        _area("bongnae", "影島蓬萊洞", "Bongnae-dong", 35.0913, 129.0357, 0.7, ko="봉래동"),
        _area("haeridan", "海理團街", "Haeridan-gil", 35.166, 129.159, 0.5, ko="해리단길"),
    ),
    "CJU": (
        _area(
            "jeju-city",
            "濟州市區／東門市場",
            "Jeju City & Dongmun Market",
            33.4950,
            126.5200,
            7.0,
            ko="제주시·동문시장",
        ),
        _area(
            "hallasan",
            "漢拏山／思連伊林蔭路",
            "Hallasan & Saryeoni Forest",
            33.3750,
            126.5200,
            9.0,
            ko="한라산·사려니숲길",
        ),
        _area("aewol", "涯月／翰林", "Aewol & Hallim", 33.4600, 126.3300, 8.0, ko="애월·한림"),
        _area(
            "andeok",
            "安德／大靜／雪綠茶",
            "Andeok, Daejeong & O'sulloc",
            33.2500,
            126.2800,
            11.0,
            ko="안덕·대정·오설록",
        ),
        _area("jungmun", "中文觀光區", "Jungmun Resort", 33.2450, 126.4150, 6.0, ko="중문관광단지"),
        _area("seogwipo", "西歸浦", "Seogwipo", 33.2500, 126.5650, 6.0, ko="서귀포"),
        _area("seongsan", "城山／牛島", "Seongsan & Udo", 33.4700, 126.9300, 7.0, ko="성산·우도"),
        _area(
            "gujwa",
            "舊左／萬丈窟／榧子林",
            "Gujwa, Manjanggul & Bijarim",
            33.5100,
            126.7900,
            6.0,
            ko="구좌·만장굴·비자림",
        ),
        _area(
            "seongeup",
            "城邑民俗村／表善",
            "Seongeup Folk Village & Pyoseon",
            33.3867,
            126.7853,
            6.0,
            ko="성읍민속마을·표선",
        ),
        _area("sehwa", "細花里", "Sehwa", 33.5254, 126.8603, 1.2, ko="세화리"),
    ),
    "BKK": (
        _area("rattanakosin", "大皇宮／考山路", "Grand Palace & Khao San", 13.7530, 100.4950, 1.6),
        _area("thonburi", "吞武里／鄭王廟", "Thonburi & Wat Arun", 13.7420, 100.4870, 1.1),
        _area("chinatown", "唐人街／耀華力", "Chinatown (Yaowarat)", 13.7400, 100.5110, 0.9),
        _area("siam", "暹羅／水門", "Siam & Pratunam", 13.7460, 100.5330, 1.3),
        _area("sukhumvit", "Asok／素坤逸", "Asok & Sukhumvit", 13.7380, 100.5600, 2.0),
        _area("silom", "是隆／倫披尼", "Silom & Lumphini", 13.7280, 100.5340, 1.5),
        _area("riverside", "河濱／Asiatique", "Riverside & Asiatique", 13.7150, 100.5100, 2.0),
        _area("chatuchak", "恰圖恰／阿里", "Chatuchak & Ari", 13.8000, 100.5500, 2.5),
        _area("bang-kachao", "邦喀昭", "Bang Kachao", 13.6807, 100.5663, 3.0),
        _area(
            "samut-prakan",
            "北欖／三頭象博物館",
            "Samut Prakan & Erawan Museum",
            13.6283,
            100.5889,
            6.0,
        ),
        _area("ko-kret", "閣格雷島／暖武里", "Ko Kret & Nonthaburi", 13.9069, 100.4733, 5.0),
        _area("song-wat", "嵩越路", "Song Wat", 13.7393, 100.5038, 0.5),
        _area("talat-noi", "噠叻仔", "Talat Noi", 13.7348, 100.5131, 0.5),
        _area(
            "charoenkrung", "石龍軍創意區", "Charoenkrung Creative District", 13.724, 100.515, 1.0
        ),
        _area("ekkamai", "伊卡邁", "Ekkamai", 13.73, 100.587, 1.0),
    ),
    "CNX": (
        _area("old-city", "古城", "Old City", 18.7880, 98.9870, 1.1),
        _area(
            "night-bazaar", "夜市／湄平河畔", "Night Bazaar & Ping Riverside", 18.7880, 99.0010, 0.9
        ),
        _area("nimman", "尼曼／清邁大學／悟孟寺", "Nimman, CMU & Wat Umong", 18.7950, 98.9620, 2.4),
        _area("doi-suthep", "素帖山", "Doi Suthep", 18.8050, 98.9216, 4.0),
        _area(
            "hang-dong", "杭東／皇家公園", "Hang Dong & Royal Park Rajapruek", 18.7518, 98.9230, 4.0
        ),
        _area("wiang-kum-kam", "魏攻甘／沙拉碧", "Wiang Kum Kam & Saraphi", 18.7541, 98.9956, 3.0),
        _area("mae-kampong", "湄甘蓬", "Mae Kampong", 18.8655, 99.3510, 8.0),
        _area("doi-inthanon", "茵他儂山", "Doi Inthanon", 18.5922, 98.4867, 15.0),
        _area("lamphun", "南奔", "Lamphun", 18.5774, 99.0082, 8.0),
        _area("chang-moi", "昌莫路", "Chang Moi", 18.7906, 99.0003, 0.5),
        _area("san-pa-khoi", "山巴闊", "San Pa Khoi", 18.786, 99.012, 0.6),
    ),
    "HKT": (
        _area("old-town", "普吉老城", "Phuket Old Town", 7.8850, 98.3880, 2.0),
        _area("patong", "芭東", "Patong", 7.8950, 98.2960, 2.5),
        _area("karon", "卡隆", "Karon", 7.8500, 98.2950, 2.0),
        _area("kata", "卡塔", "Kata", 7.8180, 98.3000, 2.0),
        _area("chalong", "查龍／大佛", "Chalong & Big Buddha", 7.8400, 98.3250, 2.5),
        _area("rawai", "拉威／神仙半島", "Rawai & Promthep Cape", 7.7700, 98.3200, 3.5),
        _area(
            "coral-island", "珊瑚島／離島", "Coral Island & Nearby Islands", 7.7436, 98.3725, 5.0
        ),
        _area(
            "thalang",
            "他朗／斯里納斯國家公園",
            "Thalang & Sirinat National Park",
            8.0500,
            98.3200,
            8.0,
        ),
        _area("ko-yao", "攀牙灣／瑤艾島", "Phang Nga Bay & Ko Yao", 8.0022, 98.5689, 12.0),
    ),
    "KBV": (
        _area("krabi-town", "喀比鎮", "Krabi Town", 8.0620, 98.9170, 2.5),
        _area("ao-nang", "奧南", "Ao Nang", 8.0400, 98.8150, 2.5),
        _area("railay", "萊雷", "Railay", 8.0106, 98.8394, 1.8),
        _area("four-islands", "波達島／四島", "Poda Island & Four Islands", 7.9714, 98.8086, 3.0),
        _area("tiger-cave", "虎窟寺", "Tiger Cave Temple", 8.1240, 98.9252, 3.0),
        _area("phanom-bencha", "帕儂賓札國家公園", "Khao Phanom Bencha", 8.2419, 98.9153, 6.0),
        _area("phi-phi", "皮皮島", "Phi Phi Islands", 7.7200, 98.7700, 8.0),
        _area("lanta", "蘭塔島", "Ko Lanta", 7.5500, 99.0800, 15.0),
        _area("ko-mook", "董里離島／翡翠洞", "Trang Islands & Emerald Cave", 7.3700, 99.2800, 10.0),
    ),
    "TPE": (
        _area("ximending", "西門町／萬華", "Ximending & Wanhua", 25.0400, 121.5040, 1.2),
        _area(
            "taipei-station",
            "台北車站／中正紀念堂",
            "Taipei Main Station & CKS Memorial",
            25.0420,
            121.5180,
            1.2,
        ),
        _area("dadaocheng", "大稻埕／迪化街", "Dadaocheng & Dihua Street", 25.0600, 121.5110, 1.2),
        _area("zhongshan", "中山／林安泰古厝", "Zhongshan & Lin An Tai", 25.0630, 121.5300, 1.5),
        _area("xinyi", "信義區／台北101", "Xinyi & Taipei 101", 25.0350, 121.5650, 1.5),
        _area(
            "songshan", "松山／饒河夜市", "Songshan & Raohe Night Market", 25.0500, 121.5720, 1.2
        ),
        _area("gongguan", "公館／寶藏巖", "Gongguan & Treasure Hill", 25.0140, 121.5340, 1.3),
        _area("shilin", "士林／故宮", "Shilin & National Palace Museum", 25.0950, 121.5400, 2.5),
        _area("beitou", "北投", "Beitou", 25.1370, 121.5060, 2.5),
        _area("tamsui", "淡水", "Tamsui", 25.1700, 121.4400, 4.0),
        _area("muzha", "木柵／動物園", "Muzha & Taipei Zoo", 24.9950, 121.5842, 2.5),
        _area("sanxia", "三峽／鶯歌", "Sanxia & Yingge", 24.9330, 121.3694, 6.0),
        _area("pinglin", "坪林", "Pinglin", 24.9344, 121.7130, 6.0),
        _area("chifeng", "赤峰街", "Chifeng Street", 25.053, 121.5205, 0.4),
        _area(
            "minsheng",
            "富錦街／民生社區",
            "Fujin Street & Minsheng Community",
            25.0603,
            121.5541,
            0.9,
        ),
        _area("dongqu", "東區巷弄", "Taipei East Village", 25.0417, 121.5514, 0.7),
    ),
    "SIN": (
        _area("marina-bay", "濱海灣", "Marina Bay", 1.2850, 103.8600, 1.2),
        _area("civic", "市政區／克拉碼頭", "Civic District & Clarke Quay", 1.2910, 103.8480, 0.9),
        _area("chinatown", "牛車水／中峇魯", "Chinatown & Tiong Bahru", 1.2830, 103.8380, 1.2),
        _area("orchard", "烏節路", "Orchard Road", 1.3040, 103.8320, 1.2),
        _area(
            "bugis",
            "武吉士／甘榜格南／小印度",
            "Bugis, Kampong Glam & Little India",
            1.3050,
            103.8580,
            1.2,
        ),
        _area("sentosa", "聖淘沙／港灣", "Sentosa & HarbourFront", 1.2550, 103.8250, 2.0),
        _area(
            "southern-ridges",
            "亞歷山大／南部山脊",
            "Alexandra & Southern Ridges",
            1.2790,
            103.8050,
            1.5,
        ),
        _area(
            "botanic", "植物園／荷蘭村", "Botanic Gardens & Holland Village", 1.3130, 103.8150, 1.5
        ),
        _area("macritchie", "麥里芝／武吉布朗", "MacRitchie & Bukit Brown", 1.3400, 103.8250, 2.5),
        _area("east-coast", "東海岸／加東", "East Coast & Katong", 1.3050, 103.9050, 3.0),
        _area("mandai", "萬禮／動物園", "Mandai & Singapore Zoo", 1.4038, 103.7941, 3.0),
        _area("kranji", "克蘭芝", "Kranji", 1.4167, 103.7286, 4.0),
        _area("ubin", "烏敏島／樟宜", "Pulau Ubin & Changi", 1.4000, 103.9600, 5.0),
        _area("jalan-besar", "惹蘭勿剎", "Jalan Besar", 1.3086, 103.8577, 0.7),
        _area("keong-saik", "恭錫路", "Keong Saik", 1.2802, 103.8416, 0.4),
    ),
    "HKG": (
        _area("central", "中環／上環", "Central & Sheung Wan", 22.2830, 114.1560, 1.1),
        _area("peak", "太平山", "Victoria Peak", 22.2756, 114.1439, 1.2),
        _area("wan-chai", "灣仔／銅鑼灣", "Wan Chai & Causeway Bay", 22.2780, 114.1780, 1.3),
        _area("southside", "南區／海洋公園", "Southside & Ocean Park", 22.2470, 114.1750, 2.5),
        _area(
            "tsim-sha-tsui",
            "尖沙咀／西九龍",
            "Tsim Sha Tsui & West Kowloon",
            22.2990,
            114.1660,
            1.4,
        ),
        _area("mong-kok", "旺角／油麻地", "Mong Kok & Yau Ma Tei", 22.3110, 114.1705, 1.2),
        _area(
            "kowloon-city",
            "九龍城／寨城公園",
            "Kowloon City & Walled City Park",
            22.3319,
            114.1900,
            1.5,
        ),
        _area("sai-kung", "西貢", "Sai Kung", 22.3810, 114.2730, 6.0),
        _area("lantau", "大嶼山／天壇大佛", "Lantau & Big Buddha", 22.2541, 113.9051, 8.0),
        _area("disneyland", "迪士尼／欣澳", "Disneyland & Sunny Bay", 22.3133, 114.0433, 3.0),
        _area("kam-tin", "元朗／吉慶圍", "Yuen Long & Kat Hing Wai", 22.4397, 114.0640, 5.0),
        _area(
            "lai-chi-wo",
            "新界東北／荔枝窩",
            "Northeast New Territories & Lai Chi Wo",
            22.5270,
            114.2590,
            8.0,
        ),
        _area(
            "sham-shui-po", "大南街／深水埗", "Tai Nam Street, Sham Shui Po", 22.3271, 114.1634, 0.7
        ),
        _area("wong-chuk-hang", "黃竹坑", "Wong Chuk Hang", 22.2479, 114.1676, 0.7),
        _area("poho", "太平山街 PoHo", "PoHo, Tai Ping Shan Street", 22.2837, 114.1477, 0.4),
        _area("tai-hang", "大坑", "Tai Hang", 22.2779, 114.1919, 0.5),
        _area("star-street", "星街小區", "Star Street Precinct", 22.2748, 114.1693, 0.4),
    ),
    "HAN": (
        _area(
            "old-quarter", "老城區／還劍湖", "Old Quarter & Hoan Kiem Lake", 21.0350, 105.8520, 1.6
        ),
        _area(
            "french-quarter",
            "法國區／歌劇院",
            "French Quarter & Opera House",
            21.0220,
            105.8560,
            1.0,
        ),
        _area(
            "ba-dinh", "巴亭／胡志明陵", "Ba Dinh & Ho Chi Minh Mausoleum", 21.0370, 105.8360, 1.15
        ),
        _area("west-lake", "西湖／鎮國寺", "West Lake & Tran Quoc Pagoda", 21.0600, 105.8280, 2.5),
        _area(
            "cau-giay", "紙橋／民族學博物館", "Cau Giay & Ethnology Museum", 21.0406, 105.7987, 2.0
        ),
        _area("bat-trang", "鉢場陶瓷村", "Bat Trang Pottery Village", 20.9833, 105.9167, 4.0),
        _area("duong-lam", "唐林古村／山西", "Duong Lam & Son Tay", 21.1544, 105.4739, 8.0),
        _area("quang-an", "廣安街", "Quang An", 21.0637, 105.8265, 1.0),
    ),
    "SGN": (
        _area(
            "district-1",
            "第一郡／濱城市場",
            "District 1 & Ben Thanh Market",
            10.7760,
            106.7000,
            1.3,
        ),
        _area("district-3", "第三郡", "District 3", 10.7880, 106.6900, 1.4),
        _area("cho-lon", "堤岸／第五郡", "Cho Lon (District 5)", 10.7520, 106.6550, 2.0),
        _area("binh-thanh", "平盛／Lăng Ông", "Binh Thanh & Lang Ong", 10.8030, 106.6980, 1.5),
        _area("go-vap", "富潤／嘉定公園", "Phu Nhuan & Gia Dinh Park", 10.8123, 106.6751, 2.0),
        _area("thao-dien", "草田／第二郡", "Thao Dien (District 2)", 10.8050, 106.7330, 2.5),
        _area("cu-chi", "古芝地道", "Cu Chi Tunnels", 11.0610, 106.5260, 10.0),
        _area("can-gio", "芹椰紅樹林", "Can Gio Mangroves", 10.3100, 106.7400, 20.0),
        _area("nguyen-thai-binh", "阮太平街區", "Nguyen Thai Binh", 10.7688, 106.6998, 0.4),
    ),
    "DAD": (
        _area("han-river", "漢江／市中心", "Han River & City Centre", 16.0680, 108.2200, 1.6),
        _area("my-khe", "美溪海灘", "My Khe Beach", 16.0600, 108.2450, 1.8),
        _area("son-tra", "山茶半島", "Son Tra Peninsula", 16.1197, 108.2868, 4.0),
        _area(
            "marble-mountains",
            "五行山／非水灘",
            "Marble Mountains & Non Nuoc",
            16.0000,
            108.2600,
            3.0,
        ),
        _area("ba-na", "巴拿山／佛手金橋", "Ba Na Hills & Golden Bridge", 15.9956, 107.9942, 6.0),
        _area("hai-van", "海雲關", "Hai Van Pass", 16.1875, 108.1308, 6.0),
        _area("hoi-an", "會安古城", "Hoi An Ancient Town", 15.8780, 108.3240, 5.0),
        _area("my-son", "美山聖地", "My Son Sanctuary", 15.7667, 108.1167, 8.0),
        _area("dong-duong", "東陽佛院／升平", "Dong Duong & Thang Binh", 15.7070, 108.2249, 6.0),
        _area("an-thuong", "安上街區", "An Thuong", 16.0499, 108.2453, 0.6),
    ),
    "RMQ": (
        _area("central", "中區／舊城", "Central District & Old Town", 24.1400, 120.6780, 1.0),
        _area("yizhong", "一中商圈／臺中公園", "Yizhong & Taichung Park", 24.1470, 120.6850, 0.9),
        _area(
            "caowudao",
            "草悟道／科博館",
            "Calligraphy Greenway & Science Museum",
            24.1550,
            120.6650,
            1.2,
        ),
        _area("qiqi", "七期／歌劇院", "Qiqi & National Taichung Theater", 24.1640, 120.6400, 1.3),
        _area("fengjia", "逢甲", "Fengjia", 24.1780, 120.6460, 1.2),
        _area(
            "rainbow-village", "南屯／彩虹眷村", "Nantun & Rainbow Village", 24.1333, 120.6094, 2.0
        ),
        _area("wufeng", "霧峰", "Wufeng", 24.0642, 120.7010, 5.0),
        _area("gaomei", "高美濕地／清水", "Gaomei Wetlands & Qingshui", 24.3121, 120.5500, 6.0),
        _area("shenji", "審計新村", "Shenji New Village", 24.1379, 120.6633, 0.3),
    ),
    "KHH": (
        _area("yancheng", "鹽埕／駁二", "Yancheng & Pier-2", 22.6220, 120.2850, 1.0),
        _area("sizihwan", "西子灣／哈瑪星", "Sizihwan & Hamasen", 22.6250, 120.2660, 1.2),
        _area("cijin", "旗津", "Cijin", 22.6100, 120.2700, 1.5),
        _area("qianjin", "前金／六合夜市", "Qianjin & Liuhe Night Market", 22.6330, 120.3000, 1.0),
        _area(
            "sanmin", "三民／三鳳中街", "Sanmin & Sanfeng Central Street", 22.6380, 120.2930, 0.8
        ),
        _area("shoushan", "壽山／美術館", "Shoushan & Fine Arts Museum", 22.6540, 120.2740, 2.0),
        _area("sanduo", "三多商圈／苓雅", "Sanduo & Lingya", 22.6130, 120.3040, 1.2),
        _area(
            "ruifeng",
            "巨蛋／瑞豐夜市",
            "Kaohsiung Arena & Ruifeng Night Market",
            22.6680,
            120.3020,
            1.2,
        ),
        _area("zuoying", "左營／蓮池潭", "Zuoying & Lotus Pond", 22.6850, 120.2970, 2.0),
        _area("weiwuying", "衛武營／鳳山", "Weiwuying & Fengshan", 22.6211, 120.3394, 2.0),
        _area("chengqing", "澄清湖", "Chengqing Lake", 22.6606, 120.3510, 3.0),
        _area("foguangshan", "佛光山／大樹", "Fo Guang Shan & Dashu", 22.7474, 120.4462, 6.0),
        _area("huangpu", "黃埔新村", "Huangpu New Village", 22.6247, 120.358, 0.5),
    ),
    "SDJ": (
        _area(
            "aobayama",
            "青葉山／仙台城",
            "Aobayama & Sendai Castle",
            38.2540,
            140.8590,
            1.0,
            ja="青葉山・仙台城",
        ),
        _area(
            "ichibancho",
            "一番町／定禪寺通",
            "Ichibancho & Jozenji-dori",
            38.2640,
            140.8680,
            1.0,
            ja="一番町・定禅寺通",
        ),
        _area(
            "sendai-station",
            "仙台站／榴岡",
            "Sendai Station & Tsutsujigaoka",
            38.2600,
            140.8850,
            1.4,
            ja="仙台駅・榴岡",
        ),
        _area(
            "kita-sendai",
            "北仙台／東照宮",
            "Kita-Sendai & Toshogu",
            38.2850,
            140.8700,
            1.9,
            ja="北仙台・東照宮",
        ),
        _area(
            "hachiman",
            "八幡／大崎八幡宮",
            "Hachiman & Osaki Hachimangu",
            38.2722,
            140.8450,
            1.0,
            ja="八幡・大崎八幡宮",
        ),
        _area("akiu", "秋保溫泉", "Akiu Onsen", 38.2749, 140.6029, 6.0, ja="秋保温泉"),
        _area("sakunami", "作並溫泉", "Sakunami Onsen", 38.3316, 140.6135, 5.0, ja="作並温泉"),
        _area("matsushima", "松島", "Matsushima", 38.3690, 141.0590, 6.0, ja="松島"),
    ),
    "KMQ": (
        _area(
            "kenrokuen",
            "兼六園／金澤城",
            "Kenrokuen & Kanazawa Castle",
            36.5620,
            136.6610,
            0.7,
            ja="兼六園・金沢城",
        ),
        _area(
            "korinbo",
            "香林坊／長町",
            "Korinbo & Nagamachi",
            36.5640,
            136.6520,
            0.6,
            ja="香林坊・長町",
        ),
        _area(
            "nishi-chaya",
            "西茶屋街／妙立寺",
            "Nishi Chaya & Myoryuji",
            36.5560,
            136.6490,
            0.6,
            ja="にし茶屋街・妙立寺",
        ),
        _area(
            "omicho",
            "近江町／金澤站",
            "Omicho Market & Kanazawa Station",
            36.5750,
            136.6540,
            0.9,
            ja="近江町・金沢駅",
        ),
        _area(
            "higashi-chaya", "東茶屋街", "Higashi Chaya", 36.5725, 136.6672, 0.6, ja="ひがし茶屋街"
        ),
        _area(
            "hakusan",
            "白山比咩神社",
            "Shirayama Hime Shrine",
            36.4349,
            136.6358,
            6.0,
            ja="白山比咩神社",
        ),
        _area(
            "natadera",
            "那谷寺／小松",
            "Natadera & Komatsu",
            36.3134,
            136.4204,
            8.0,
            ja="那谷寺・小松",
        ),
        _area(
            "tatemachi",
            "竪町／新竪町",
            "Tatemachi & Shin-Tatemachi",
            36.557,
            136.659,
            0.5,
            ja="竪町・新竪町",
        ),
    ),
    "HIJ": (
        _area(
            "peace-park",
            "和平公園／原爆圓頂",
            "Peace Memorial Park & Atomic Bomb Dome",
            34.3935,
            132.4530,
            0.55,
            ja="平和記念公園・原爆ドーム",
        ),
        _area(
            "hondori",
            "本通／八丁堀",
            "Hondori & Hatchobori",
            34.3925,
            132.4590,
            0.55,
            ja="本通・八丁堀",
        ),
        _area(
            "hiroshima-castle",
            "廣島城／縮景園",
            "Hiroshima Castle & Shukkeien",
            34.4015,
            132.4630,
            0.8,
            ja="広島城・縮景園",
        ),
        _area(
            "hiroshima-station", "廣島站", "Hiroshima Station", 34.3975, 132.4750, 0.8, ja="広島駅"
        ),
        _area("hijiyama", "比治山", "Hijiyama", 34.3850, 132.4730, 0.8, ja="比治山"),
        _area("mitaki", "三瀧寺", "Mitaki-dera", 34.4203, 132.4376, 1.5, ja="三瀧寺"),
        _area("miyajima", "宮島", "Miyajima", 34.2958, 132.3201, 4.0, ja="宮島"),
    ),
    "TAE": (
        _area(
            "dongseongno",
            "東城路／大邱站",
            "Dongseong-ro & Daegu Station",
            35.8690,
            128.5960,
            0.8,
            ko="동성로·대구역",
        ),
        _area(
            "banwoldang",
            "半月堂／桂山聖堂",
            "Banwoldang & Gyesan Cathedral",
            35.8670,
            128.5870,
            0.6,
            ko="반월당·계산성당",
        ),
        _area(
            "seomun",
            "西門市場／達城公園",
            "Seomun Market & Dalseong Park",
            35.8715,
            128.5790,
            0.8,
            ko="서문시장·달성공원",
        ),
        _area("suseong", "壽城池", "Suseong Lake", 35.8280, 128.6200, 1.5, ko="수성못"),
        _area(
            "daegu-museum",
            "國立大邱博物館／凡魚",
            "Daegu National Museum & Beomeo",
            35.8458,
            128.6380,
            1.5,
            ko="국립대구박물관·범어",
        ),
        _area("apsan", "前山公園", "Apsan Park", 35.8200, 128.5790, 2.0, ko="앞산공원"),
        _area(
            "duryu",
            "頭流公園／文化藝術會館",
            "Duryu Park & Daegu Arts Center",
            35.8524,
            128.5591,
            1.5,
            ko="두류공원·문화예술회관",
        ),
        _area(
            "arboretum", "大邱樹木園", "Daegu Arboretum", 35.7994, 128.5210, 2.5, ko="대구수목원"
        ),
        _area(
            "daegu-art-museum",
            "大邱美術館",
            "Daegu Art Museum",
            35.8271,
            128.6743,
            2.5,
            ko="대구미술관",
        ),
        _area(
            "bullo", "不老洞古墳群", "Bullo-dong Tumuli", 35.9153, 128.6442, 3.0, ko="불로동 고분군"
        ),
        _area(
            "palgongsan",
            "八公山／桐華寺",
            "Palgongsan & Donghwasa",
            36.0050,
            128.7020,
            6.0,
            ko="팔공산·동화사",
        ),
        _area("dongin", "東仁洞", "Dongin-dong", 35.871, 128.606, 0.4, ko="동인동"),
        _area("samdeok", "三德洞", "Samdeok-dong", 35.8672, 128.6053, 0.4, ko="삼덕동"),
        _area("bukseongro", "北城路", "Bukseong-ro", 35.8734, 128.5926, 0.4, ko="북성로"),
    ),
    "CEI": (
        _area(
            "city-centre",
            "市區／鐘樓／夜市",
            "City Centre, Clock Tower & Night Bazaar",
            19.9080,
            99.8300,
            1.5,
        ),
        _area("blue-temple", "藍廟／郭河畔", "Blue Temple & Kok Riverside", 19.9234, 99.8417, 1.5),
        _area("white-temple", "白龍寺", "White Temple (Wat Rong Khun)", 19.8242, 99.7633, 3.0),
        _area("baan-dam", "黑屋博物館／南邦", "Baan Dam Museum & Nang Lae", 19.9921, 99.8607, 3.0),
        _area("mae-salong", "美斯樂", "Doi Mae Salong", 20.1683, 99.6194, 8.0),
        _area("doi-tung", "董山／美塞", "Doi Tung & Mae Sai", 20.3900, 99.8700, 8.0),
        _area(
            "golden-triangle",
            "金三角／清盛",
            "Golden Triangle & Chiang Saen",
            20.3200,
            100.0800,
            8.0,
        ),
        _area("phu-chi-fa", "富智發", "Phu Chi Fa", 19.8500, 100.4542, 10.0),
    ),
    "DLI": (
        _area(
            "market", "大叻市場／春香湖", "Da Lat Market & Xuan Huong Lake", 11.9400, 108.4420, 1.2
        ),
        _area(
            "french-quarter",
            "舊法國區／保大宮",
            "Old French Quarter & Bao Dai Palace",
            11.9330,
            108.4300,
            1.0,
        ),
        _area(
            "flower-garden",
            "花園／Domaine de Marie",
            "Flower Garden & Domaine de Marie",
            11.9500,
            108.4400,
            1.3,
        ),
        _area(
            "ward-3",
            "第三坊／宮殿一號／林同博物館",
            "Ward 3, Dinh I & Lam Dong Museum",
            11.9420,
            108.4650,
            1.3,
        ),
        _area(
            "linh-phuoc", "靈福寺／茶園", "Linh Phuoc Pagoda & Tea Hills", 11.9443, 108.4995, 3.0
        ),
        _area(
            "tuyen-lam",
            "泉林湖／竹林禪院",
            "Tuyen Lam Lake & Truc Lam Monastery",
            11.8980,
            108.4350,
            2.5,
        ),
        _area("love-valley", "情人谷", "Valley of Love", 11.9808, 108.4504, 2.5),
    ),
    "TNN": (
        _area(
            "confucius", "孔廟／府中街", "Confucius Temple & Fuzhong Street", 22.9905, 120.2040, 0.6
        ),
        _area(
            "chihkan", "赤崁樓／神農街", "Chihkan Tower & Shennong Street", 22.9970, 120.2020, 0.6
        ),
        _area("anping", "安平", "Anping", 22.9990, 120.1620, 2.0),
        _area(
            "north-district",
            "北區／花園夜市",
            "North District & Garden Night Market",
            23.0100,
            120.2020,
            1.2,
        ),
        _area("chimei", "奇美博物館／仁德", "Chimei Museum & Rende", 22.9267, 120.2436, 3.0),
        _area("annan", "台史博／安南", "Museum of Taiwan History & Annan", 23.0583, 120.2351, 3.0),
        _area(
            "taijiang",
            "台江國家公園／七股",
            "Taijiang National Park & Qigu",
            23.0630,
            120.0550,
            8.0,
        ),
        _area("guanziling", "關子嶺溫泉", "Guanziling Hot Springs", 23.3333, 120.5000, 8.0),
        _area("zhengxing", "正興街／國華街", "Zhengxing & Guohua Street", 22.9963, 120.1985, 0.4),
    ),
    "GYE": (
        _area(
            "hwangnidan",
            "皇理團路／大陵苑",
            "Hwangnidan-gil & Daereungwon",
            35.8370,
            129.2120,
            0.9,
            ko="황리단길·대릉원",
        ),
        _area(
            "wolseong",
            "月城／校村／瞻星臺",
            "Wolseong, Gyochon & Cheomseongdae",
            35.8300,
            129.2230,
            1.0,
            ko="월성·교촌·첨성대",
        ),
        _area(
            "hwangnyongsa",
            "皇龍寺／芬皇寺",
            "Hwangnyongsa & Bunhwangsa",
            35.8390,
            129.2330,
            0.8,
            ko="황룡사·분황사",
        ),
        _area("bomun", "普門湖", "Bomun Lake", 35.8400, 129.2850, 2.5, ko="보문호"),
        _area(
            "bulguksa",
            "佛國寺／石窟庵",
            "Bulguksa & Seokguram",
            35.7920,
            129.3400,
            3.0,
            ko="불국사·석굴암",
        ),
        _area(
            "golgulsa", "骨窟寺／甘浦", "Golgulsa & Gampo", 35.8033, 129.4060, 4.0, ko="골굴사·감포"
        ),
        _area("namsan", "慶州南山", "Gyeongju Namsan", 35.7800, 129.2250, 3.0, ko="경주 남산"),
        _area("yangdong", "良洞村", "Yangdong Folk Village", 36.0011, 129.2533, 5.0, ko="양동마을"),
    ),
    "JEO": (
        _area(
            "hanok-village",
            "全州韓屋村",
            "Jeonju Hanok Village",
            35.8145,
            127.1530,
            0.9,
            ko="전주한옥마을",
        ),
        _area(
            "nambu-market",
            "南部市場／客理團路",
            "Nambu Market & Gaeksa-gil",
            35.8175,
            127.1430,
            0.8,
            ko="남부시장·객리단길",
        ),
        _area(
            "namgosanseong",
            "南固山城",
            "Namgosanseong Fortress",
            35.7964,
            127.1525,
            1.5,
            ko="남고산성",
        ),
        _area(
            "deokjin",
            "德津公園／全北大",
            "Deokjin Park & Jeonbuk National University",
            35.8478,
            127.1220,
            2.0,
            ko="덕진공원·전북대",
        ),
        _area(
            "jeonju-zoo",
            "全州動物園／松川",
            "Jeonju Zoo & Songcheon",
            35.8567,
            127.1447,
            1.5,
            ko="전주동물원·송천",
        ),
        _area(
            "hyoja",
            "全州歷史博物館／孝子洞",
            "Jeonju History Museum & Hyoja-dong",
            35.8330,
            127.0960,
            2.0,
            ko="전주역사박물관·효자동",
        ),
        _area(
            "moaksan",
            "母岳山／金山寺",
            "Moaksan & Geumsansa",
            35.7260,
            127.0700,
            5.0,
            ko="모악산·금산사",
        ),
        _area(
            "seohak",
            "棲鶴洞藝術村",
            "Seohak-dong Art Village",
            35.8078,
            127.15,
            0.6,
            ko="서학동예술마을",
        ),
        _area(
            "sinsigaji",
            "全州新市街",
            "Jeonju Sinsigaji",
            35.8158,
            127.1078,
            1.0,
            ko="전주 신시가지",
        ),
    ),
    "HUI": (
        _area("citadel", "皇城／京城", "Imperial City & Citadel", 16.4700, 107.5790, 0.9),
        _area(
            "dong-ba",
            "東巴市場／長前橋",
            "Dong Ba Market & Truong Tien Bridge",
            16.4710,
            107.5890,
            0.7,
        ),
        _area("south-bank", "香江南岸／新城區", "South Bank & New Town", 16.4590, 107.5930, 1.2),
        _area("thien-mu", "天姥寺／金龍", "Thien Mu Pagoda & Kim Long", 16.4536, 107.5448, 1.5),
        _area(
            "royal-tombs",
            "皇陵區（嗣德陵／啟定陵／明命陵）",
            "Royal Tombs (Tu Duc, Khai Dinh & Minh Mang)",
            16.4050,
            107.5750,
            5.0,
        ),
        _area(
            "thuan-an",
            "順安海灘／香江口",
            "Thuan An Beach & Perfume River Mouth",
            16.5500,
            107.6300,
            5.0,
        ),
        _area("tam-giang", "潭江潟湖", "Tam Giang Lagoon", 16.6319, 107.4719, 10.0),
        _area("bach-ma", "白馬國家公園", "Bach Ma National Park", 16.2000, 107.8667, 12.0),
        _area("pham-ngu-lao", "范五老步行街", "Pham Ngu Lao Walking Street", 16.47, 107.5946, 0.4),
    ),
    "YOK": (
        _area("minato-mirai", "港未來", "Minato Mirai", 35.4565, 139.6325, 1.0, ja="みなとみらい"),
        _area(
            "shinko",
            "新港／紅磚倉庫／大棧橋",
            "Shinko, Red Brick Warehouse & Osanbashi",
            35.4515,
            139.6450,
            0.8,
            ja="新港・赤レンガ倉庫・大さん橋",
        ),
        _area(
            "kannai",
            "關內／馬車道",
            "Kannai & Bashamichi",
            35.4460,
            139.6360,
            0.8,
            ja="関内・馬車道",
        ),
        _area(
            "chinatown",
            "中華街／元町／山下公園",
            "Chinatown, Motomachi & Yamashita Park",
            35.4430,
            139.6480,
            0.9,
            ja="中華街・元町・山下公園",
        ),
        _area(
            "noge", "野毛／櫻木町", "Noge & Sakuragicho", 35.4500, 139.6290, 0.6, ja="野毛・桜木町"
        ),
        _area(
            "yokohama-station",
            "橫濱站",
            "Yokohama Station",
            35.4658,
            139.6220,
            0.8,
            ja="横浜駅",
        ),
        _area(
            "yamate",
            "山手／本牧／三溪園",
            "Yamate, Honmoku & Sankeien",
            35.4250,
            139.6550,
            2.0,
            ja="山手・本牧・三渓園",
        ),
        _area("shin-yokohama", "新橫濱", "Shin-Yokohama", 35.5070, 139.6170, 1.5, ja="新横浜"),
        _area(
            "hakkeijima",
            "八景島／金澤文庫",
            "Hakkeijima & Kanazawa-Bunko",
            35.3420,
            139.6380,
            2.5,
            ja="八景島・金沢文庫",
        ),
        _area("tsurumi", "鶴見", "Tsurumi", 35.5090, 139.6780, 2.0, ja="鶴見"),
        _area(
            "koganecho",
            "黃金町／日之出町",
            "Koganecho",
            35.4398,
            139.6227,
            0.5,
            ja="黄金町・日ノ出町",
        ),
    ),
    "KMK": (
        _area(
            "kamakura-station",
            "鎌倉站／小町通／鶴岡八幡宮",
            "Kamakura Station, Komachi-dori & Tsurugaoka Hachimangu",
            35.3215,
            139.5525,
            0.8,
            ja="鎌倉駅・小町通り・鶴岡八幡宮",
        ),
        _area(
            "genjiyama",
            "源氏山／錢洗弁財天",
            "Genjiyama & Zeniarai Benten",
            35.3240,
            139.5435,
            0.7,
            ja="源氏山・銭洗弁財天",
        ),
        _area("hase", "長谷／大佛", "Hase & Great Buddha", 35.3160, 139.5350, 0.8, ja="長谷・大仏"),
        _area("kita-kamakura", "北鎌倉", "Kita-Kamakura", 35.3355, 139.5510, 0.9, ja="北鎌倉"),
        _area(
            "nikaido",
            "二階堂／金澤街道",
            "Nikaido & Kanazawa Kaido",
            35.3215,
            139.5700,
            1.2,
            ja="二階堂・金沢街道",
        ),
        _area(
            "inamuragasaki",
            "極樂寺／稻村崎",
            "Gokurakuji & Inamuragasaki",
            35.3050,
            139.5280,
            1.0,
            ja="極楽寺・稲村ヶ崎",
        ),
        _area(
            "yuigahama",
            "由比濱／材木座",
            "Yuigahama & Zaimokuza",
            35.3120,
            139.5460,
            0.8,
            ja="由比ヶ浜・材木座",
        ),
        _area(
            "enoshima",
            "江之島／腰越",
            "Enoshima & Koshigoe",
            35.3040,
            139.4880,
            2.0,
            ja="江の島・腰越",
        ),
        _area("zushi", "逗子／葉山", "Zushi & Hayama", 35.2950, 139.5800, 3.0, ja="逗子・葉山"),
    ),
}

AREAS_BY_CODE: dict[str, dict[str, HotspotArea]] = {
    city_code: {area.code: area for area in areas} for city_code, areas in HOTSPOT_AREAS.items()
}


def city_areas(city_code: str | None) -> tuple[HotspotArea, ...]:
    if not city_code:
        return ()
    return HOTSPOT_AREAS.get(city_code.upper(), ())


def area_by_code(city_code: str | None, code: str | None) -> HotspotArea | None:
    if not city_code or not code:
        return None
    return AREAS_BY_CODE.get(city_code.upper(), {}).get(code)


def resolve_area(
    city_code: str | None,
    latitude: float | Decimal | None,
    longitude: float | Decimal | None,
) -> HotspotArea | None:
    """Pick the area whose circle contains the point with the tightest fit."""

    if latitude is None or longitude is None:
        return None
    lat, lon = float(latitude), float(longitude)
    best: HotspotArea | None = None
    best_ratio = float("inf")
    for area in city_areas(city_code):
        distance = haversine_km(lat, lon, area.latitude, area.longitude)
        if distance > area.radius_km:
            continue
        ratio = distance / area.radius_km
        if ratio < best_ratio:
            best, best_ratio = area, ratio
    return best


def resolve_area_code(
    city_code: str | None,
    latitude: float | Decimal | None,
    longitude: float | Decimal | None,
) -> str | None:
    area = resolve_area(city_code, latitude, longitude)
    return area.code if area else None


# Simplified spellings for the area names written differently in the two scripts.
# A table rather than a field on all 393 entries: the catalog is curated in
# Traditional, most names are identical in both, and one list is what a reader
# checking the conversion actually wants to see. Produced by
# ``python -m app.cli fill-simplified-names --source areas`` and reviewed by hand.
SIMPLIFIED_AREA_NAMES: dict[str, str] = {
    "一中商圈／臺中公園": "一中商圈／台中公园",
    "一番町／定禪寺通": "一番町／定禅寺通",
    "七期／歌劇院": "七期／歌剧院",
    "三峽／鶯歌": "三峡／莺歌",
    "三民／三鳳中街": "三民／三凤中街",
    "三瀧寺": "三泷寺",
    "上岩／數位媒體城": "上岩／数位媒体城",
    "下北澤": "下北泽",
    "不老洞古墳群": "不老洞古坟群",
    "中區／舊城": "中区／旧城",
    "中城／宜野灣": "中城／宜野湾",
    "中文觀光區": "中文观光区",
    "中環／上環": "中环／上环",
    "中華街／元町／山下公園": "中华街／元町／山下公园",
    "九龍城／寨城公園": "九龙城／寨城公园",
    "二條城／京都御所": "二条城／京都御所",
    "二階堂／金澤街道": "二阶堂／金泽街道",
    "五六島／二妓臺": "五六岛／二妓台",
    "五行山／非水灘": "五行山／非水滩",
    "亞歷山大／南部山脊": "亚历山大／南部山脊",
    "他朗／斯里納斯國家公園": "他朗／斯里纳斯国家公园",
    "仙台站／榴岡": "仙台站／榴冈",
    "伊卡邁": "伊卡迈",
    "伏見": "伏见",
    "佛光山／大樹": "佛光山／大树",
    "佛國寺／石窟庵": "佛国寺／石窟庵",
    "作並溫泉": "作并温泉",
    "信義區／台北101": "信义区／台北101",
    "元朗／吉慶圍": "元朗／吉庆围",
    "克蘭芝": "克兰芝",
    "全州動物園／松川": "全州动物园／松川",
    "全州歷史博物館／孝子洞": "全州历史博物馆／孝子洞",
    "全州韓屋村": "全州韩屋村",
    "八公山／桐華寺": "八公山／桐华寺",
    "八幡／大崎八幡宮": "八幡／大崎八幡宫",
    "八景島／金澤文庫": "八景岛／金泽文库",
    "公館／寶藏巖": "公馆／宝藏岩",
    "六本木／東京鐵塔": "六本木／东京铁塔",
    "兼六園／金澤城": "兼六园／金泽城",
    "前山公園": "前山公园",
    "創成川東": "创成川东",
    "北仙台／東照宮": "北仙台／东照宫",
    "北區／花園夜市": "北区／花园夜市",
    "北欖／三頭象博物館": "北榄／三头象博物馆",
    "北谷／美國村": "北谷／美国村",
    "北鎌倉": "北镰仓",
    "半月堂／桂山聖堂": "半月堂／桂山圣堂",
    "南區／海洋公園": "南区／海洋公园",
    "南城／齋場御嶽": "南城／斋场御岳",
    "南漢山城": "南汉山城",
    "南部市場／客理團路": "南部市场／客理团路",
    "厚別／開拓村": "厚别／开拓村",
    "台北車站／中正紀念堂": "台北车站／中正纪念堂",
    "台場": "台场",
    "台江國家公園／七股": "台江国家公园／七股",
    "吉祥寺／三鷹": "吉祥寺／三鹰",
    "名古屋港／金城埠頭": "名古屋港／金城埠头",
    "名古屋站／四間道": "名古屋站／四间道",
    "吞武里／鄭王廟": "吞武里／郑王庙",
    "和平公園／原爆圓頂": "和平公园／原爆圆顶",
    "唐人街／耀華力": "唐人街／耀华力",
    "喀比鎮": "喀比镇",
    "噠叻仔": "哒叻仔",
    "四條河原町／烏丸": "四条河原町／乌丸",
    "國立大邱博物館／凡魚": "国立大邱博物馆／凡鱼",
    "圓山／宮之森": "圆山／宫之森",
    "城山／牛島": "城山／牛岛",
    "士林／故宮": "士林／故宫",
    "壽城池": "寿城池",
    "壽山／美術館": "寿山／美术馆",
    "大叻市場／春香湖": "大叻市场／春香湖",
    "大嶼山／天壇大佛": "大屿山／天坛大佛",
    "大濠公園／舞鶴": "大濠公园／舞鹤",
    "大皇宮／考山路": "大皇宫／考山路",
    "大邱樹木園": "大邱树木园",
    "大邱美術館": "大邱美术馆",
    "大須": "大须",
    "天保山／環球影城": "天保山／环球影城",
    "天姥寺／金龍": "天姥寺／金龙",
    "天滿／天神橋筋": "天满／天神桥筋",
    "天神／薬院": "天神／药院",
    "奇美博物館／仁德": "奇美博物馆／仁德",
    "奧南": "奥南",
    "奧澀谷": "奥涩谷",
    "孔廟／府中街": "孔庙／府中街",
    "安上街區": "安上街区",
    "安德／大靜／雪綠茶": "安德／大静／雪绿茶",
    "宮之澤／白色戀人公園": "宫之泽／白色恋人公园",
    "宮島": "宫岛",
    "富智發": "富智发",
    "富潤／嘉定公園": "富润／嘉定公园",
    "富錦街／民生社區": "富锦街／民生社区",
    "審計新村": "审计新村",
    "小金井／江戶東京建築園": "小金井／江户东京建筑园",
    "尖沙咀／西九龍": "尖沙咀／西九龙",
    "尼曼／清邁大學／悟孟寺": "尼曼／清迈大学／悟孟寺",
    "山巴闊": "山巴阔",
    "山手／本牧／三溪園": "山手／本牧／三溪园",
    "山茶半島": "山茶半岛",
    "嵐山": "岚山",
    "左營／蓮池潭": "左营／莲池潭",
    "巨蛋／瑞豐夜市": "巨蛋／瑞丰夜市",
    "巴拿山／佛手金橋": "巴拿山／佛手金桥",
    "市區／鐘樓／夜市": "市区／钟楼／夜市",
    "市政區／克拉碼頭": "市政区／克拉码头",
    "帕儂賓札國家公園": "帕侬宾札国家公园",
    "廣安街": "广安街",
    "廣安里": "广安里",
    "廣島城／縮景園": "广岛城／缩景园",
    "廣島站": "广岛站",
    "影島蓬萊洞": "影岛蓬莱洞",
    "影島／太宗臺": "影岛／太宗台",
    "德津公園／全北大": "德津公园／全北大",
    "恩納／萬座毛": "恩纳／万座毛",
    "恭錫路": "恭锡路",
    "恰圖恰／阿里": "恰图恰／阿里",
    "惹蘭勿剎": "惹兰勿刹",
    "慶州南山": "庆州南山",
    "戶越／大井町": "户越／大井町",
    "拉威／神仙半島": "拉威／神仙半岛",
    "攀牙灣／瑤艾島": "攀牙湾／瑶艾岛",
    "新橫濱": "新横滨",
    "新港／紅磚倉庫／大棧橋": "新港／红砖仓库／大栈桥",
    "新界東北／荔枝窩": "新界东北／荔枝窝",
    "日本橋／人形町": "日本桥／人形町",
    "星街小區": "星街小区",
    "是隆／倫披尼": "是隆／伦披尼",
    "普門湖": "普门湖",
    "景福宮／北村／仁寺洞": "景福宫／北村／仁寺洞",
    "暹羅／水門": "暹罗／水门",
    "會安古城": "会安古城",
    "月城／校村／瞻星臺": "月城／校村／瞻星台",
    "木柵／動物園": "木栅／动物园",
    "本部／美麗海水族館": "本部／美丽海水族馆",
    "杭東／皇家公園": "杭东／皇家公园",
    "東京站／銀座／築地": "东京站／银座／筑地",
    "東仁洞": "东仁洞",
    "東區巷弄": "东区巷弄",
    "東城路／大邱站": "东城路／大邱站",
    "東大門／廣藏市場": "东大门／广藏市场",
    "東巴市場／長前橋": "东巴市场／长前桥",
    "東海岸／加東": "东海岸／加东",
    "東茶屋街": "东茶屋街",
    "東萊／溫泉場": "东莱／温泉场",
    "東陽佛院／升平": "东阳佛院／升平",
    "松山／饒河夜市": "松山／饶河夜市",
    "松島": "松岛",
    "查龍／大佛": "查龙／大佛",
    "棲鶴洞藝術村": "栖鹤洞艺术村",
    "植物園／荷蘭村": "植物园／荷兰村",
    "極樂寺／稻村崎": "极乐寺／稻村崎",
    "榮／伏見": "荣／伏见",
    "機張／海東龍宮寺": "机张／海东龙宫寺",
    "橫濱站": "横滨站",
    "正興街／國華街": "正兴街／国华街",
    "水原華城": "水原华城",
    "汝矣島／仙遊島": "汝矣岛／仙游岛",
    "江之島／腰越": "江之岛／腰越",
    "河原町五條": "河原町五条",
    "河濱／Asiatique": "河滨／Asiatique",
    "泉林湖／竹林禪院": "泉林湖／竹林禅院",
    "法國區／歌劇院": "法国区／歌剧院",
    "波達島／四島": "波达岛／四岛",
    "浮島通": "浮岛通",
    "海之中道／志賀島": "海之中道／志贺岛",
    "海理團街": "海理团街",
    "海雲台": "海云台",
    "海雲關": "海云关",
    "淺草／晴空塔": "浅草／晴空塔",
    "清澄白河／兩國": "清澄白河／两国",
    "港未來": "港未来",
    "源氏山／錢洗弁財天": "源氏山／钱洗弁财天",
    "漢南洞": "汉南洞",
    "漢拏山／思連伊林蔭路": "汉拏山／思连伊林荫路",
    "漢江／市中心": "汉江／市中心",
    "澀谷／原宿": "涩谷／原宿",
    "濟州市區／東門市場": "济州市区／东门市场",
    "濱松町／竹芝": "滨松町／竹芝",
    "濱海灣": "滨海湾",
    "灣仔／銅鑼灣": "湾仔／铜锣湾",
    "烏敏島／樟宜": "乌敏岛／樟宜",
    "烏節路": "乌节路",
    "熱田／金山": "热田／金山",
    "牛車水／中峇魯": "牛车水／中峇鲁",
    "珊瑚島／離島": "珊瑚岛／离岛",
    "甘川文化村／松島": "甘川文化村／松岛",
    "由比濱／材木座": "由比滨／材木座",
    "白壁／德川園": "白壁／德川园",
    "白馬國家公園": "白马国家公园",
    "白龍寺": "白龙寺",
    "皇理團路／大陵苑": "皇理团路／大陵苑",
    "皇陵區（嗣德陵／啟定陵／明命陵）": "皇陵区（嗣德陵／启定陵／明命陵）",
    "皇龍寺／芬皇寺": "皇龙寺／芬皇寺",
    "皮皮島": "皮皮岛",
    "真駒內／藝術之森": "真驹内／艺术之森",
    "石龍軍創意區": "石龙军创意区",
    "祇園／東山": "祇园／东山",
    "秋保溫泉": "秋保温泉",
    "秋葉原／神田": "秋叶原／神田",
    "立川／昭和紀念公園": "立川／昭和纪念公园",
    "竪町／新竪町": "竖町／新竖町",
    "第一郡／濱城市場": "第一郡／滨城市场",
    "第三坊／宮殿一號／林同博物館": "第三坊／宫殿一号／林同博物馆",
    "糸島": "糸岛",
    "糸滿／豐見城": "糸满／丰见城",
    "紙橋／民族學博物館": "纸桥／民族学博物馆",
    "細花里": "细花里",
    "美山聖地": "美山圣地",
    "美斯樂": "美斯乐",
    "美溪海灘": "美溪海滩",
    "老城區／還劍湖": "老城区／还剑湖",
    "聖水洞": "圣水洞",
    "聖淘沙／港灣": "圣淘沙／港湾",
    "舊左／萬丈窟／榧子林": "旧左／万丈窟／榧子林",
    "舊法國區／保大宮": "旧法国区／保大宫",
    "舞濱／東京迪士尼": "舞滨／东京迪士尼",
    "芭東": "芭东",
    "花園／Domaine de Marie": "花园／Domaine de Marie",
    "芹椰紅樹林": "芹椰红树林",
    "茵他儂山": "茵他侬山",
    "草悟道／科博館": "草悟道／科博馆",
    "莫埃來沼公園／東區": "莫埃来沼公园／东区",
    "萊雷": "莱雷",
    "萬禮／動物園": "万礼／动物园",
    "葛西臨海公園": "葛西临海公园",
    "葛飾／柴又": "葛饰／柴又",
    "董里離島／翡翠洞": "董里离岛／翡翠洞",
    "薄野／中島公園": "薄野／中岛公园",
    "藍廟／郭河畔": "蓝庙／郭河畔",
    "藻岩山／伏見": "藻岩山／伏见",
    "蘭塔島": "兰塔岛",
    "蠶室／樂天世界": "蚕室／乐天世界",
    "衛武營／鳳山": "卫武营／凤山",
    "裏原宿／貓街": "里原宿／猫街",
    "西子灣／哈瑪星": "西子湾／哈玛星",
    "西歸浦": "西归浦",
    "西湖／鎮國寺": "西湖／镇国寺",
    "西貢": "西贡",
    "西門市場／達城公園": "西门市场／达城公园",
    "西門町／萬華": "西门町／万华",
    "西陣": "西阵",
    "覺王山": "觉王山",
    "豐洲": "丰洲",
    "赤崁樓／神農街": "赤崁楼／神农街",
    "近江町／金澤站": "近江町／金泽站",
    "逗子／葉山": "逗子／叶山",
    "那霸市區／國際通": "那霸市区／国际通",
    "野毛／櫻木町": "野毛／樱木町",
    "金閣寺／北野": "金阁寺／北野",
    "鉢場陶瓷村": "钵场陶瓷村",
    "鎌倉站／小町通／鶴岡八幡宮": "镰仓站／小町通／鹤冈八幡宫",
    "長谷／大佛": "长谷／大佛",
    "閣格雷島／暖武里": "阁格雷岛／暖武里",
    "關內／馬車道": "关内／马车道",
    "關子嶺溫泉": "关子岭温泉",
    "阮太平街區": "阮太平街区",
    "難波／心齋橋": "难波／心斋桥",
    "霧峰": "雾峰",
    "靈福寺／茶園": "灵福寺／茶园",
    "青葉山／仙台城": "青叶山／仙台城",
    "鞍馬／貴船": "鞍马／贵船",
    "順安海灘／香江口": "顺安海滩／香江口",
    "頭流公園／文化藝術會館": "头流公园／文化艺术会馆",
    "飯田橋／神樂坂／後樂園": "饭田桥／神乐坂／后乐园",
    "香林坊／長町": "香林坊／长町",
    "香江南岸／新城區": "香江南岸／新城区",
    "駒込／六義園": "驹込／六义园",
    "高圓寺": "高圆寺",
    "高美濕地／清水": "高美湿地／清水",
    "鶴見": "鹤见",
    "鹽埕／駁二": "盐埕／驳二",
    "麥里芝／武吉布朗": "麦里芝／武吉布朗",
    "黃埔新村": "黄埔新村",
    "黃竹坑": "黄竹坑",
    "黃金町／日之出町": "黄金町／日之出町",
    "黑屋博物館／南邦": "黑屋博物馆／南邦",
    "龍山／梨泰院": "龙山／梨泰院",
    "龍理團街": "龙理团街",
}


def area_name(area: HotspotArea, locale: Locale) -> str:
    name = area.names.get(locale)
    if name:
        return name
    if locale == "zh-CN":
        traditional = area.names["zh-TW"]
        return SIMPLIFIED_AREA_NAMES.get(traditional) or traditional
    return area.names.get("en") or area.names["zh-TW"]


def area_payload(area: HotspotArea | None, locale: Locale) -> dict[str, str] | None:
    if area is None:
        return None
    return {"code": area.code, "name": area_name(area, locale)}
