from dataclasses import dataclass, field
from typing import Literal

LEGACY_DESTINATION_IDS = {
    "NRT": "tokyo",
    "KIX": "osaka-kyoto",
    "FUK": "fukuoka",
    "CTS": "sapporo",
    "OKA": "okinawa",
    "NGO": "nagoya",
    "ICN": "seoul",
    "PUS": "busan",
    "CJU": "jeju",
    "BKK": "bangkok",
    "CNX": "chiang-mai",
    "HKT": "phuket",
    "KBV": "krabi",
    "TPE": "taipei",
    "SIN": "singapore",
    "HKG": "hong-kong",
    "HAN": "hanoi",
    "SGN": "ho-chi-minh-city",
    "DAD": "da-nang",
}


@dataclass(frozen=True)
class DestinationProfile:
    code: str
    city: str
    country: str
    country_label: str
    timezone: str
    currency: str
    aliases: tuple[str, ...]
    areas: tuple[str, ...]
    estimated_flight_twd: int
    reason: str
    suggestions: dict[str, tuple[str, ...]] = field(default_factory=dict)
    destination_id: str | None = None
    role: Literal["primary", "secondary", "extension"] = "primary"
    parent_destination_id: str | None = None
    local_name: str | None = None
    english_name: str | None = None
    gateway_codes: tuple[str, ...] = ()
    center: tuple[float, float] | None = None
    recommended_days: tuple[int, int] = (4, 6)

    @property
    def id(self) -> str:
        return self.destination_id or LEGACY_DESTINATION_IDS[self.code]

    @property
    def is_searchable(self) -> bool:
        return self.role != "extension"

    @property
    def primary_gateway(self) -> str:
        return self.gateway_codes[0] if self.gateway_codes else self.code


DESTINATIONS: tuple[DestinationProfile, ...] = (
    DestinationProfile(
        "NRT",
        "東京",
        "Japan",
        "日本",
        "Asia/Tokyo",
        "JPY",
        ("東京", "东京", "Tokyo", "NRT", "HND", "TYO", "도쿄"),
        ("新宿", "上野／淺草", "東京站／銀座", "澀谷"),
        9_400,
        "航班、住宿與跨區交通選擇最完整",
        {
            "food": ("築地場外市場早餐", "淺草老舖與甜點散步", "新宿居酒屋晚餐"),
            "shopping": ("銀座與有樂町選物", "澀谷原宿購物散步", "上野阿美橫町採買"),
            "culture": ("淺草寺與合羽橋散步", "上野博物館與公園", "神樂坂文化街區"),
            "nature": ("明治神宮與代代木公園", "濱離宮庭園", "高尾山近郊健行"),
            "family": ("台場親子體驗", "上野動物園與公園", "東京灣親子散步"),
            "nightlife": ("澀谷夜景與巷弄餐酒館", "新宿夜間街區", "東京車站夜景散步"),
        },
    ),
    DestinationProfile(
        "KIX",
        "大阪／京都",
        "Japan",
        "日本",
        "Asia/Tokyo",
        "JPY",
        ("大阪", "京都", "Osaka", "Kyoto", "KIX", "ITM", "OSA", "오사카", "교토"),
        ("難波／心齋橋", "梅田", "京都站", "四條河原町"),
        8_600,
        "美食、購物與京都文化可在同一旅程搭配",
        {
            "food": ("黑門市場與難波美食", "道頓堀晚餐散步", "京都錦市場小吃"),
            "shopping": ("心齋橋與堀江選物", "梅田百貨與地下街", "京都河原町購物"),
            "culture": ("京都祇園與八坂神社", "大阪城與歷史街區", "伏見稻荷早晨散步"),
            "nature": ("嵐山竹林與河岸", "大阪中之島公園", "京都哲學之道"),
            "family": ("大阪灣親子景點", "天王寺公園與動物園", "京都鐵道博物館"),
            "nightlife": ("難波夜間美食巡禮", "梅田夜景", "京都先斗町晚餐"),
        },
    ),
    DestinationProfile(
        "FUK",
        "福岡",
        "Japan",
        "日本",
        "Asia/Tokyo",
        "JPY",
        ("福岡", "博多", "Fukuoka", "Hakata", "FUK", "福冈", "후쿠오카", "하카타"),
        ("博多站", "天神", "中洲", "大濠公園"),
        7_200,
        "機場離市區近，適合三至五日美食旅行",
        {
            "food": ("柳橋連合市場早餐", "博多拉麵與屋台晚餐", "天神在地咖啡巡禮"),
            "shopping": ("天神地下街與百貨", "博多站商場採買", "大名選物散步"),
            "culture": ("櫛田神社與博多町家", "太宰府文化一日遊", "福岡市博物館"),
            "nature": ("大濠公園與舞鶴公園", "海之中道近郊散步", "糸島海岸半日遊"),
            "family": ("海之中道親子一日", "福岡市科學館", "博多運河城親子時段"),
        },
    ),
    DestinationProfile(
        "CTS",
        "札幌",
        "Japan",
        "日本",
        "Asia/Tokyo",
        "JPY",
        ("札幌", "北海道", "Sapporo", "Hokkaido", "CTS", "삿포로", "홋카이도"),
        ("札幌站", "大通", "薄野", "中島公園"),
        11_800,
        "四季自然、溫泉與北海道美食主題鮮明",
        {
            "food": ("二條市場海鮮早餐", "札幌拉麵與甜點", "薄野北海道晚餐"),
            "shopping": ("札幌站商場", "狸小路商店街", "大通地下街"),
            "culture": ("北海道廳舊本廳舍周邊", "札幌啤酒博物館", "北海道開拓村"),
            "nature": ("藻岩山與札幌夜景", "小樽運河近郊一日", "定山溪溫泉散步"),
            "spa": ("定山溪溫泉慢旅", "札幌市區湯屋", "登別溫泉近郊一日"),
        },
    ),
    DestinationProfile(
        "OKA",
        "沖繩",
        "Japan",
        "日本",
        "Asia/Tokyo",
        "JPY",
        ("沖繩", "那霸", "Okinawa", "Naha", "OKA", "沖縄", "冲绳", "오키나와", "나하"),
        ("國際通", "那霸新都心", "北谷", "恩納"),
        9_800,
        "海島、親子與自駕路線適合放慢步調",
        {
            "food": ("第一牧志公設市場", "沖繩麵與島料理", "北谷海景晚餐"),
            "shopping": ("國際通與壺屋通", "那霸新都心採買", "瀨長島選物"),
            "culture": ("首里城公園與城下町", "壺屋陶器街", "沖繩縣立博物館"),
            "nature": ("萬座毛海岸", "古宇利島環島", "沖繩北部森林散步"),
            "family": ("沖繩美麗海水族館", "名護親子景點", "瀨長島親子散步"),
            "beach": ("恩納海岸半日", "北谷日落海灘", "古宇利島海景路線"),
        },
    ),
    DestinationProfile(
        "NGO",
        "名古屋",
        "Japan",
        "日本",
        "Asia/Tokyo",
        "JPY",
        ("名古屋", "Nagoya", "NGO", "나고야"),
        ("名古屋站", "榮", "伏見", "金山"),
        9_100,
        "適合串聯中部城市、主題樂園與在地美食",
        {
            "food": ("柳橋中央市場早餐", "名古屋飯與味噌料理", "榮地下街美食"),
            "shopping": ("名古屋站商場", "榮商圈", "大須商店街"),
            "culture": ("名古屋城與本丸御殿", "德川美術館", "有松老街"),
            "family": ("名古屋港親子一日", "鐵道館親子體驗", "近郊主題樂園"),
        },
    ),
    DestinationProfile(
        "ICN",
        "首爾",
        "South Korea",
        "韓國",
        "Asia/Seoul",
        "KRW",
        ("首爾", "首尔", "Seoul", "仁川", "Incheon", "ICN", "GMP", "SEL", "ソウル", "서울", "인천"),
        ("明洞", "弘大", "東大門", "江南"),
        7_800,
        "購物、美食、展覽與夜間活動密度高",
        {
            "food": ("廣藏市場早午餐", "望遠市場在地小吃", "乙支路烤肉晚餐"),
            "shopping": ("聖水洞選物與咖啡", "明洞與南大門採買", "弘大延南洞散步"),
            "culture": ("景福宮與北村韓屋", "國立中央博物館", "西村文化街區"),
            "nature": ("漢江公園散步", "首爾林", "北漢山輕健行"),
            "nightlife": ("乙支路巷弄夜生活", "弘大夜間散步", "漢江夜景"),
            "spa": ("韓式汗蒸幕體驗", "江南療癒半日", "市區美容與休息時段"),
        },
    ),
    DestinationProfile(
        "PUS",
        "釜山",
        "South Korea",
        "韓國",
        "Asia/Seoul",
        "KRW",
        ("釜山", "Busan", "PUS", "プサン", "부산"),
        ("西面", "南浦洞", "海雲台", "廣安里"),
        8_200,
        "海景、市場與城市交通適合四至五日慢遊",
        {
            "food": ("札嘎其市場海鮮", "南浦洞在地小吃", "西面豬肉湯飯"),
            "shopping": ("西面地下街", "南浦洞商圈", "新世界百貨採買"),
            "culture": ("甘川文化村", "影島文化空間", "釜山近代歷史館"),
            "nature": ("太宗台海岸步道", "冬柏島散步", "松島海岸路線"),
            "beach": ("海雲台海岸半日", "廣安里日落與夜景", "松亭海灘慢遊"),
            "nightlife": ("廣安里夜景晚餐", "海雲台夜間散步", "西面餐酒館"),
        },
    ),
    DestinationProfile(
        "CJU",
        "濟州",
        "South Korea",
        "韓國",
        "Asia/Seoul",
        "KRW",
        ("濟州", "济州", "Jeju", "CJU", "済州", "チェジュ", "제주"),
        ("濟州市", "涯月", "中文觀光區", "西歸浦"),
        9_600,
        "海岸、咖啡與自然步道適合自駕或包車",
        {
            "food": ("東門市場早午餐", "濟州黑豬肉晚餐", "海女海鮮料理"),
            "nature": ("城山日出峰", "漢拏山周邊步道", "偶來小路海岸散步"),
            "beach": ("涯月海岸咖啡路線", "咸德海水浴場", "中文海岸半日"),
            "family": ("濟州親子博物館", "西歸浦親子農場", "海岸親子慢遊"),
            "spa": ("濟州療癒森林", "海景休息與汗蒸", "西歸浦慢旅日"),
        },
    ),
    DestinationProfile(
        "BKK",
        "曼谷",
        "Thailand",
        "泰國",
        "Asia/Bangkok",
        "THB",
        ("曼谷", "Bangkok", "BKK", "DMK", "バンコク", "방콕"),
        ("暹羅", "Asok／素坤逸", "Silom", "河濱"),
        8_500,
        "美食、購物、寺廟與按摩行程選擇豐富",
        {
            "food": ("早晨市場與泰式早餐", "唐人街晚餐巡禮", "在地餐廳與甜點"),
            "shopping": ("暹羅商圈", "恰圖恰週末市集", "河濱夜市"),
            "culture": ("大皇宮與臥佛寺", "昭披耶河文化路線", "曼谷藝術文化中心"),
            "nightlife": ("昭披耶河夜景", "通羅餐酒館", "曼谷夜市散步"),
            "spa": ("泰式按摩與療癒時段", "市區水療半日", "河濱放鬆行程"),
            "family": ("暹羅親子景點", "河濱親子半日", "曼谷城市公園"),
        },
    ),
    DestinationProfile(
        "CNX",
        "清邁",
        "Thailand",
        "泰國",
        "Asia/Bangkok",
        "THB",
        ("清邁", "Chiang Mai", "CNX", "清迈", "チェンマイ", "치앙마이"),
        ("古城", "尼曼區", "湄平河畔", "夜市周邊"),
        10_500,
        "古城、咖啡、手作與近郊自然適合慢旅行",
        {
            "food": ("清邁市場與北泰早餐", "尼曼咖啡散步", "夜市北泰料理"),
            "shopping": ("週末步行街", "瓦洛洛市場", "尼曼設計選物"),
            "culture": ("清邁古城寺廟散步", "素帖山雙龍寺", "蘭納文化館"),
            "nature": ("茵他儂山近郊一日", "湄林自然路線", "皇家公園散步"),
            "spa": ("蘭納按摩與水療", "古城療癒半日", "尼曼慢活時段"),
        },
    ),
    DestinationProfile(
        "HKT",
        "普吉",
        "Thailand",
        "泰國",
        "Asia/Bangkok",
        "THB",
        ("普吉", "普吉島", "Phuket", "HKT", "普吉岛", "プーケット", "푸껫", "푸켓"),
        ("普吉老城", "芭東", "卡塔", "卡隆"),
        10_800,
        "海灘、跳島、度假村與夜生活可自由組合",
        {
            "food": ("普吉老城早午餐", "海鮮市場晚餐", "南洋風味料理"),
            "culture": ("普吉老城建築散步", "查龍寺", "在地文化館"),
            "nature": ("攀牙灣自然一日", "普吉南端觀景路線", "海岸森林散步"),
            "beach": ("卡塔海灘慢遊", "珊瑚島跳島", "芭東海灘日落"),
            "nightlife": ("芭東夜間街區", "海灘日落餐酒館", "普吉老城夜市"),
            "spa": ("度假村水療半日", "泰式按摩放鬆", "海景療癒時段"),
        },
    ),
    DestinationProfile(
        "KBV",
        "喀比",
        "Thailand",
        "泰國",
        "Asia/Bangkok",
        "THB",
        ("喀比", "甲米", "Krabi", "KBV", "クラビ", "끄라비", "크라비"),
        ("奧南", "喀比鎮", "萊雷", "克隆芒"),
        11_200,
        "島嶼、石灰岩海岸與悠閒度假節奏鮮明",
        {
            "food": ("喀比鎮市場早餐", "奧南海鮮晚餐", "週末夜市小吃"),
            "nature": ("虎窟寺與自然景觀", "翡翠池近郊一日", "紅樹林生態路線"),
            "beach": ("四島跳島一日", "萊雷海灘半日", "奧南日落散步"),
            "spa": ("奧南水療半日", "溫泉瀑布療癒路線", "海景按摩時段"),
            "family": ("四島親子路線", "奧南海灘慢遊", "喀比鎮親子夜市"),
        },
    ),
    DestinationProfile(
        "TPE",
        "台北",
        "Taiwan",
        "台灣",
        "Asia/Taipei",
        "TWD",
        ("台北", "臺北", "Taipei", "TPE", "TSA", "타이베이"),
        ("台北車站", "西門町", "信義區", "中山"),
        4_500,
        "交通便利，美食、文化與近郊自然適合短天數旅行",
        {
            "food": ("永康街與東門美食", "寧夏夜市", "大稻埕小吃散步"),
            "shopping": ("信義商圈", "中山站選物", "西門町"),
            "culture": ("故宮博物院", "大稻埕與迪化街", "中正紀念堂"),
            "nature": ("象山步道", "北投地熱谷", "陽明山半日"),
            "nightlife": ("信義夜景", "東區餐酒館", "饒河夜市"),
        },
    ),
    DestinationProfile(
        "SIN",
        "新加坡",
        "Singapore",
        "新加坡",
        "Asia/Singapore",
        "SGD",
        ("新加坡", "Singapore", "SIN", "シンガポール", "싱가포르"),
        ("濱海灣", "烏節路", "牛車水", "武吉士"),
        8_800,
        "城市緊湊、交通簡單，親子、美食與多元文化可一次體驗",
        {
            "food": ("熟食中心巡禮", "牛車水美食", "加東娘惹料理"),
            "shopping": ("烏節路", "濱海灣商場", "武吉士"),
            "culture": ("牛車水與小印度", "國家美術館", "甘榜格南"),
            "nature": ("濱海灣花園", "新加坡植物園", "南部山脊"),
            "family": ("聖淘沙親子一日", "動物園與夜間野生動物園", "科學館"),
        },
    ),
    DestinationProfile(
        "HKG",
        "香港",
        "Hong Kong",
        "香港",
        "Asia/Hong_Kong",
        "HKD",
        ("香港", "Hong Kong", "HKG", "홍콩"),
        ("中環／上環", "尖沙咀", "銅鑼灣", "旺角"),
        6_200,
        "城市景觀、飲茶、購物與離島路線密度高",
        {
            "food": ("上環早茶", "深水埗小吃", "廟街夜間美食"),
            "shopping": ("銅鑼灣", "尖沙咀", "旺角"),
            "culture": ("中上環歷史散步", "香港故宮文化博物館", "大館"),
            "nature": ("太平山步道", "龍脊健行", "南丫島"),
            "nightlife": ("維港夜景", "蘭桂坊", "廟街夜市"),
        },
    ),
    DestinationProfile(
        "HAN",
        "河內",
        "Vietnam",
        "越南",
        "Asia/Ho_Chi_Minh",
        "VND",
        ("河內", "河内", "Hanoi", "HAN", "ハノイ", "하노이"),
        ("還劍湖", "老城區", "西湖", "巴亭"),
        9_000,
        "老城街區、咖啡與歷史文化適合慢步探索",
        {
            "food": ("老城區河粉早餐", "同春市場", "西湖咖啡"),
            "culture": ("文廟", "昇龍皇城", "胡志明陵周邊"),
            "shopping": ("三十六古街", "同春市場", "河內設計選物"),
            "nature": ("還劍湖晨間散步", "西湖半日", "寧平近郊一日"),
            "nightlife": ("老城啤酒街", "還劍湖夜間散步", "法式街區晚餐"),
        },
    ),
    DestinationProfile(
        "SGN",
        "胡志明市",
        "Vietnam",
        "越南",
        "Asia/Ho_Chi_Minh",
        "VND",
        ("胡志明市", "西貢", "Ho Chi Minh City", "Saigon", "SGN", "ホーチミン", "호찌민", "호치민"),
        ("第一郡", "第三郡", "濱城市場", "草田"),
        9_500,
        "法式建築、市場、美食與夜生活集中",
        {
            "food": ("濱城市場周邊", "第三郡街頭美食", "草田咖啡"),
            "culture": ("統一宮", "戰爭遺跡博物館", "西貢中央郵局"),
            "shopping": ("濱城市場", "阮惠街", "草田選物"),
            "nightlife": ("阮惠步行街", "西貢河夜景", "第一郡餐酒館"),
            "nature": ("西貢河散步", "古芝地道近郊", "湄公河一日"),
        },
    ),
    DestinationProfile(
        "DAD",
        "峴港",
        "Vietnam",
        "越南",
        "Asia/Ho_Chi_Minh",
        "VND",
        ("峴港", "岘港", "Da Nang", "Danang", "DAD", "ダナン", "다낭"),
        ("美溪海灘", "漢江", "山茶半島", "會安古城"),
        10_200,
        "海灘、山景與會安古城適合度假慢遊",
        {
            "food": ("漢市場小吃", "海鮮晚餐", "會安古城料理"),
            "culture": ("占婆雕刻博物館", "會安古城", "五行山寺院"),
            "nature": ("山茶半島", "巴拿山", "五行山"),
            "beach": ("美溪海灘", "安邦海灘", "山茶海岸"),
            "family": ("巴拿山親子一日", "會安燈籠體驗", "海灘休閒日"),
        },
    ),
    DestinationProfile(
        code="RMQ",
        city="台中",
        country="Taiwan",
        country_label="台灣",
        timezone="Asia/Taipei",
        currency="TWD",
        aliases=("台中", "臺中", "Taichung", "RMQ", "타이중"),
        areas=("中區", "西區", "草悟道", "逢甲"),
        estimated_flight_twd=3_200,
        reason="老城街區、文化聚落與山海近郊適合慢遊",
        suggestions={
            "food": ("第二市場小吃", "第五市場散步"),
            "culture": ("霧峰文化路線", "中區老城散步"),
            "nature": ("大坑步道", "高美濕地黃昏"),
            "shopping": ("草悟道選物", "審計新村"),
        },
        destination_id="taichung",
        role="secondary",
        local_name="臺中",
        english_name="Taichung",
        gateway_codes=("RMQ",),
        center=(24.1477, 120.6736),
        recommended_days=(3, 5),
    ),
    DestinationProfile(
        code="KHH",
        city="高雄",
        country="Taiwan",
        country_label="台灣",
        timezone="Asia/Taipei",
        currency="TWD",
        aliases=("高雄", "Kaohsiung", "KHH", "가오슝"),
        areas=("鹽埕", "前金", "左營", "三多商圈"),
        estimated_flight_twd=3_000,
        reason="港都景觀、老城文化與南台灣美食集中",
        suggestions={
            "food": ("鹽埕小吃巡禮", "三民市場"),
            "culture": ("哈瑪星文化散步", "鳳山老城"),
            "nature": ("柴山步道", "旗津海岸"),
            "shopping": ("駁二選物", "新堀江散步"),
        },
        destination_id="kaohsiung",
        role="secondary",
        local_name="高雄",
        english_name="Kaohsiung",
        gateway_codes=("KHH",),
        center=(22.6273, 120.3014),
        recommended_days=(3, 5),
    ),
    DestinationProfile(
        code="SDJ",
        city="仙台",
        country="Japan",
        country_label="日本",
        timezone="Asia/Tokyo",
        currency="JPY",
        aliases=("仙台", "Sendai", "SDJ", "센다이"),
        areas=("仙台站", "一番町", "國分町", "青葉通"),
        estimated_flight_twd=12_000,
        reason="城下町文化、東北美食與松島近郊可組成四季行程",
        suggestions={
            "food": ("仙台朝市", "牛舌與在地料理"),
            "culture": ("青葉城與瑞鳳殿", "博物館巡禮"),
            "nature": ("松島海岸", "秋保溪谷"),
            "shopping": ("一番町商店街", "仙台站採買"),
        },
        destination_id="sendai",
        role="secondary",
        local_name="仙台",
        english_name="Sendai",
        gateway_codes=("SDJ",),
        center=(38.2682, 140.8694),
        recommended_days=(4, 6),
    ),
    DestinationProfile(
        code="KMQ",
        city="金澤",
        country="Japan",
        country_label="日本",
        timezone="Asia/Tokyo",
        currency="JPY",
        aliases=("金澤", "金沢", "Kanazawa", "KMQ", "金泽", "가나자와"),
        areas=("金澤站", "近江町", "香林坊", "東茶屋街"),
        estimated_flight_twd=11_000,
        reason="工藝、茶屋街與北陸飲食適合文化深度旅行",
        suggestions={
            "food": ("近江町市場", "主計町料理"),
            "culture": ("茶屋街工藝散步", "長町武家屋敷"),
            "nature": ("兼六園", "卯辰山"),
            "shopping": ("金澤工藝選物", "香林坊"),
        },
        destination_id="kanazawa",
        role="secondary",
        local_name="金沢",
        english_name="Kanazawa",
        gateway_codes=("KMQ",),
        center=(36.5613, 136.6562),
        recommended_days=(3, 5),
    ),
    DestinationProfile(
        code="HIJ",
        city="廣島",
        country="Japan",
        country_label="日本",
        timezone="Asia/Tokyo",
        currency="JPY",
        aliases=("廣島", "広島", "Hiroshima", "HIJ", "广岛", "히로시마"),
        areas=("紙屋町", "八丁堀", "廣島站", "和平公園"),
        estimated_flight_twd=10_500,
        reason="和平文化、瀨戶內景觀與宮島可兼顧歷史及自然",
        suggestions={
            "food": ("廣島燒村", "本通周邊料理"),
            "culture": ("和平紀念路線", "廣島城下町"),
            "nature": ("宮島彌山", "縮景園"),
            "shopping": ("本通商店街", "廣島站採買"),
        },
        destination_id="hiroshima",
        role="secondary",
        local_name="広島",
        english_name="Hiroshima",
        gateway_codes=("HIJ",),
        center=(34.3853, 132.4553),
        recommended_days=(4, 6),
    ),
    DestinationProfile(
        code="TAE",
        city="大邱",
        country="South Korea",
        country_label="韓國",
        timezone="Asia/Seoul",
        currency="KRW",
        aliases=("大邱", "대구", "Daegu", "TAE"),
        areas=("東城路", "半月堂", "壽城池", "大邱站"),
        estimated_flight_twd=8_000,
        reason="市場、近代街區與山城景觀兼具在地生活感",
        suggestions={
            "food": ("西門市場", "安吉郎烤腸街"),
            "culture": ("近代文化胡同", "藥令市"),
            "nature": ("八公山", "壽城池"),
            "shopping": ("東城路", "前山咖啡街"),
        },
        destination_id="daegu",
        role="secondary",
        local_name="대구",
        english_name="Daegu",
        gateway_codes=("TAE",),
        center=(35.8714, 128.6014),
        recommended_days=(3, 5),
    ),
    DestinationProfile(
        code="CEI",
        city="清萊",
        country="Thailand",
        country_label="泰國",
        timezone="Asia/Bangkok",
        currency="THB",
        aliases=("清萊", "เชียงราย", "Chiang Rai", "CEI", "清莱", "チェンライ", "치앙라이"),
        areas=("鐘樓", "夜市", "河畔", "舊城"),
        estimated_flight_twd=9_500,
        reason="蘭納藝術、山區自然與地方市場適合慢節奏探索",
        suggestions={
            "food": ("清萊夜市", "在地早市"),
            "culture": ("蘭納寺院路線", "地方藝術館"),
            "nature": ("辛哈公園", "山區茶園"),
            "shopping": ("週末步行街", "手工藝市集"),
        },
        destination_id="chiang-rai",
        role="secondary",
        local_name="เชียงราย",
        english_name="Chiang Rai",
        gateway_codes=("CEI",),
        center=(19.9105, 99.8406),
        recommended_days=(4, 6),
    ),
    DestinationProfile(
        code="DLI",
        city="大叻",
        country="Vietnam",
        country_label="越南",
        timezone="Asia/Ho_Chi_Minh",
        currency="VND",
        aliases=("大叻", "Đà Lạt", "Da Lat", "DLI", "ダラット", "달랏"),
        areas=("大叻市場", "春香湖", "第三坊", "舊法國區"),
        estimated_flight_twd=10_500,
        reason="高原氣候、法式街區、花園與咖啡產地適合深度慢遊",
        suggestions={
            "food": ("大叻市場", "高原咖啡巡禮"),
            "culture": ("舊法國建築", "地方工藝空間"),
            "nature": ("泉林湖", "高原瀑布"),
            "shopping": ("夜市", "農產選物"),
        },
        destination_id="da-lat",
        role="secondary",
        local_name="Đà Lạt",
        english_name="Da Lat",
        gateway_codes=("DLI",),
        center=(11.9404, 108.4583),
        recommended_days=(4, 6),
    ),
    DestinationProfile(
        code="TNN",
        city="台南",
        country="Taiwan",
        country_label="台灣",
        timezone="Asia/Taipei",
        currency="TWD",
        aliases=("台南", "臺南", "Tainan", "TNN", "타이난"),
        areas=("中西區", "安平", "孔廟", "海安路"),
        estimated_flight_twd=0,
        reason="由高雄延伸的府城古蹟、巷弄與飲食一日行程",
        destination_id="tainan",
        role="extension",
        parent_destination_id="kaohsiung",
        local_name="臺南",
        english_name="Tainan",
        gateway_codes=("KHH", "TNN"),
        center=(22.9999, 120.2269),
        recommended_days=(1, 2),
    ),
    DestinationProfile(
        code="GYE",
        city="慶州",
        country="South Korea",
        country_label="韓國",
        timezone="Asia/Seoul",
        currency="KRW",
        aliases=("慶州", "경주", "Gyeongju"),
        areas=("皇理團路", "大陵苑", "普門湖", "佛國寺"),
        estimated_flight_twd=0,
        reason="由釜山延伸的新羅古都文化一日行程",
        destination_id="gyeongju",
        role="extension",
        parent_destination_id="busan",
        local_name="경주",
        english_name="Gyeongju",
        gateway_codes=("PUS", "USN"),
        center=(35.8562, 129.2247),
        recommended_days=(1, 2),
    ),
    DestinationProfile(
        code="JEO",
        city="全州",
        country="South Korea",
        country_label="韓國",
        timezone="Asia/Seoul",
        currency="KRW",
        aliases=("全州", "전주", "Jeonju"),
        areas=("韓屋村", "南部市場", "客理團路", "完山公園"),
        estimated_flight_twd=0,
        reason="由首爾延伸的韓屋、飲食與地方工藝一日行程",
        destination_id="jeonju",
        role="extension",
        parent_destination_id="seoul",
        local_name="전주",
        english_name="Jeonju",
        gateway_codes=("ICN", "GMP"),
        center=(35.8242, 127.1480),
        recommended_days=(1, 2),
    ),
    DestinationProfile(
        code="HUI",
        city="順化",
        country="Vietnam",
        country_label="越南",
        timezone="Asia/Ho_Chi_Minh",
        currency="VND",
        aliases=("順化", "Huế", "Hue", "HUI"),
        areas=("皇城", "香江南岸", "東巴市場", "新城區"),
        estimated_flight_twd=0,
        reason="由峴港延伸的阮朝古都、香江與地方飲食一日行程",
        destination_id="hue",
        role="extension",
        parent_destination_id="da-nang",
        local_name="Huế",
        english_name="Hue",
        gateway_codes=("DAD", "HUI"),
        center=(16.4637, 107.5909),
        recommended_days=(1, 2),
    ),
    DestinationProfile(
        code="YOK",
        city="橫濱",
        country="Japan",
        country_label="日本",
        timezone="Asia/Tokyo",
        currency="JPY",
        aliases=("橫濱", "横浜", "横滨", "Yokohama", "YOK", "요코하마"),
        areas=("港未來", "關內／馬車道", "中華街／元町", "橫濱站"),
        estimated_flight_twd=0,
        reason="由東京延伸的港灣夜景、中華街與紅磚倉庫一日行程",
        destination_id="yokohama",
        role="extension",
        parent_destination_id="tokyo",
        local_name="横浜",
        english_name="Yokohama",
        gateway_codes=("NRT", "HND"),
        center=(35.4437, 139.6380),
        recommended_days=(1, 2),
    ),
    DestinationProfile(
        code="KMK",
        city="鎌倉",
        country="Japan",
        country_label="日本",
        timezone="Asia/Tokyo",
        currency="JPY",
        aliases=("鎌倉", "镰仓", "Kamakura", "KMK", "가마쿠라"),
        areas=("鎌倉站／小町通", "長谷", "北鎌倉", "由比濱"),
        estimated_flight_twd=0,
        reason="由東京延伸的古都寺社、大佛與江之電海岸一日行程",
        destination_id="kamakura",
        role="extension",
        parent_destination_id="tokyo",
        local_name="鎌倉",
        english_name="Kamakura",
        gateway_codes=("NRT", "HND"),
        center=(35.3192, 139.5467),
        recommended_days=(1, 2),
    ),
)


_BY_CODE: dict[str, DestinationProfile] = {}
_BY_ID: dict[str, DestinationProfile] = {}
for _destination in DESTINATIONS:
    _BY_CODE[_destination.code] = _destination
    _BY_ID[_destination.id] = _destination
    for _alias in _destination.aliases:
        if len(_alias) == 3 and _alias.isascii():
            _BY_CODE[_alias.upper()] = _destination


def destination_for_code(code: str | None) -> DestinationProfile | None:
    value = code or ""
    return _BY_CODE.get(value.upper()) or _BY_ID.get(value.casefold())


def destination_for_id(destination_id: str | None) -> DestinationProfile | None:
    return _BY_ID.get((destination_id or "").casefold())


SEARCHABLE_DESTINATIONS = tuple(item for item in DESTINATIONS if item.is_searchable)


def match_destination(text: str) -> DestinationProfile | None:
    folded = text.casefold()
    for destination in SEARCHABLE_DESTINATIONS:
        if any(alias.casefold() in folded for alias in destination.aliases):
            return destination
    return None


def infer_destination_region(text: str) -> str | None:
    matched = match_destination(text)
    if matched:
        return matched.country
    region_aliases = {
        "Japan": ("日本", "japan"),
        "South Korea": ("韓國", "韩国", "南韓", "south korea", "korea"),
        "Thailand": ("泰國", "泰国", "thailand"),
        "Taiwan": ("台灣", "臺灣", "taiwan"),
        "Singapore": ("新加坡", "singapore"),
        "Hong Kong": ("香港", "hong kong"),
        "Vietnam": ("越南", "vietnam"),
    }
    folded = text.casefold()
    return next(
        (
            region
            for region, aliases in region_aliases.items()
            if any(alias in folded for alias in aliases)
        ),
        None,
    )
